htdocs/pages/forumphp2015/appel-a-conferenciers-en.php
htdocs/templates/forumphp2015/appel-a-conferenciers-en.html
htdocs/templates/forumphp2015/fin_appel_en.html
htdocs/templates/forumphp2015/soumission_enregistree_en.html

Ajout du CFP en anglais pour le Forum PHP 2015 :
- Description en anglais du CFP.
- Message de succès en anglais après validation du formulaire.
- Message de fin de l'appel en anglais.

add call for speakers in en for forum 2015

---

htdocs/pages/administration/inscription.php
sources/Afup/AFUP_Base_De_Donnees.php
sources/Afup/AFUP_Personnes_Physiques.php

close #117 
I just improve the registration process with a "simple" `throwsException` flag.
I made some updates in the `AFUP_Personnes_Physiques` class.
Now we have complete messages. :sunglasses:

Improve registration error messages

---

dependencies/paybox/payboxv2.inc
htdocs/pages/forumphp2015/inscription.php
htdocs/pages/forumphp2015/paybox_retour.php

Activation du mode de retour serveur à serveur sur présence du paramètre $_GET['repondre_a'] sur la page de post de l'inscription.
Cela permet de faire alors une redirection vers le wordpress plutôt que le site legacy.

Paybox : retour serveur à serveur

---

htdocs/pages/forumphp2015/inscription.php

Le champ mobilite_reduite est obligatoire en base de données.
Si l'utilisateur ne coche pas "Oui" ou "non" sur son inscription, une erreur SQL est générée mais cependant l'inscription peut poursuivre (et donc le paiement, sans trace en base de données).

Correction erreur sql si mobilite reduite non coche

---

htdocs/templates/forumphp2015/conferenciers.html

Le champs "twitter" existe déjà en BDD et est déjà gérable depuis le backend administratif.
CSS permettant d'avoir le bouton twitter à coté du nom:
```css
article.conferenciers h3 {
float: left;
}
article.conferenciers a.twitter {
￼  margin-left: 20px;
}
article.conferenciers .article-body.conferencier {
clear: both;
}
```
Cela donnerait le rendu suivant:

Ajout du lien twitter pour chaque conférencier si celui-ci est connu

---

htdocs/templates/forumphp2015/forum_planning.html

Pour que les mots soient coupés au bon endroit dans [les navigateurs qui le supportent (autrement dit sur iOS)](http://caniuse.com/#feat=css-hyphens)

Amelioration de la vue responsive du planning

---

configs/application/pages.php

Corrige #135 
cc @hellosct1 et @perrick mais il me semble que cela suffise avant de développer une solution plus évoluée ? Si la liste des personnes doit être publique intra-afup, je ferai un autre commit.

Fix #135 Suppression de l'annuaire aux membres

---

sources/Afup/AFUP_Site.php

Si il n'y avait aucun article en base, un warning était affiché :
```
Warning: Invalid argument supplied for foreach() in /var/www/afup/sources/Afup/AFUP_Site.php on line 283
```

correction notice quand il n'y a aucun article en base

---

htdocs/pages/administration/forum_conferenciers.php

modification d'un conférencier : on affiche pas l'image si il n'y en a pas

---

htdocs/templates/forumphp2016/appel-a-conferenciers.html
translations/cfp.en.xlf

Description de la demande : 
> tout en bas, après le formulaire, il est indiqué "un dîner avec les membres de l'AFUP et les sponsors le soir du premier jour."
> 
> hors c’est la veille du premier jour...
ping @afup/communication

Forum 2016: Modification de la date du repas conférencier

---

configs/application/config.php.dist
cron/syncAfupSympa.php
htdocs/pages/administration/membre_ml.php
sources/Afup/Utils/Sympa.php

La conf actuelle pointe l'ancien domaine old.afup.org. Ce domaine a été coupé, on va donc accéder au serveur via son IP et forcer le host dans le header.

Correction mailing list

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/vote/liste.html.twig
app/config/routing/event.yml
htdocs/css/vote.css
sources/AppBundle/Controller/VoteController.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

On gère la pagination en récupérant 11 résultats par page au lieu de 10 => pas besoin de connaitre le nombre total de résultats pour afficher le lien vers la page suivante
On utilise l'id de la session (transformée en entier grâce à crc32) pour créer un ordre aléatoire "consistant" pour toute la session mais unique par utilisateur.

Consistent random

---

sources/AppBundle/CFP/PhotoStorage.php

Evidemment le test était à l'envers, les comptes qui n'ont pas d'ID n'ont pas encore de photo associée.

On delete les anciennes photos de comptes déjà sauvegardés

---

app/Resources/views/event/base.html.twig
app/Resources/views/site/talks/show.html.twig
app/config/config.yml
app/config/routing/talks.yml
app/config/services.yml
composer.json
composer.lock
htdocs/css/grid.css
htdocs/css/talk/show.css
htdocs/css/vote.css
htdocs/js/talk/list.js
sources/AppBundle/Controller/TalksController.php
sources/AppBundle/Event/Model/Repository/PlanningRepository.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Indexation/Talks/Transformer.php
tests/units/AppBundle/Event/Model/Talk/Talk.php
tests/units/AppBundle/Indexation/Talks/Transformer.php

A merger après avoir mergé la #272 
Ajoute une page semblable à celle-ci: 
(les images ne correspondent pas à la conf)
Il y a maintenant un lien sur la page de recherche:

Ajout d'une page de détail des conférences

---

htdocs/pages/administration/personnes_physiques.php
htdocs/templates/administration/personnes_physiques.html
sources/Afup/Association/Personnes_Physiques.php

Ajout de liens pour exporter la liste des membres: il y a deux liens, exporter tous les membres et exporter les membres actifs.
Capture d'écran du BO :
Sont exportés dans le CSV:
* email
* nom
* prenom
cf https://github.com/afup/web/pull/275

ajout export csv de la liste des membres

---

app/Resources/views/base.html.twig

Il y avait un espacement sur l'historique des conférences, le menu était
donc visible sur mobile sans avoir cliqué sur le hamburger.
Cela car une classe du layout de base a le même nom qu'une classe de la grille.
Afin d'éviter cet espacement, on force le padding sur cet élément.
//cc @mikaelkael

correction padding sur pages talks

---

app/Resources/views/base.html.twig
app/Resources/views/site/talks/list.html.twig
app/Resources/views/site/talks/show.html.twig
htdocs/app.php
htdocs/js/talk/list.js
sources/AppBundle/Indexation/Talks/Runner.php

* correction du lien vers la liste des talks du speaker depuis la page de détail : le filtre était pris en compte, mais la l'item n'était pas coché dans la liste des facettes. On ne pouvait donc pas le décocher et revenir à la liste complète. C'est maintenant corrigé.
* ajout facette article de blog
* ajout d'un lien vers la liste des talks de l'event depuis la page de détail
* tri chronologique des items de la facette événements

Changements sur les facettes

---

app/Resources/views/site/talks/list.html.twig
htdocs/js/talk/list.js
htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Indexation/Talks/Runner.php
sources/AppBundle/Indexation/Talks/Transformer.php
sql/2016-12-17-sessionLanguage.sql
tests/units/AppBundle/Indexation/Talks/Transformer.php

* ajout dans le BO d'un sélecteur de langue 
* passage de toutes les langues courantes en français
* ajout d'une facette de langue sur la page de recherche
la facette ressemble à cela:
(il faudra repasser sur les talks en anglais pour modifier le code de langue)

On permet de filtrer sur la langue des conférences

---

htdocs/js/talk/list.js

Il faut effectuer un and et pas un or pour avoir un comportement
cohérent avec les autres filtres de ce type.

correction filtrage sur le format

---

app/Resources/views/site/talks/show.html.twig
htdocs/css/talk/show.css

Le lien sera plus visible et sera mieux intégré lorsque le speaker
n'a pas de description.
avant:
après:
//cc @mikaelrandy

passage du rebond talks de speakers en dessous de la photo de celui-ci

---

app/Resources/views/site/talks/show.html.twig
htdocs/js/talk/list.js

Cela permettra d'être plus clair sur le type d'article demandé
(pour éviter de mettre par exemple des articles avec seulement un
lien vers les slides).

on renomme article de blog en transcript

---

htdocs/js/talk/list.js

Ajout d'une bouton permettant d'afficher plus de speakers
(dans la limite de 20).

ajout d'un bouton pour voir plus de speakers

---

app/config/routing/site.yml

Les numéros de facture ont été différenciés pour les adhésions récemment, entrainant un problème de routage sur les adhésions entreprises pour les paiements CB et le téléchargement des factures.

Fix adhesions entreprises

---

sources/AppBundle/Controller/MemberShipController.php

En passant à la ligne suivante si l'email n'est pas rempli sur une ligne de membre. La première ligne est gérée via la validation front.
Ce n'est pas imparable mais suffisant: au pire l'adhésion sera enregistrée mais aucune personne rattachée

On autorise moins de 3 membres entreprises

---

app/Resources/views/blog/planning.html.twig
htdocs/css/blog/planning.css

Je trouve que le planning n'est pas toujours très lisible au niveau des heures, voici un exemple
Il est difficile de comprendre précisément à quelle heure une conférence commence ou se termine.
Cette proposition vise donc à ajouter un minutage plus précis visuellement, voici ce que ça pourrait donner:

Amélioration de la lisibilité du planning

---

sources/AppBundle/CFP/PhotoStorage.php

FIX #324 preserve png transparency

---

app/Resources/views/event/ticket/ticket.html.twig
htdocs/css/tickets.css
sources/AppBundle/Controller/TicketController.php
sources/AppBundle/Event/Form/PurchaseType.php
sources/AppBundle/Event/Form/TicketType.php

En vrac:
* On réouvre automatiquement toutes les inscriptions en cas d'erreurs dans le formulaire
* On affiche un message en haut en cas d'erreur
* On autorise la possibilité d'avoir un lien pour revenir sur la page de paiement (via l'invoiceRef passé en get)
* On rend optionnel le numéro de téléphone

Fix sur les inscriptions

---

docker-compose.yml
event/resources/themes/basis_child/functions.php

en incluant :
```
[afup_website path="/blog/talk_widget?ids=2398,2401"]
```
dans les articles, on affichera les confs 2398 et 2401 ainsi
que les speakers liés (cf #446).

ajout shortcode pour inclure infos sur les articles des interviews

---

sources/AppBundle/Association/Model/User.php

Parfois le role MEMBER_EXPIRED reste en base, associé au user même
si celui-ci a payé sa cotisation.
Vu que ce role est recalculé à chaque fois il n'y pas besoin de le récupérer
de la base.
En le supprimant des roles récupérés depuis la base on contourne le problème.

contournement membre expiré persistant

---

sources/AppBundle/Command/TwitterListCreateCommand.php
sources/AppBundle/Twitter/ListCreator.php

Le PHPTour avec le titre le plus long est : "PHP Tour Clermont-Ferrand 2016".
Quand on tente de créer une liste nommée comme cela l'api twitter nous remonte :
```
The list failed validation: A list's name can't be this many characters long.
```
On ajoute donc une option a la commande pour pouvoir y mettre le nom que l'on souhaite.

correction commande de création de liste

---

htdocs/pages/administration/personnes_morales.php
htdocs/pages/administration/personnes_physiques.php
sources/Afup/Association/Personnes_Morales.php
sources/Afup/Association/Personnes_Physiques.php

Cette PR ajoute sur les pages de gestion des personnes morales la gestion du nombre de membre maximum permis par leur cotisation.
Elle ajoute également un simple champ permettant la gestion des rôles sur la page de gestion des personnes physiques.

FIX #445 nombre membres & roles

---

htdocs/pages/administration/forum_inscriptions.php
htdocs/templates/administration/forum_inscriptions.html

Dans le BO les billets gratuits perdaient leurs libellés.
Je supprime également le tableau "Nombre de personnes validées par type d'inscription" qui n'est pas clair et affiche des infos en doublon avec le grand tableau

Fix affichage BO billets gratuits

---

htdocs/pages/administration/personnes_physiques.php
sources/Afup/Association/Personnes_Physiques.php
sources/AppBundle/Controller/LegacyController.php

Suite au tweet https://twitter.com/eliesse/status/908695853795127296, voici le fix pour supprimer l'envoi des mots de passe en clair dans les mails d'inscriptions.
Il est possible qu'un tour sur le template 'confirmation-cr-ation-de-compte' doit être fait avant le merge.

Suppression du mot de passe en clair dans les mails

---

event/resources/themes/basis/header.php
event/resources/themes/basis_child/functions.php

On permet de d'ajouter un champ personalisé qui servira à
ajouter des metas afin d'afficher des twitter cards sur
les interviews.
Il existe des extensions, mais qui soient font trop de choses
en ajoutant les cartes en automatique conflictant avec l'extension
multilingue.
ou soit, pour d'autres extensions, permetant d'ajouter des metas,
seraient très fastidieuses à ajouter sur toutes les interviews.

ajout d'un champ personalisé pour mettre des metas sur les articles

---

event/composer.json
event/composer.lock

wordpress se met à jour tout seul dans cette version mineure,
il le fait après chaque déploiement vu qu'on downgrade à chaque fois
car on repars de la version du composer.lock.
Afin de toujours rester dans la même version, on mets à jour la version
dans composer.

mise à jour de wordpress en version 4.7.6

---

sources/AppBundle/VideoNotifier/TweetGenerator.php
tests/units/AppBundle/VideoNotifier/TweetGenerator.php

On profite de la généralisation des 280 chars chez twitter pour les tweets des vidéos

Vidéo Twitter: on passe la limite à 280 caractères

---

app/Resources/translations/validators.fr.yml
app/Resources/views/event/ticket/ticket.html.twig
htdocs/css/tickets.css
sources/Afup/Forum/Inscriptions.php
sources/AppBundle/Association/Model/Repository/UserRepository.php
sources/AppBundle/Association/Model/User.php
sources/AppBundle/Controller/TicketController.php
sources/AppBundle/Event/Model/Invoice.php
sources/AppBundle/Event/Model/Repository/TicketRepository.php
sources/AppBundle/Event/Model/Ticket.php
sources/AppBundle/Event/Validator/Constraints/CorporateMember.php
sources/AppBundle/Event/Validator/Constraints/CorporateMemberValidator.php
sql/2017-11-28-inscriptions-entreprises.sql

Les nouvelles règles d'inscriptions des entreprises incluent le fait qu'elles ont le droit de commander autant de places qu'elles ont de membres autorisés par leur cotisation.
Cette PR effectue donc les changements côté formulaire, ainsi que dans le BO au niveau de l'affichage de la validité des cotisations. Au passage les membres "classiques" profitent d'une amélioration: nous ne nous basons plus sur l'email pour effectuer la vérification de cotisations mais sur l'id du membre. Cela permettra d'éviter des cas de changement d'adresse mail rattachée au compte entre l'inscription et l'événement.

FIX #519: Changement règles inscriptions entreprises

---

htdocs/js/meetups/list.js

Cela permettra d'avoir tous les meetups à venir de chaque antenne
sur la première page si chaque antenne à un meetup à venir.

on passe le nombre de meetups par page à 14

---

htdocs/pages/administration/forum_conferenciers.php

Les photos des speakers n'étaient pas affichées dans le BO car l'id du forum était toujours NULL.

correction de la condition d'affichage des photos des speakers dans le BO

---

sources/AppBundle/Offices/OfficesCollection.php

@afup_lille sur twitter n'est pas le bon, c'est un ancien compte inactif depuis 6ans
Le blog n'est pas utilisé

Mise à jour antenne haut de france

---

sources/AppBundle/Event/Model/Speaker.php
sources/AppBundle/VideoNotifier/TweetGenerator.php
tests/units/AppBundle/VideoNotifier/TweetGenerator.php

Nous pouvions avoir des cas comme celui-ci qui se produisaient :
```
Les hexagones de la Ruche qui dit Oui ! La conférence de @https://twitter.com/trompouet à revoir sur le site de l'AFUP : https://afup.org/talks/2314-les-hexagones-de-la-ruche-qui-dit-oui
```

correction des tweets automatiques quand le compte twitter en base est l'url vers celui-ci

---

htdocs/pages/administration/forum_facturation.php
htdocs/templates/administration/forum_facturation.html
sources/Afup/Forum/Facturation.php

Cette feature est inutile puisque les factures sont désormais envoyées par mail dès réception du paiement.

Suppression "envoyer les factures réglées à tous" qui est inutile

---

app/config/config.yml
app/config/services.yml
sources/AppBundle/Event/Model/Repository/TicketRepository.php
sources/AppBundle/Event/Ticket/RegistrationsExportGenerator.php
sql/2018-05-05_emojis_tags.sql

les emojis sont maintenant supportés dans la commande de génération des badges.
par contre l'enregistrement en base lors de l'inscription ne fonctionnait pas (ainsi que l'export csv), cette PR corrige cela.

gestion des emojis sur la saisie/export des tags

---

app/Resources/views/event/cfp/edit.html.twig
app/Resources/views/event/cfp/propose.html.twig
sources/AppBundle/Event/Form/TalkType.php

Si on allait sur la page de modification d'une soumission, puis que l'on
soumettais le formulaire sans effectuer une modfication nous tombions
sur un message d'erreur car le champ un champ était requis.
Cela était dû à simpleMde. Afin de limiter les problèmes, on supprime la
validation html5. Il y a des contraintes sur l'objet talk, on a donc
des messages d'affichés si on ne saisi rien dans l'abstract.

correction sur la modification de soumission

---

.gitignore
Makefile
README.md
app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker
composer.json
composer.lock
db/migrations/20180526091813_init.php
db/migrations/20180526091813_init.sql
db/seeds/Users.php
docker/dockerfiles/mysql/Dockerfile
docker/dockerfiles/mysql/mysql_no_db
phinx.php
sources/Afup/Utils/Mail.php
sources/AppBundle/Controller/HomeController.php

Jusqu'à présent nous devons éxecuter à main les patchs que nous écrivions lors de la mise à jour.
Maintenant il y aura une commande pour pouvoir les passer (`php bin/phinx migrate`).
Après avoir l'utilisée quelques fois nous pourrons l'ajouter dans le script de déploiement.
De plus nous avions un problème au niveau des contributions : jusqu'à présent c'était surtout des membres du bureau, qui utilisent du contenu tiré de la production, qu'on ne peux pas fournir à des contributeurs.
Afin de simplifier les contributions externes nous avons besoin de données de test.
Ici nous commençons très simple avec juste un user, et au fur et à mesure quand nous aurons besoin de données de test nous pourrons les rajouter dans les seeds (il sera possible d'utiliser Faker). Pour ces seeds autant les …

Commande de passage de migration et seeds pour simplifier l'env de dev

---

app/Resources/views/site/talks/list.html.twig
db/migrations/20180607095749_video_subtitles.php
htdocs/js/talk/list.js
htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Indexation/Talks/Runner.php
sources/AppBundle/Indexation/Talks/Transformer.php
tests/units/AppBundle/Indexation/Talks/Transformer.php

Sur /talks on peux maintenant filtrer sur les talks qui sont sous titrés, via l'ajout de deux booléens en base. Pour l'instant sur la page on ajoute seulement le filtre sous titre français, mais dès qu'on aura des sous titres en anglais, on rajoutera le filtre.

Indication sous titrage sur page /talks

---

sources/AppBundle/Mailchimp/Mailchimp.php

On doit passer un offset et pas un numéro de page.
Cela ne posait pas de réel problème, mais on envoyait des inscriptions
en trop à chaque appel.

correction de la récupération de la liste des inscrits

---

db/migrations/20180705202558_conference_publication_date.php
htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

on permet d'indiquer une date de publication des confs.
cela permet de passer les confs sélectionnées en planifiée et leur donner accès à leur page speaker sans qu'ils apparaissent sur le programme / liste des speakers.
Cela permettra de planifier la publication des confs et ne pas être devant sa machine au moment de la publication.

Planification publication confs

---

app/Resources/views/base.html.twig
app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker
sources/AppBundle/Twig/TwigExtension.php

- Ajout de paramètres pour l'ID Google Analytics & son utilisation ou non (à `false` par défaut)
- Injection des variables en tant que globales dans `Twig_Environment`
- Utilisation de ces variables pour afficher / ou non GA
⚠️ Lors du déploiement il faut bien penser à ajouter les options correspondantes dans le fichier `parameters.yml`
- Fixes #639

639 ajouter une option pour activer ou non ga

---

db/seeds/Event.php
db/seeds/Users.php
sources/AppBundle/Event/Model/Speaker.php

J'avais commencé à regarder l'issue #631 et j'ai vu que c'était sur events.
Bref j'ai fait un seeder, autant le garder ça peut servir et j'ai modifier le seeder User pour qu'il soit toujours bon.
EDIT: Au final, après un peu de creusage j'ai réussi à accéder à la page correspondante et ai pu corrigé / tester le soucis.
- Fixes #631

631 rendre le champ societe optionnel lors de la creation dun profil de speaker

---

app/Resources/views/event/ticket/ticket.html.twig

On avait des lenteurs et timeouts sur le cdn du polyfill formdata.
En utilisant un CDN correct cela corrige le problème.
fixes #659

amélioration cdn du polyfill formdata

---

event/resources/themes/basis_child/header.php

On change les titres des pages sur event.afup.org afin de mieux référencer celles-ci :
| Page            | Titre avant                                               | Titre après                                          |
| --------------- |-----------------------------------------------------------| -----------------------------------------------------|
| Home            | `Forum PHP 2018`                                          | `Forum PHP 2018`                                     |
| Home Tour 2018  | `PHP Tour Montpellier 2018  \|   Forum PHP 2018`           | `PHP Tour Montpellier 2018`                          |
| Sponsors Forum  | `Sponsors  \|   Forum PHP 2018`                            | `Sponsors \| Forum PHP 2018`                          |
| Sponsors Tour   | `Sponsors  \| …

amélioration seo des titres sur event.afup.org

---

app/Resources/views/event/ticket/ticket.html.twig
db/migrations/20180815214957_tickets_nearest_office.php
sources/AppBundle/Event/Form/TicketType.php
sources/AppBundle/Event/Model/Repository/TicketRepository.php
sources/AppBundle/Event/Model/Ticket.php

cela sera utile à la fois pour améliorer l'accuracy des badges visiteurs (vu que l'adresse de facturation peux être différente de celle où habitent les inscrits), et sera utile pour savoir d'où viennent les visteurs de l'AFUP Day.

on permet de saisir l'antenne la plus proche dans le tunnel de commande

---

htdocs/pages/.htaccess
sources/Afup/Corporate/Rubrique.php
sources/AppBundle/Controller/CmsPageController.php

page contact avant:
page contact après:
page mentions légales avant:
page mention légales après:
les pages annuaire des prestataires et livre blanc, ainsi que l'index de divers ont été redirigées vers la home.

bascule pages contact sur le nouveau layout

---

app/AppKernel.php
app/config/routing.yml
app/config/routing/blog.yml
app/config/routing/event.yml
app/config/routing/global.yml
app/config/routing/meetups.yml
app/config/routing/news.yml
app/config/routing/site.yml
app/config/routing/talks.yml
composer.json
composer.lock

Première partie du sitemap: les routes statiques !
L'idée est de release la première partie sur le sitemap contant tout ce qui est route statique pour laisser le SEO commencer à se faire et enchainer plus tard sur une seconde partie qui aura les routes dynamiques (sans doute petit à petit vu qu'il y a pas mal de taf de ce côté là)
J'utilise: https://github.com/prestaconcept/PrestaSitemapBundle pour la génération du sitemap.
Related: #386

AFUP sitemap

---

event/resources/themes/basis_child/three_cols_section_banner.php

Cela va permettre de créer des boutons en colonne sur toute la largeur
qu'on utilisera pour l'AFUP Day.
La façon de faire est moche, mais on doit faire avec Wordpress.
Il faudra dans la config de la page, ajouter dans le html_head (on avait pas la main sur la config du page builder pour faire mieux).
```
<link rel='stylesheet' href="https://localhost:9215/wp-content/themes/basis_child/three_cols_section_banner.php?nth-child=2" type='text/css' media='all' />
```

event : page builder on permet d'avoir des profile (trois colonnes) en mode banner

---

.env-dist
.gitignore
Makefile
README.md
docker/dockerfiles/apachephp/Dockerfile
docker/dockerfiles/event/Dockerfile
docker/dockerfiles/planete/Dockerfile

L'installation du projet en utilisant [Docker For Mac](https://docs.docker.com/docker-for-mac/) rencontre un petit soucis de dépassement de limite d'utilisation de disque.
Cette PR ajoute une petite option à l'instruction `useradd` permettant de ne pas générer de logs lors de son execution (`--no-log-init` https://linux.die.net/man/8/useradd).
Ajout également de la possibilité de configurer l'exécution de docker.
Replace #629

Amélioration de la configuration Docker

---

app/Resources/views/event/ticket/sponsor.html.twig
sources/AppBundle/Controller/TicketController.php

Maintenant que sur la page sponsor on affiche des informations à propos
de l'événement, on permet toujours d'accéder la page des sponsors
via leur token, mais bloque la partie gauche de la page.

on permet d'affichager la page sponsor après la fin de la billeterie

---

htdocs/templates/administration/forum_inscriptions.html

on ne passait pas l'id du forum. du coup les liens d'export des badges
exportaient à chaque fois ceux du dernier forum.

on fait fonctionner les anciens exports des badges

---

app/Resources/views/admin/event/mail_inscription.html.twig
app/Resources/views/mail/_base_mail.html.twig
app/config/routing/admin_event.yml
app/config/services.yml
htdocs/pages/administration/forum_gestion.php
htdocs/templates/administration/forum_gestion.html
sources/AppBundle/Controller/AdminEventController.php
sources/AppBundle/Controller/TicketController.php
sources/AppBundle/Email/Emails.php
sources/AppBundle/Email/Parsedown.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Twig/TwigExtension.php

Jusqu'à présent il fallait créer un nouveau template dans mandrill.
Cette année celui-ci avait été oublié pendant une partie de l'ouverture de la billeterie,
ce qui a entrainé pas mal de support.
Afin d'éviter de l'oublier et de multipler les outils à la création d'un event,
on permet de saisir le contenu du mail dans le BO.
Le contenu est saisi en markdown.
Afin de pouvoir tester le rendu, on ajoute un controlleur pour envoyer un mail
de test.
De plus, cela permettra de limiter la dépendance à Mandrill pour pouvoir
utiliser juste la partie SMTP et plus l'api (ce qui permettra à termer de limiter
les coûts sur Mandrill/Mailchimp).

on permet de saisir le contenu du mail d'inscription dans le bo

---

sources/AppBundle/Controller/CFPController.php
sources/AppBundle/Notifier/SlackNotifier.php
sources/AppBundle/Slack/MessageFactory.php

Vu qu'on a 3 events en parallèle, il faut indiquer à quel event
correspond l'événement dans la notfif slack.
De plus on rajoute l'id de l'event dans le lien, afin d'arriver de
suite sur la bonne page.

améliorations info notification cfp

---

app/Resources/views/event/cfp/vote_only.html.twig
app/Resources/views/event/home.html.twig
app/Resources/views/event/ticket/ticket.html.twig

on affichait dans la description :
```
Proposez une conférence pour le AFUP Day 2019 Lyon qui aura lieu les 17-17 mai
```
on affiche maintenant :
```
Proposez une conférence pour le AFUP Day 2019 Lyon qui aura lieu le 17 mai
```
(jusqu'à présent on avait pas d'event d'une journée).

amélioration des cartes twitter des événements pour l'AFUP Day

---

sources/AppBundle/Event/Model/Talk.php

Si une conf avait été planifiée et se trouvait dans la table de planning,
puis qu'elle était annulée via la table des sessions, on l'affichait dans l'historique.
Il faut dans ces cas la masquer.

correction affichage des confs planifiées sur l'historique

---

htdocs/pages/administration/site_articles.php

L'année maximum lors de la saisie d'un article est l'année courante.
Parfois en fin d'année on veux commencer à écrire des articles dont la
date affichée sera l'année suivante.
Pour pouvoir le faire on permet de sélectionner l'année après l'année
courante dans la sélecteur.

on permet de saisir dans le bo des dates d'articles sur l'année suivante

---

sources/Afup/Association/Personnes_Physiques.php

* la condition sur les dates n'était pas bonne
* les personnes rattachées à une personne morale n'étaient pas forcément exportées
fixes #714

correction de l'export csv des membres à jour de cotisation

---

app/Resources/views/site/home.html.twig
sources/Afup/Corporate/Article.php

Quand le raccourci de l'article contenait un caractère urlencodé,
il été encodé deux fois : une première fois dans le lien, une seconde
lors de la redirection. On tombait donc sur des 404. Vu qu'on peux
difficilement modifier les raccourcis déjà existants, on met directement
le lien vers l'url de l'article (au passage, comme ça on évite la redirection).

correction du lien vers les articles dans la liste des news de la home

---

htdocs/templates/administration/forum_inscriptions.html
sources/AppBundle/Controller/AdminEventController.php
sources/AppBundle/Event/Model/Repository/TicketRepository.php

Lors de l'inscription au forum on a une case à cocher "Je souhaite être tenu au courant des rencontres de l'AFUP sur des sujets afférents à PHP".
On utilise ce flag dans l'export des inscriptions aux X derniers événements (qu'on utilise pour communiquer autour de la billeterie).

Export des inscrits aux derniers forums : on prends bien en compte l'autorisation d'envoi

---

sources/AppBundle/TechLetter/Form/SendingType.php

La newsletter de la veille est envoyé le mercredi toutes les deux semaines.
Il est alors intéressant de positionner par défaut la date d'envoi au prochain mercredi plutôt qu'une date arbitraire.

par défaut la date de la techletter est positionnée sur le prochain mercredi

---

htdocs/templates/administration/membre_cotisation.html

Correction sur la cotisation active et inactive, les icônes étaient inversés.

Erreur sur les icônes de statut de cotisation

---

event/resources/themes/basis_child/functions.php

Si l'interview était éditée en mode visuel et pas en mode texte l'url
était htmlencodée et l'esperluette n'était donc plus présente telle
quelle, on ne prennait donc plus en compte les derniers paramètres
de filtre qui permettent de choisir si on affiche le widget speaker
ou celui du talk. En décodant celui-ci on évite ce problème et permet
d'utiliser le mode visuel lors de la rédaction des interviews.

correction du widget des talks/speakers sur les pages d'interviews

---

Makefile

Ajout d'un target make pour ouvrir une console dans un container `cliphp`.
C'est très utile que la version de PHP n'est pas installé sur le poste.

Ajout d'un target pour la console PHP

---

sources/AppBundle/Event/Model/HydratorAggregator.php
sources/AppBundle/Event/Model/JoinHydrator.php

Parfois le joinHydrator ne renvoyais pas tous les résultats (un speaker n'était pas affiché sur la liste des speakers de Rennes).
On utilise donc le HydratorAggregator présent dans une version plus récente de ting et le proxifie dans le JoinHydrator afin de corriger cela.

correction affichage certains résultats

---

htdocs/pages/site/rss.php

L'auteur du flux rss était `Nicolas Silberman / AFUP`.
On corrige cela pour que ça soit seulement `AFUP`.

correction auteur flux rss

---

db/migrations/20190403055839_suppression_aperos_php.php

Lors  de l'initialisation  de la base de donnés la migration de suppression des tables liées aux apéros PHP bloque les migrations.
Cette PR corrige la migration pour supprimer les tables uniquement si elles existent.

correction des erreurs de migration de la db

---

app/Resources/views/site/talks/show.html.twig

on affiche la langue de la vidéo ainsi que les sous titres présents sur la page d'un talk

---

.env-dist
Makefile
docker-compose.override.yml-dist
docker-compose.yml
docker/dockerfiles/apachephp/Dockerfile
docker/dockerfiles/apachephp7/Dockerfile

Afin d'aider au débug, les images docker build xdebug.
Il faut activer xdebug dans le `.env` puis dans le fichier `docker-compose.override.yml-dist` il y a la configuration par défaut pour Xdebug.

ajout de xdebug dans les images docker

---

app/config/routing/talks.yml
app/config/services.yml
sources/AppBundle/Controller/TalksController.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Joindin/JoindinTalk.php
tests/units/AppBundle/Indexation/Talks/Transformer.php

Les liens de legacy.joind.in renvoient maintenant vers la home de joind.in
Vu qu'on a en base les id et non pas les slug, on passe par un controlleur pour récupérer le slug et faire la redirection.
fixes #792

correction des liens joindin sur migration site legacy

---

sources/AppBundle/Association/Model/User.php

suite à l'ajout de l'invitation slack on avait une erreur 500
à la soumission du formulaire de création de membre physique lié
à la personne morale.

correction de l'invitation de l'adhésion membre

---

sources/AppBundle/Event/Model/HydratorAggregator.php

si la requête ne renvoyait aucun résultat on yieldait tout de même
des tableaux vides/incomplets ce qui pouvait causer des erreurs 500.

correction retour de l'hydrator si la requête ne renvoie aucun résultat

---

sources/Afup/Forum/Forum.php
sources/Afup/Forum/Inscriptions.php

Avant avec le PHP Tour on appellait deux fois le la méthode
récupérant l'event précédent.
Maintenant avec l'AFUP Day on a plusieurs events à nombre variable.
On utilise donc le nom de l'événement pour trouver le précédent
et ainsi comparer le Forum à un Forum et non plus comparer le Forum
à un AFUP Day.
fixes #809

correction de la gestion du Forum précédent sur la page des stats

---

htdocs/templates/site/scss/components/subheader.scss

Parfois c'est utile de pouvoir cliquer sur l'item du menu courant.
Par exemple quand on est sur la page de détail d'un talk.
On ne pouvait pas le faire, c'est maintenant le cas.

on permet de clic sur l'item du menu courant

---

htdocs/pages/administration/personnes_physiques.php

Si les rôles sont vides on évite une erreur à la soumission du formulaire
car le json est invalide en mettant une valeur par défaut.
fixes #845

On évite une erreur à la modification d'un user si les rôles sont vides

---

app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker
sources/AppBundle/Command/IndexMeetupsCommand.php
sources/AppBundle/Indexation/Meetups/Runner.php

l'authentification via clef d'API n'est plus autorisée. il faut donc passer par oauth pour récupérer les derniers meetups.

on permet de s'auhentifier à l'api meetup en oauth

---

sources/AppBundle/Command/CfpNotificationCommand.php
sources/AppBundle/Command/TicketStatsNotificationCommand.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
sources/AppBundle/Slack/MessageFactory.php

* Sur les AFUP Day on a plus besoin de créer autant de commandes que d'événements
* Les commandes de notification pour le CFP peuvent être planifiées toute l'année et on aura pas de notification selon la config de date de fin dans l'admin
* On publie automatiquement sur la bonne room selon si c'est un AFUP Day ou un Forum

Meilleure gestion des notifications des événéments

---

sources/Afup/Association/Personnes_Morales.php

On utilise le nombre maximum de personnes et pas le nombre
de personnes actives.
fixes #668

correction du calcul de la cotisation des personnes morales

---

app/Resources/views/blog/program.html.twig
event/resources/themes/basis_child/style.css
sources/AppBundle/Controller/BlogController.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

Les liens s'affiche du join de l'event jusqu'à 10 jours après le dernier jour.

ajout d'un lien vers les fiches joindin sur la page de programme

---

htdocs/templates/administration/compta_journal.html

On avait deux lignes de filtrage qui ne fonctionnaient pas et ça augmentait
le temps de chargement de la page (le js de l'admin était chargé à la
fois dans le template spécifique au journal et dans toutes les pages du bo).

BO : on évite de charger deux fois tablefilter sur le journal

---

htdocs/templates/administration/forum_facturation.html

Permet de plus facilement les retrouver quand on a juste la référence.

ajout référence facture sur la liste des factures du Forum

---

app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker

Les deux fichiers de conf (parameters.yml.dist et parameters.yml.dist-docker) sont invalides. Il manque un guillemet manquant pour la clé meetup_api_consumer_secret

Fichiers yaml invalides

---

htdocs/pages/.htaccess
htdocs/pages/administration/membre_assemblee_generale.php

on évite de remettre l'ancien controlleur et permet de
faire fonctionner la redirection même si on a pas forcément tous
les droits sur l'admin.

amélioration de la redirection vers la page d'AG

---

sources/Afup/Forum/AppelConferencier.php

La recherche sur les speakers ne fonctionnait pas, c'est maintenant corrigé.

admin : correction de la recherche sur les speakers

---

app/config/config.yml
htdocs/pages/administration/forum_joind_in.php
htdocs/templates/administration/forum_joind_in.html
htdocs/templates/administration/forum_sessions.html

On a plus de cohérence dans la navigation et cela permet au passage
de choisir l'evénement, ce qui est utile pour les AFUP Day.

on déplace l'export joindin dans la page sessions

---

README.md
configs/application/config.php.dist
configs/application/config.php.dist-docker
sources/AppBundle/Command/DevCallBackPayboxCotisationCommand.php
sources/AppBundle/Payment/PayboxFactory.php

* ajout de documentation dans le readme
* on éviter l'identifiant de boutique en dur et défini celle de test dans la conf par défaut
* ajout d'une commande pour gérer le callback des adhésions (on devra faire la même chose pour les autres paiements)

On permet de facilement tester paybox en environnement de dev

---

sources/AppBundle/Controller/LegacyController.php

Depuis le 3f484c13d2bcc724214c522d3f452222177c779e il y avait une erreur 500
sur la page d'adhésion des personnes physiques (la variable $bdd était vide).
On efectue un premier fix (pas forcément très beau) pour faire fonctionner
cette fonctionnalité critique.

correction erreur 500 sur la page adhésion

---

sources/Afup/Bootstrap/commonStart.php

depuis la modification de la gestion des globales on avait plus
certains libellés d'affichés.

correction affichage libellés des tarifs sur la page inscription

---

dependencies/magpierss/extlib/Snoopy.class.inc
dependencies/magpierss/rss_cache.inc
dependencies/magpierss/rss_fetch.inc
dependencies/magpierss/rss_parse.inc
dependencies/paybox/payboxv2.inc

Lié à #768 
Changements :
* Reformatage du code
* Remplacement de `each` par `foreach`
* Mise à jour des constructeurs PHP 4
* Remplacement des utilisations de `$php_errormsg` par `error_get_last()`
* Remplacement de `split()` par `explode()` car l'usage dans le code ne nécessite pas une RegEx

[PHP7] Mise à jour des librairies legacy non portée

---

sources/AppBundle/Event/Model/Repository/TalkRepository.php

correction affichage durée de la conf et niveau dans le listing des conférences soumises par le conférencié dans la page CFP.
Augmentation de la limite du nombre de conférence affichée à 20 dans la page CFP.

Amélioration de la page conférencier pour les CFP

---

app/Resources/views/admin/event/bankwires.html.twig
app/Resources/views/admin/event/prices.html.twig
app/Resources/views/admin/event/rooms.html.twig
app/Resources/views/admin/event/speakers_management.html.twig
app/Resources/views/admin/event/special_price.html.twig
app/Resources/views/admin/event/sponsor_ticket.html.twig
app/Resources/views/admin/event/stats.html.twig
app/Resources/views/admin/speaker/list.html.twig
app/Resources/views/admin/vote/liste.html.twig
htdocs/pages/administration/forum_gestion.php
htdocs/templates/administration/forum_gestion.html
sources/AppBundle/Controller/Admin/Event/PendingBankwiresAction.php
sources/AppBundle/Controller/Admin/Event/PricesAction.php
sources/AppBundle/Controller/Admin/Event/RoomAction.php
sources/AppBundle/Controller/Admin/Event/SpeakersManagementAction.php
sources/AppBundle/Controller/Admin/Event/SpecialPriceAction.php
sources/AppBundle/Controller/Admin/Event/SponsorTicketAction.php
sources/AppBundle/Controller/Admin/Event/StatsAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerListAction.php
sources/AppBundle/Controller/VoteController.php
sources/AppBundle/Event/Form/EventSelectType.php

* Correction des erreurs 404 sur les pages de gestion des événements quand aucun identifiant d’événement n'est présent dans l'URL.
* Vérification de la possibilité de supprimer un forum avant la suppression.
* Correction du lien de suppression d'un forum.

Fix erreur admin

---

sources/AppBundle/Controller/CmsPageController.php

si un article est hors ligne ou en attente, il n'est visible que par les admins via le Front (http://afup.org/p/...)

Fix visibilité d'un article

---

app/config/services.yml
sources/AppBundle/Command/SynchMembersCommand.php
sources/AppBundle/Mailchimp/MailchimpMembersAutoListSynchronizer.php

On sychronise la liste membre automatique en arrière plan via une commande
qu'on lancera régulièrement dans une cron.
Cela permettra d'éviter des problèmes ou la liste n'est pas à jour.

ajout d'une commande de synchronisation de la liste membres-automatique

---

sources/AppBundle/Mailchimp/Mailchimp.php

le hash mailchimp doit être effectué à partir de la version minuscule
de l'adress mail.
Sans cela les appels PUT de modification ne fonctionnaient pas.

correction du hash mailchimp

---

sources/AppBundle/Mailchimp/Mailchimp.php
sources/AppBundle/Mailchimp/MailchimpMembersAutoListSynchronizer.php

Cela va permettre de corriger des erreurs de synchronisation et de limiter les personnes de la liste en les passant en archivées au lieu de les passer en unsubscribed. Cette réduction devrait permettre de réduire les coûts sur mailchimp.

améliorations sur la synchro des membres auto

---

sources/AppBundle/Association/UserMembership/AbstractUserReminder.php

Les mails de relance de cotisation étaient envoyés avec l'adresse sponsors
ce qui n'était pas logique. on utilise donc maintenant une adresse plus cohérente.

correction de l'adresse mail d'envoi des mails de relance

---

app/Resources/views/event/sponsorship_file/form.html.twig
sources/AppBundle/Event/Form/LeadType.php

Cela va éviter qu'on ait des bots qui utilisent ce formulaire pour envoyer des messages non solicités sur certaines adresses, qui sont potentiellement invalides et nous cause des problèmes de réputation sur Mandrill.

ajout du recaptcha sur la page de demande de dossier de sponsoring

---

.gitignore
htdocs/pages/administration/compta_journal.php
sources/Afup/Comptabilite/Comptabilite.php
sources/AppBundle/Compta/Importer/CaisseEpargne.php
sources/AppBundle/Compta/Importer/CreditMutuel.php
sources/AppBundle/Compta/Importer/Factory.php
sources/AppBundle/Compta/Importer/Importer.php
sources/AppBundle/Compta/Importer/Operation.php
sources/AppBundle/Model/ComptaCategorie.php
sources/AppBundle/Model/ComptaCompte.php
sources/AppBundle/Model/ComptaEvenement.php
sources/AppBundle/Model/ComptaModeReglement.php

Pas totalement terminé (pas encore le format définitif du Crédit Mutuel)
- refactoring de l'import du journal pour gérer 2 formats différents pour le Crédit Mutuel et la Caisse d'Epargne
- ajout de règles auto pour simplifier les imports
Peut être mergée en l'état, il suffira de valider le format une fois les premiers fichiers obtenus.

Import journal CMut et amélioration

---

sources/AppBundle/GeneralMeeting/GeneralMeetingRepository.php

Maintenant celui-ci est de "minimale d'au moins un quart des membres actifs".
fixes #1030

mise à jour de calcul du quorum suite à la mise à jour des statuts de février 2020

---

.github/workflows/ci.yml
.travis.yml

Avec les changements au niveau de l'offre de travis-ci :
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
et les lenteurs rencontrés sur ce service sur ces dernières semaines,
ainsi que le fait qu'on pourra plus facilement ensuite y ajouter d'autres tests
(migrer PrettyCi, lancer des tests fonctionnels ou d'analyse statique),
il sera une bonne chose de migrer vers Github Actions pour l'intégration continue :
c'est ce qu'effectue cette PR.
Merci à @oallain pour l'inspiration (sur https://www.synolia.com/synolab/outils/comment-tester-plugin-sylius/).

Migration des tests de travis-ci à Github actions

---

sources/AppBundle/Controller/MemberShipController.php

Si on était pas à jour lors de la création de l'AG et qu'on est maintenant à jour, on tombait
sur une erreur 500 en allant sur la page d'AG dans l'espace membre.
Il y avait cette erreur :
```
Feb  1 18:39:04 afupsvr01 [3016]: request.CRITICAL: Uncaught PHP Exception Assert\InvalidArgumentException: "Value "<NULL>" is null, but non null value was expected." at /home/sources/web/releases/20210130123711/vendor/beberlei/assert/lib/Assert/Assertion.php line 288 {"exception":"[object] (Assert\\InvalidArgumentException(code: 15): Value \"<NULL>\" is null, but non null value was expected. at /home/sources/web/releases/20210130123711/vendor/beberlei/assert/lib/Assert/Assertion.php:288)"} []
```
Cela est dû aux changements sur les repositories dans cette page (le commit …

correction erreur 500 sur la page de l'ag dans l'espace membre si on était pas à jour

---

.github/workflows/ci.yml

On passait par prettyci pour lancer le linter.
Ce service devait être arrêté en décembre 2020, notamment avec l'arrivée de Github Actions : https://prettyci.com/goodbye
On passe donc sur Github actions pour lancer ces tests, ce qui permettra de couper l'intégration à PrettyCI.

on lance le linter via github actions

---

sources/AppBundle/Controller/HomeController.php

cela permet d'éviter de faire des appels à l'API afin de rester en dessous
du quota.
On met en cache seulement une seule fois par jour (de toute façon l'index
n'est aussi mis à jour qu'une seule fois par jour).
Au passage on devrait aussi améliorer les perfs de la home.

ajout de cache sur la récupération des meetups sur la home

---

sources/Afup/Forum/Facturation.php

Sur le prochain AFUP Day les factures étaient mal affichées : le texte dépassait
de la cellule.
Cela car cette année le type de billet était plus long qu'à l'accoutumée.
On tronque donc le type de billet s'il est plus long que la cellule.

correction des factures envoyées pour le prochain AFUP Day

---

composer.lock

Bitbuckt est maintenance https://bitbucket.status.atlassian.com/incidents/5q0zhsqk5dxm
Du coup le composer install ne fonctionne plus.
Cela car on va cloner mandrill/mandril
De toute façon cette livrairie n'est plus utilisée depuis
qu'on est passée sur un envoi agostic via smtp.
On supprime donc cette dépendance inutile :
```
Removing mandrill/mandrill (1.0.55)
```

Suppression de la dépendance envers mandrill/mandrill

---

sources/AppBundle/Event/Model/Ticket.php
sources/AppBundle/Event/Ticket/RegistrationsExportGenerator.php

Il manquait du mapping sur les tarifs, on avait donc une 500.

correction sur l'export des inscriptions pour badges pour l'afup day 2021

---

htdocs/js/meetups/list.js

Rendu actuel lorsque les adresses sont `null`:
Cette PR fix cela

La page meetup affiche des `null` lorsque les adresses sont vides

---

sources/AppBundle/Controller/Admin/Event/PendingBankwiresAction.php
sources/AppBundle/Controller/Admin/Event/PricesAction.php
sources/AppBundle/Controller/Admin/Event/RoomAction.php
sources/AppBundle/Controller/Admin/Event/SpeakersManagementAction.php
sources/AppBundle/Controller/Admin/Event/SpecialPriceAction.php
sources/AppBundle/Controller/Admin/Event/SponsorTicketAction.php
sources/AppBundle/Controller/Admin/Event/StatsAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerListAction.php
sources/AppBundle/Controller/Event/EventActionHelper.php
sources/AppBundle/Controller/VoteController.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

On avait plus d'event par défaut sur les pages de l'admin, le contenu était vide et il
fallait sélectionner un event. Cela n'est pas pratique. Dans la pluspart des cas on
veux accéder à l'event en cours ou au dernier event et c'est ce que modifie cette PR.

corrections sur la gestion des events par défaut dans les pages de l'admin

---

event/resources/themes/hestia-pro_child/functions.php

Il n'est pas utile d'afficher le nom du créateur ou de la créatrice.
De plus, avec le passage sur Gutemberg, c'est compliqué de le modifié.
Là où on avait avant :
```
Published by communication on 26 avril 2018
```
(avec un lien sur "communication").
On a maintenant :
```
Publié le 26 April 2018
```

event : on masque la personne ayant écrit l'article

---

app/Resources/views/blog/talk.html.twig
event/resources/themes/hestia-pro_child/style.css

Suite à la mise en place du template plus moderne sur event.afup.org
les pages des interviews étaient devenues moins lisibles (les blocs
de conférence et speakers étaient moins dissociés du reste de la page).
Avec ces changements on rends plus lisible la page d'interview.
version avant nouveau template
version courante en prod
version avec cette PR

amélioration de la mise en forme des interviews sur event.afup.org

---

sources/AppBundle/Association/Form/UserEditType.php
tests/behat/features/Admin/AdminPersonnesPhysiques.feature

Quand on affichait, sur l'édition d'une personne morale le sélecteur de choix de personne physique,
on affichait le nom.
Maintenant sur le ChoiceType l'option ChoicesAsValues n'est plus utilisable.
Du coup il y a un array_flip de fait, et dans l'opération on perd une des personnes physiques si on avait un doublon.
Pour éviter cela, on fait un correctif (pas forcément idéal, mais fonctionnel), où on va afficher aussi l'id de
la personne morale dans le sélecteur.

correction affichage personnes morales homonymes sans le sélcteur d'édition des personnes physiques

---

app/Resources/views/blog/talk.html.twig

Cela permet d'avoir un libellé plus inclusif.

changement du libellé du bloc speaker sur les interviews

---

.github/workflows/ci.yml

Ubuntu 16.04 n'est plus supporté sur les Github Actions : https://github.com/actions/virtual-environments/issues/3287
Les tests ne se lançaient donc plus.
On utilise donc une version plus récente pour lancer nos tests avec shivammathur/setup-php vu que php 5.6 n'est pas sur ubuntu-18.04

mise à jour de la distribution utilisée en CI

---

docker/dockerfiles/apachephp/Dockerfile
docker/dockerfiles/apachephp7/Dockerfile

Hello,
En voulant commencer a contriuer pour l'hacktoberfest, je n'ai pa réussi à lancer le projet.
J'ai apporté quelques fixes au process de build afin de régler le soucis:
* Mise à jour complète des paquets. Principalement pour le paquet `ca-certificates` suite à la révocation du ROOT Let's Encrypt qui empechait la récupération du script d'installation nodejs.
* Refacto des installations de nodejs et yarn pour produire des images plus "light".
Les commandes `make docker-up` et `make init` sont désormais fonctionnelles.

Fix docker build

---

planete/app/PlaneteAppKernel.php

Suite de la pull request #1090 
J'avais oublié d'enlever sensio/generator-bundle sur le site planete-php.fr

Suppression du paquet sensio/generator-bundle sur planete-php.fr

---

app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker
app/config/security.yml

Avant on se basait sur l'IP. Avec le changement d'hebergement cela
sera plus adapté de se baser sur une clef d'API passée dans les entêtes
pour autoriser l'accès aux pages apellées depuis event.afup.org.

on permet d'accéder au blog via une clef d'API

---

event/composer.json
event/composer.lock

cf https://wordpress.org/news/2022/01/wordpress-5-8-3-security-release/

mise à jour wordpress en 5.8.3

---

htdocs/.htaccess

Sans cela on redirige vers une une ancienne page.

on redirige l'adresse become-sponsor pour pointer vers le dossier de lille

---

app/Resources/views/admin/slackmembers/index.html.twig
sources/AppBundle/Slack/UsersChecker.php

Les personnes physiques arrivant en fin de cotisation reçoivent plusieurs relances par mail dont la dernière est 15 jours après la date de fin de cotisation. 
Or, le tableau dans l'admin liste les personnes dont la cotisation vient juste d'expirer sans tenir compte de ce délai de 15 jours.

Issue #1133 pour changer le seuil de détection slackmembre

---

sources/AppBundle/Slack/MessageFactory.php

fixes #1153
cf https://github.com/afup/web/blob/6209d0f971c001f752301c1ffd3e8c8b8dfc2a88/sources/AppBundle/Event/Model/Repository/EventStatsRepository.php#L29
et https://github.com/afup/web/blob/6209d0f971c001f752301c1ffd3e8c8b8dfc2a88/sources/AppBundle/Event/Model/Repository/EventStatsRepository.php#L77
On affiche le nombre de confirmés (en attente de règlement ou non), afin d'éviter
de mal interpréter le nombre envoyé (les personnes ayant eut des problèmes de paiement / n'ayant pas finalisé leur inscription étaient comptées).

amélioration décompte du bot slack sur les inscrits

---

sources/AppBundle/Event/Model/Repository/TicketRepository.php
sources/AppBundle/Event/Ticket/TicketTypeAvailability.php

Quand on était sur un ticket 2 jours on enlevait tout le temps le nombre de tickets vendus max des deux jours
alors qu'il faut enlever le nombre total vendus du type (tout en gérant le cas où on aurait tout vendu sur les
autres types).
Le correctif avait déjà été effectué sur les maximums de tickets 1 jour, mais pas sur ceux 2 jours.
On corrige donc cela.

correction sur le calcul du nombre de tickets restants pour les maximums de tickets 2 jours

---

app/Resources/views/event/ticket/sponsor.html.twig
db/migrations/20220802172610_date_fin_vente_token_sponsor.php
db/seeds/Event.php
htdocs/pages/administration/forum_gestion.php
sources/Afup/Forum/Forum.php
sources/AppBundle/Controller/TicketController.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

On permet d'avoir une date de fin de vente des token sponsor différente de la billeterie.
Pour cela, on ajoute un nouveau champ en base, administrable et qu'on utilise sur le controlleur des tokens sponsor.

On permet d'avoir une date de fin de vente des token sponsor différente de la billeterie

---

app/config/routing/global.yml
htdocs/.htaccess
sources/AppBundle/Controller/LeadController.php
tests/behat/features/PublicSite/Sponsor.feature

Rend la redirection `/become-sponsor` dynamique vers le dernier événement courant.
Issue #1138

feat (#1138): redirection dynamique de become-sponsor

---

sources/AppBundle/Association/Model/User.php

Le needsUpToDateMembership est manuellement configuré pour certains
membres AFUP (bureau, coordinateur/coordinatrice modérateur/modératice d'antenne..),
il doit donc être à faux par défaut (il permet un reporting pour vérifier que ces
personnes soient bien à jour de leur cotisation).

correction de la valeur par défaut du needsUpToDateMembership

---

sources/Afup/Forum/Forum.php

Dans le BO le planning ne s'affiche pas après 18h.
Or cette année il est prévu d'avoir des slots après cet horaire.
Ce changement permet de générer dans le BO le planning jusqu'à 19h.
(pour le planning affiché sur event depuis le controleur de Blog, on a pas cette contrainte).

correction de l'affichage du planning dans le BO

---

sources/AppBundle/Event/Model/Repository/EventRepository.php

Une erreur 500 nous a été remontée lors de la validation d'un virement en attente.
Cela vient d'un problème lors de l'envoi du mail d'inscription, après validation.
Le mail est envoyé ici : https://github.com/afup/web/blob/46fe3e2f99a767f803afa334a21919a6ec408c89/sources/AppBundle/Controller/Admin/Event/PendingBankwiresAction.php#L123
Où on vérifie qu'on a bien le contenu administré disponible et sinon renvoie une exception : https://github.com/afup/web/blob/2bb8beaae2a81c3bbb9f2ac8b520a14851e2320c/sources/AppBundle/Email/Emails.php#L25
Ce contenu administré n'est pas disponible car on a récupéré un objet Event qui n'a pas le champ cfp (rempli avec la valeur "text") de renseigné.
Cela car vu qu'on est sur l'event par défaut on a pas fait de getid, mais un getNextEvent/getLastEvent : …

correction sur la validation des virements en attente

---

sources/AppBundle/Event/Ticket/RegistrationsExportGenerator.php

Je cache pas que j'ai un peu fait ça l'aveugle. 
J'avoue avoir raté un truc sur le mapping des colonnes entre "etat" et "status" mais je suis confiant :sweat_smile:

On n'exporte pas les billets en erreur de paiement pour la génération des badges

---

htdocs/calendrier/js/directives/FullCalendarDirective.js

Sur mobile on affichait ni le burger quiz ni la keynote de cloture, cela car on allait au maximum jusqu'à 18h.
Ce n'est pas le cas de ce Forum où on a des slots sur le créneau de 19h.
On augmente donc l'heure maximum du calendrier.
avant le fix
après le fix

on corrige le calendrier mobile pour les horaires après 19h

---

sources/AppBundle/Slack/UsersChecker.php

On peux se retrouver dans ces cas où on a un user sur slack qui n'a aucune cotisation, dans ce cas là on ne peux pas lui rajouter les 15 jours, on se retrouve avec une erreur 500 à cause d'un appel sur un null.

correction sur la vérification des users inscrits au slack

---

sources/AppBundle/Event/Form/SpeakerType.php

On demandait la personne référente et son mail alors que ça doit être seulement saisi dans le BO.

correction bug sur saisie speaker sur CPF

---

htdocs/css/vote.css

le texte du CPF était un peu petit, on l'augmente afin de lui donne plus de visibilité.
exemple avant:
exemple après:

on augmente la taille du texte du CFP

---

app/Resources/translations/validators.fr.yml
app/Resources/views/event/ticket/ticket.html.twig
db/seeds/EventTarif.php
db/seeds/Tarif.php
sources/AppBundle/Event/Form/PurchaseType.php
sources/AppBundle/Event/Form/TicketType.php
sources/AppBundle/Event/Model/Invoice.php
sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
sources/AppBundle/Event/Ticket/PurchaseTypeFactory.php
sources/AppBundle/Event/Validator/Constraints/TicketsCfpSubmitter.php
sources/AppBundle/Event/Validator/Constraints/TicketsCfpSubmitterValidator.php

Corrige le bug : https://github.com/afup/web/issues/1193
On vérifie qu'il y a eu au moins 1 CFP de proposer pour pouvoir bénéficier du tarif préférentiel.
Modification de la requête SQL pour faire le lien avec la table `afup_sessions`.
J'ai également ajouté un tarif préférentiel CFP (`'cfp_submitter_only' => true`) en fixture.

fix (#1193): tarif spécial CFP

---

db/migrations/20221020065442_tarif_event_description_nullable.php
sources/AppBundle/Association/Form/TicketEventType.php

**Impact**
Page d'administration - Tarification d'un événement
**Contenu**
- fichier migration DB
- mise à jour de la contrainte sur le champ description

feat (#1156): admin tarification evenement - rendre le champ description non obligatoire

---

docker/dockerfiles/mailcatcher/Dockerfile

les tests ne passaient plus car des versions sur les dépendances de mailcatcher avaient changée, on les force donc et évite d'avoir des erreurs comme celle-ci :
```
net-protocol requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
```
qui faisait que les tests fonctionnels ne tournaient plus (en plus de ne plus pouvoir utiliser mailcatcher sur on rebuilde en local)

correction installation mailcatcher

---

sources/AppBundle/Controller/EventController.php

la validation de l'url par openfeedback se fait coté client, c'est le navigateur qui fait la requête. On a donc une requête Cross Origin qui est faite et ne passait pas.
Afin d'éviter cela, on autorise openfeedback à faire l'appel en crossorigin.

configuration cors pour openfeedback

---

sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php

fixes #1221 
J'ai supprimé la variable `$response` en retour de l'appel à Mailchimp elle n'était pas utilisée de toute façon.
J'en ai profité pour ajouter la `timezone` dans le message de confirmation Mailchimp. C'est un point qui a été remonté dans Slack.

fix (#1221): corrige le problème de récupération de l'URL mailchimp

---

app/Resources/views/admin/slackmembers/index.html.twig

Ajout du lien vers la page d'administration des membres Slack directement dans la page du BO concernée pour faciliter la gestion des membres.

Add link to Slack member administration

---

htdocs/pages/administration/compta_banque.php
sources/Afup/Comptabilite/Comptabilite.php

Cela permet d'avoir dans l'export Excel une colonne avec le compte.
Une second PR va probablement venir pour faire un export unifié avec plusieurs comptes.

ajout du compte dans l'export Excel du journal de banque

---

Makefile

On avait cette erreur lors des tests fonctionnels en CI (et en local) :
```
[RuntimeException]
An error occurred when executing the "'cache:clear'" command:
// Clearing the cache for the dev environment with debug
// true
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 437895 bytes) in /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 227
22:07:06 CRITICAL  [php] Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 437895 bytes) ["exception" => Symfony\Component\Debug\Exception\OutOfMemoryException { …}]
In CacheClearCommand.php line 227:
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
437895 bytes)
```
Qui apparaissait lors du cache warmup …

correction erreur de memory limit lors du lancement des tests fonctionnels

---

sources/AppBundle/Compta/BankAccount/BankAccountFactory.php

quand on payait les billets par virement on tombait sur une 500.
En dev on avait cette erreur
```
Catchable Fatal Error: Argument 1 passed to AppBundle\Compta\BankAccount\BankAccountFactory::createApplyableAt() must implement interface DateTimeInterface, null given, called in /var/www/html/sources/AppBundle/Controller/TicketController.php on line 302 and defined
```
Cela car ici : https://github.com/afup/web/blob/a06958c90297e474cb02c33a149a16ec127d81fe/sources/AppBundle/Controller/TicketController.php#L301
la date est nulle vu que le paiement n'a pas été réalisé. (ça pourrait être utile plus tard sur les factures d'avoir une date d'émission en plus de cette date de paiement)
On se prémuni donc de ce genre de cas, en affichant si la date est nulle, le RIB le plus récent.

correction du paiement des billets par virement

---

sources/AppBundle/Email/Emails.php

Supprime l'email de l'organisateur dans le ICS de l'email d'inscription. Cela évite de se faire spammer via Google Calendar.

Suppression email organisateur dans email inscription

---

.github/workflows/ci.yml

ajout de cache sur les images docker pour ne pas les recréer à chaque fois et gagner en temps de test fonctionnels 
avant : 11 minutes
https://github.com/afup/web/actions/runs/3980011537/jobs/6822809025
après : 5 minutes
https://github.com/afup/web/actions/runs/3980160863/jobs/6823054240

ajout de cache sur les images docker lors des tests

---

sources/AppBundle/Mailchimp/MailchimpMembersAutoListSynchronizer.php

Lorsqu'on subscribait des personnes sur mailchimp parfois on pouvait avoir cette erreur (ici dans ce cas le statut est actuellement en "pending")
```
{"title":"Member In Compliance State","status":400,"detail":"****@*****.me is in a compliance state due to unsubscribe, bounce, or compliance review and cannot be subscribed.","instance":"5299cbb7-8605-bc4a-e8a0-9d5bf8fbedb3"}"
```
Du coup cela bloquait la synchronisation, on avait des comptes qui n'étaient pas ajoutés dans la liste.
Afin d'éviter cela si on a une erreur, on la catche, et on renvoie une exception à la fin.
La problème existe toujours et sera à corriger, mais il sera limité à un certain nombre de cas et permettra d'éviter d'avoir des membres non synchronisés.

on fait en sorte que s'il y a une erreur dans la synchro des membres auto, on ne bloque pas le reste de la synchro

---

app/Resources/views/event/speaker/page.html.twig

Suite a des échanges avec le pole antennes, on fait quelques ajustements sur la page speaker : 
en changeant des alignements sur les boutons / passer des formulaires sur une ligne ou textarea sur leur propre ligne, afin de clarifier la mise en page.
avant:
après:

amélioration de l'affichage de la page speaker

---

app/Resources/views/admin/techletter/index.html.twig
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/TechLetter/Model/Repository/SendingRepository.php
tests/behat/features/Admin/Techletter/AdminVeilleCampagnes.feature

Fix #1278 
Du coup, j'ai au passage remonté le formulaire de création d'une veille car, je ne trouvais pas logique de trier les veilles par ordre DESC, mais de devoir scroller jusqu'en bas de la page pour en créer une nouvelle.

Affichage de la liste des veilles par ordre chronologique décroissant

---

app/Resources/views/admin/speaker/list.html.twig

Quand on créait les inscriptions speakers pour un événément, ça le faisait tout le temps le dernier événement.
Cela car danss le controlleur on récupérait le paramètre id
https://github.com/afup/web/blob/7222a339c13ad9c98ddab87a158a8afd37dfeccf/sources/AppBundle/Controller/Admin/Speaker/SpeakerRegisterAction.php#L64
Mais que sur le lien on passait l'id de l'événement dans un paramètre eventId.
(et qu si on avait pas d'id on avait un fallback sur le premier prochain événement).

correction création des inscriptions speaker

---

sources/AppBundle/Controller/Admin/HomeAction.php

Lorsque je me connecte sur l'espace d'administration, j'ai une carte `Abonnements à la veille` qui est visible avec un lien `Voir plus`.
Or quand je clique sur ce dernier, j'ai une erreur 403.
En regardant les droits d'accès, je me rends compte que le droit correspondant à l'affichage de la carte n'est pas le même que celui qui restreint l'accès à la page en question:
https://github.com/afup/web/blob/9389b48835b170c6ecd71d38dd77ebf1a8120d8b/app/config/security.yml#L52

Correction du droit d'affichage de la carte 'Abonnements à la veille' sur la page d'accueil de l'admin

---

.github/workflows/ci.yml

cf https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
L'image qu'on utilisait a été supprimée, les tests en CI ne passaient plus, on corrige cela en utilisant une image qui existe.

changement du runner en ci suite à la suppression de l'image ubuntu 18.04

---

app/Resources/views/admin/speaker/add.html.twig
sources/AppBundle/Controller/Admin/Speaker/SpeakerAddAction.php

L'ajout ne fonctionnait pas et le champ n'était pas bien placé.
avant:
après:

correction de l'ajout info mastodon d'un speaker dans l'admin

---

sources/AppBundle/Email/Emails.php
tests/behat/features/Admin/Events/GestionEvenements.feature

Suppression de la mise en copie des mails d'inscription la trésorerie.
fixes #1291

suppression de la copie des mails d'inscription à la trésorerie

---

sources/Afup/Corporate/Accueil.php
sources/Afup/Corporate/Branche.php
sources/Afup/Corporate/Page.php
sources/AppBundle/Event/Ticket/RegistrationsExportGenerator.php
sources/AppBundle/Event/Ticket/SponsorTicketHelper.php
sources/AppBundle/Indexation/Meetups/Runner.php
sources/AppBundle/Payment/Paybox.php

Les propriétés de classe non déclarée ont été [dépréciées en PHP 8.2](https://php.watch/versions/8.2/dynamic-properties-deprecated)

Ajout de propriétés manquantes dans certaines classes

---

sources/Afup/Utils/Mailing.php

La variable `$champs` n'existe pas et ne sert donc à rien : https://3v4l.org/gkHaB
La fonction `obtenirEmails` ne semble plus servir nul part, on peut peut-être la supprimer ?

Suppression d'une variable inexistante

---

sources/Afup/Corporate/Articles.php

La variable dans le `if` était mal nommée.
La fonction `obtenirListe` n'est appelée qu'à un seul endroit avec la valeur par défaut donc il ne devrait pas y avoir d'impact : https://github.com/afup/web/blob/master/htdocs/pages/administration/site_articles.php#L57
Avec la variable inexistante la condition valait toujours `false` : https://3v4l.org/sYtqO

Correction d'un nom de variable

---

docker/dockerfiles/apachephp/Dockerfile
docker/dockerfiles/apachephp7/Dockerfile
docker/dockerfiles/planete/Dockerfile

Avec la sortie de bookwork, strech qui était en lts est passée en archivée cf https://www.debian.org/releases/stretch/
et https://www.debian.org/distrib/archive
On avait des erreurs comme celle-ci lors du build :
```
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://archive.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
E: Failed to fetch http://archive.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found [IP: 130.89.148.13 80]
E: Some index files failed to download. …
```

correction du build suite à la sortie de bookworm

---

sources/Afup/Comptabilite/Facture.php

La méthode `obtenirParNumeroFacture` n'a qu'un seul argument.
Les 3 en trop semblent venir d'un oubli lors d'un ancien refactor.

Suppression de paramètres inutilisés

---

sources/AppBundle/Security/ActionThrottling/ActionThrottling.php

La condition `isset($interval)` ne peut jamais être `false` car avec un `$delay` invalide, le `new \DateInterval` lance une exception qui arrête l'exécution avant le `if`.
https://3v4l.org/WvQe8#v5.6.40

Refactor de la validation `\DateInterval`

---

docker/dockerfiles/mailcatcher/Dockerfile

Les tests ne passaient plus vu qu'il y avait un souci avec le build de mailchatcher, ce changement fait passer le build de mailcatcher en évitant cette erreur :
```
Building native extensions. This could take a while...
ERROR:  Error installing mailcatcher:
The last version of mini_mime (>= 0.1.1) to support your Ruby & RubyGems was 1.1.2. Try installing it with `gem install mini_mime -v 1.1.2` and then running the current command again
mini_mime requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
```

correction du build

---

htdocs/css/tickets.css

On nous a signalé récemment sur linkedin que le rendu était cassé sur mobile, c'est effectivement le cas:
- Les label ne sont pas visibles car présents sur la droite
- Les champs dépassent de l'écran
- Les alignements sont douteux
Cette PR fixe une bonne partie des problèmes rencontrés.
Avant:
Après:
Il reste quelques trucs un peu cracra, mais c'est le mieux que je pouvais faire pour ne toucher qu'au css.
Au passage je forcer la taille en 16px sur mobile: pour les possesseurs d'iphone en dessous de cette taille, l'entrée dans un champ de formulaire provoque un zoom

Correction responsive billetterie

---

htdocs/templates/administration/compta_facture.html

Dans l'admin sur la liste des factures on peux maintenant filtrer sur l'année et sur l'état de paiement.
Cela permet de filtrer facilement sur les paiements en attente.

ajout de filtres sur les factures

---

htdocs/templates/administration/forum_inscriptions.html

On avait le badge à propos de l'adhésion qui était orange et attirait l'oeil alors que la ligne d'inscription était annulée.
On a pas besoin de mettre l'accent sur ces adhésions non à jour, on garde donc dans ce cas le badge gris.
avant:
après:

on grise le badge d'adhésion si la ligne d'inscription est annulée

---

sources/AppBundle/Event/Ticket/SponsorTokenMail.php

On envoyait la mauvaise date, on envoyait la date de fin de la billeterie et pas celle de saisie des tokens sponsor.

correction du mail envoyé aux sponsors

---

sources/AppBundle/Controller/Admin/HomeAction.php

Dans le cas où il n'y a pas de prochain événement en base de données cette erreur apparaît sur la home de l'admin :
Effectivement, `$this->eventRepository->getNextEvents();` peut retourner `null` dans ce cas et le `foreach` n'est pas content.
J'ai ajouté le test `&& $nextevents` pour corriger le problème.

corrige le problème de la home de l'admin

---

db/seeds/Compta.php
htdocs/templates/administration/compta_synthese.html
tests/behat/features/Admin/Tresorerie/BalanceComptable.feature
tests/behat/features/Admin/Tresorerie/Bilan.feature
tests/behat/features/Admin/Tresorerie/CompteBanques.feature
tests/behat/features/Admin/Tresorerie/Configuration.feature
tests/behat/features/Admin/Tresorerie/RechercheComptable.feature
tests/behat/features/Admin/Tresorerie/SyntheseEvenements.feature
tests/behat/features/PublicSite/Rss.feature

Trésorerie:
- Comptes banque
- Synthese événement
- Balance comptable
- Bilan
- Configuration
- Recherche comptable
Site web : 
- Flux RSS

feat (afup#1110): TF Administration - Trésorerie

---

app/Resources/views/admin/planete/feed_list.html.twig
app/Resources/views/site/member/index.html.twig
app/config/config.yml
db/seeds/FeedArticle.php
db/seeds/NiveauPartenariat.php
db/seeds/Users.php
tests/behat/features/Admin/AdminPersonnesMoralesCotisations.feature
tests/behat/features/Admin/Divers/Administrateurs.feature
tests/behat/features/Admin/Divers/Configuration.feature
tests/behat/features/Admin/Divers/Logs.feature
tests/behat/features/Admin/Divers/Sponsors.feature
tests/behat/features/Admin/Members/AdminMembersReporting.feature
tests/behat/features/Admin/PlanetePHP/BIllets.feature
tests/behat/features/Admin/PlanetePHP/Flux.feature
tests/behat/features/Admin/Tresorerie/RechercheComptable.feature
tests/behat/features/MembersArea/Index.feature
tests/behat/features/MembersArea/PersonneMorale.feature
tests/behat/features/MembersArea/Techletter.feature

Tests fonctionnel pour l'administration "Planete PHP" : 
- Flux
- Billets

feat (afup#1110): functionals tests

---

sources/AppBundle/TechLetter/MailchimpSynchronizer.php

On avait un peu plus de 40 mails qui n'étaient pas inscrits à cause de cela.

correction de la synchronisation de la veille

---

sources/Afup/Utils/Mailing.php

Seule la méthode `envoyerMail` est encore utilisée.
Cette PR fait suite à la #1297

Nettoyage de la classe `Mailing`

---

sources/AppBundle/Event/JsonLd.php

Les évènements d'une seule journée étaient mal gérés, la date étant
répétée deux fois : `les 12 et 12 May` au lieu de `le 12 May`.
Le nom du lieu de l'évènement est désormais correctement inclus dans la
description.

Correction de la description JSON-LD d'un évènement

---

app/Resources/views/site/news/list.html.twig
app/config/config_test.yml
db/seeds/Event.php
db/seeds/Feuilles.php
db/seeds/Session.php
db/seeds/Users.php
sources/AppBundle/Association/UserMembership/BadgesComputer.php
sources/AppBundle/Controller/MemberShipController.php
tests/behat/features/Admin/Events/Salles.feature
tests/behat/features/Api/Api.feature
tests/behat/features/Api/Talks/OpenfeedbackExport.feature
tests/behat/features/PublicSite/Members.feature
tests/behat/features/PublicSite/News.feature
tests/behat/features/PublicSite/Register.feature

API pour event :
- Planning
- Programmee
- Speakers
- Ical
Site public :
-  Home
- Actualités
-  Adhésion personne physique
- Retour paybox adhésion personne physique
- Mail post adhésion personne physique
- Adhésion personne morale
- Retour paybox adhésion personne morale
- Mail post adhésion personne morale
- Listing Entreprises

feat (afup#1110): functional test

---

composer.json
htdocs/pages/administration/compta_facture.php
htdocs/pages/paiement/index.php
sources/Afup/Utils/Utils.php
tests/units/Afup/Utils/Utils.php

Remplacement de la fonction `mcrypt_cbc` par `openssl_encrypt`.
J'ai repris des valeurs générées avec l'ancienne fonction pour créer les tests unitaires.
J'ai également laissé l'ancien code en commentaire pour pouvoir investiguer en cas de régression.

feat (afup#905): mcrypt CBC replace by openssl

---

sources/Afup/Utils/PDF_Facture.php

On évite de mettre le timestamp du fichier dans les métadonnées, ainsi les PDFs générés seront identiques peu importe le moment où ils sont générés et on pourra ainsi dans les prochaines PRs ajouter des tests sur ceux-ci (par exemple comparer des md5).
fixes #1344

Avoir des PDFs comparables

---

tests/units/Afup/Association/Cotisations.php

En lançant les tests à minuit, ceux-ci plantaient : https://github.com/afup/web/actions/runs/6963642073/job/18949581204
Cela car on ne précisait pas l'heure dans un des tests, c'est donc chose faite.

correction des tests unitaires quand on les lançait à minuit

---

sources/Afup/Comptabilite/Facture.php

Pour l'issue : #1347
Je propose de me baser sur le fait que l'`$index` soit `null` (changement d'année) pour aller chercher celui de l'année précédente.
Je garde aussi la possibilité qu'il n'y ai rien l'année précédente pour forcer l'incrémentation à 1.
fixes #1347

Génération des ids de facture

---

htdocs/pages/administration/compta_journal.php

En 2024, on utilisera plus l'export Excel, mais passera par l'export CSV (l'import coté comptable sera plus récurrent et automatisé qu'avant), il manquait les infos de justificatif, ce changement corrige cela.
fixes #1341

export CSV du journal : on ajoute les infos de justificatif

---

sources/AppBundle/Controller/Admin/Event/StatsAction.php
sources/AppBundle/LegacyModelFactory.php

Cela permet d'éviter de préciser le type à chaque utilisation.

Ajout de generics

---

composer.json
composer.lock
sources/Afup/Utils/PDF_Facture.php

On met à jour FPDF pour PHP 7. 0
Suppression de la partie `repository` du `composer.json` comme la version est maintenant disponible dans packagist.
Mise à jour faite via composer.
Traite l'issue #1331

PHP 7 upgrade fpdf

---

tests/behat/features/Admin/Divers/Configuration.feature

Lors de la PR https://github.com/afup/web/pull/1373 on s'est rendus compte que ce test influait sur les autres.
En effet, il consiste à modifier un fichier de conf sur le disque.
On fait donc en sorte de revenir à la valeur précédente une fois le test terminé (et on le fait sur la ville au lieu de l'adresse pour évite de se poser des soucis de sauts de ligne).
Ce n'est pas idéal, mais ici c'est tout ce mécanisme qui est à revoir plus tard pour mettre dans de la conf en dur les valeurs qui ne sont pas censées bouger et mettre en base les valeurs modiables depuis l'admin (comme la conf pour le planete par exemple).

test de la configuration : on remet la conf dans l'état précédent

---

sources/Afup/Tags.php

La méthode `echapper` n'accepte qu'un seul argument.

Suppression d'un paramètre inutile

---

sources/AppBundle/Command/CfpNotificationCommand.php
sources/AppBundle/Command/CleanThrottlingCommand.php
sources/AppBundle/Command/DevCallBackPayboxCotisationCommand.php
sources/AppBundle/Command/GeneralMeetupNotificationCommand.php
sources/AppBundle/Command/IndexMeetupsCommand.php
sources/AppBundle/Command/IndexTalksCommand.php
sources/AppBundle/Command/RegistrationsExporterCommand.php
sources/AppBundle/Command/SlackMemberNotificationCommand.php
sources/AppBundle/Command/SubscriptionReminderCommand.php
sources/AppBundle/Command/SynchMembersCommand.php
sources/AppBundle/Command/SynchTechLetterCommand.php
sources/AppBundle/Command/TicketStatsNotificationCommand.php
sources/AppBundle/Command/TwitterBotCommand.php
sources/AppBundle/Command/TwitterListCreateCommand.php
sources/AppBundle/Command/UpdateCompanyMemberStateCommand.php
sources/AppBundle/Command/UpdateMailchimpMembersCommand.php
sources/AppBundle/Command/UpdateUserStateCommand.php
sources/AppBundle/Command/VideosDataCommand.php

Il existe une constante `Command::SUCCESS` mais elle n'existe que depuis la version `5.1` de `symfony/console` : https://github.com/symfony/console/commit/27327a59875896d8b8e577ccddc35d92d7654664

Ajout d'un code de retour aux commandes

---

configs/application/config-test.php
configs/application/config.php.dist
configs/application/config.php.dist-docker
phpstan.neon
sources/Afup/Utils/Configuration.php
sources/Afup/Utils/SymfonyKernel.php

Corrige les erreurs ignorées par PHPStan : 
https://github.com/afup/web/actions/runs/7151424353/job/19476027508

fix phpstan ignore errors

---

app/Resources/views/event/ticket/ticket.html.twig
htdocs/js/inscription.js
htdocs/templates/site/scss/base/typography.scss
sources/AppBundle/Controller/TicketController.php

On affiche le prix HT unitaire, le prix HT, et précise quand les tarifs sont en TTC.
Sur le total on ajoute des entêtes pour clarifier le tableau vu les infos ajoutées.
fixes #1355
sans TVA:
avec TVA:

Gestion de la TVA dans le tunnel de vente

---

sources/Afup/Comptabilite/Comptabilite.php

Avec l'ajout du numéro de TVA il y a eut un décalage sur l'ajout de nouvelle entrée, ça a causé un souci à l'import.
Vu que la modification des lignes se fait via le numéro d'opération, il faudra supprimer les lignes mal importées.
De plus on pourra plus tard ajouter un test sur cet import assez critique (car on début d'année prochaine ajouter de nouvelles fonctionnalités dessus).

Fiscalisation : correction sur l''import du csv

---

sources/Afup/Comptabilite/Comptabilite.php
tests/behat/features/MembersArea/Index.feature

fixes #1390
Si on a pas de TVA de renseigné, le total n'est pas juste, on évite cela.

correction de l'export CSV des TVA

---

docker/dockerfiles/mailcatcher/Dockerfile

On avait ce souci :
```
1.565 (18/19) Installing .build-deps (0)
1.565 (19/19) Upgrading musl-utils (1.1.20-r5 -> 1.1.20-r6)
1.571 Executing busybox-1.29.3-r10.trigger
1.578 OK: 184 MiB in 47 packages
32.46 Building native extensions. This could take a while...
32.59 ERROR:  Error installing net-protocol:
32.59 	The last version of timeout (>= 0) to support your Ruby & RubyGems was 0.4.0. Try installing it with `gem install timeout -v 0.4.0` and then running the current command again
32.59 	timeout requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
32.61 Successfully installed io-wait-0.3.1
------
Dockerfile:15
--------------------
14 |
15 | >>> RUN apk add --no-cache --virtual .build-deps \
16 | >>>         ruby-dev \
17 | >>>         make g++ \
18 | >>> …
```

correction installation dépendances mailcatcher

---

app/Resources/views/admin/association/membership/membershipfee.html.twig
sources/AppBundle/Controller/MemberShipController.php

Le prix de la cotisation va passer à 150HT/180TTC au premier janvier au lieu de 150 sans TVA (donc dans les faits il ne bouge pas pour les entreprises).
Il faut appliquer cela sur le lien de paiement et le montant affiché.
fixes #1354

Fiscalisation : pour les personnes morales met le nouveau prix TTC de la cotisation

---

db/seeds/ComptaPeriode.php
db/seeds/Facture.php
htdocs/templates/administration/compta_facture.html
tests/behat/features/Admin/Tresorerie/DevisFactures.feature

fixes #1351
Cela permettra de tester plus tard le journal.
Et surtout cela va servir de base au développement pour afficher la TVA sur les PDF de factures.

Fiscalisation : ajout de donnees test journal/facture et tests sur les factures

---

sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/Controller/MemberShipController.php
sources/AppBundle/Controller/NewsController.php
sources/AppBundle/Controller/StaticController.php
sources/AppBundle/Controller/TechnoWatchController.php

La propriété `$container` est de type `ContainerInterface` dans laquelle il n'y a pas de méthode `getParameter`.
La méthode `getParameter` est directement accessible via un controller.

Utilisation de `getParameter` directement

---

sources/Afup/Comptabilite/Facture.php

On ne prenait en compte que la dernière ligne pour chaque taux de TVA.

correction du calcul du total de la TVA des devis/factures

---

sources/AppBundle/Controller/LegacyController.php

Proposition d'antispam pour le formulaire d'inscription. Issue #1395.
L'implémentation de recaptcha est trop complexe sur ce formulaire..
L'idée est d'avoir un CRSF token + un pot de miel.
À voir si cela calme le spam actuel.

#1395 Registration antispam

---

compose.override.yml-dist

```console
$make docker-up
CURRENT_UID=1000 ENABLE_XDEBUG= docker compose build
parsing /home/albin/Project/afup/web/compose.override.yml: yaml: unmarshal errors:
line 24: mapping key "mailcatcher" already defined at line 16
make: *** [Makefile:21 : var/logs/.docker-build] Erreur 15
```
puis
```console
$make docker-up
CURRENT_UID=1000 ENABLE_XDEBUG= docker compose build
service "apachephp7" has neither an image nor a build context specified: invalid compose project
make: *** [Makefile:21 : var/logs/.docker-build] Erreur 15
```
Corrige les 2 erreurs ci-dessus dans l'override du `docker compose`.
On a 2 fois `mailctaher` et `apachephp7` n'existe plus.

Corrige l'override de docker compose

---

sources/AppBundle/Controller/Admin/Talk/UpdateIndexationAction.php

Cela permet d'éviter d'avoir cette erreur en prod :
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

on augmente la limite de temps d'indexation des talks

---

.github/workflows/ci.yml

Traite l'issue #1330 en supprimant les tests unitaires en PHP 5.6 dans la CI.

CI Supprimer PHP 5.6 de la matrix tests unitaires

---

sources/Afup/Utils/PDF_Facture.php
tests/behat/features/Admin/Events/FacturesEvennement.feature
tests/behat/features/MembersArea/Index.feature

Suite à l'ajout du numéro définitif, on améliore l'alignement de cette info dans le footer.

amélioration de l'alignement du numéro de TVA intracommunautaire sur les factures

---

sources/Afup/Forum/Facturation.php

Le calcul de la TVA n'était pas bon quand on avait plusieurs lignes.

correction du calcul de la TVA sur les factures d'événement multilignes

---

app/Resources/views/site/become_member.html.twig

On précise quand les prix sont HT/TTC suite à la soumission à la TVA.

on ajoute les précisions HT / TTC sur la page d'adhésion

---

sources/AppBundle/Association/CompanyMembership/SubscriptionManagement.php
tests/behat/features/PublicSite/Register.feature

Quand on adhere en tant que personne morale on payait toujours 150€ au lieu des 180€ (TTC).
C'était bien le cas sur la page cotisation pour le renouvellement, mais n'était pas pris en compte lors de l'adhesion.
Maintenant ça donne cela:

correction du montant payé quand on adhere en tant que personne morale

---

app/config/config.yml
htdocs/app.php
htdocs/pages/planete/app.php

suite au https://github.com/afup/web/pull/1446
on reviens temporairement sur l'ancien session handler
car les routes comme la gestion des articles renvoient vers la page de login
ça serait lié à ce firewall quand on est sur une page non migrée ? https://github.com/afup/web/blob/3450893ffd7053c572555c4d1fb4f44043f4b4d9/app/config/security.yml#L20
//cc @stakovicz 
(je n'ai pas pu revert, vu qu'il y a eut des changements sur les fichiers entretemps)

on reviens sur l'ancien session handler

---

sources/Afup/Comptabilite/Comptabilite.php

Le calcul de la colonne TVA dans l'export CSV n'était pas bon, on exportait rien dans cette colonne si on avait une TVA à 10% mais pas de TVA à 20%.
On corrige donc cela.

correction du calcul de la colonne TVA sur l'export CSV

---

app/config/config.yml
app/config/config_test.yml
app/config/services.yml
htdocs/app.php
htdocs/pages/planete/app.php
sources/Afup/Bootstrap/Http.php

Le retour des sessions en base de données :hot_face: 
J'avais oublié un `session_start();` dans le fichier `Http.php` ce qui cassé l'authentification.
Cela ne s'est pas vu dans les tests fonctionnel car il y avait un mock de configuré.

afup#1415 Session in DB

---

Makefile

Pour ne plus avoir à remplacer le checksum lors de l'install, on utilise le bash depuis le site de getcomposer.org

change the composer install method

---

app/config/routing.yml
app/config/routing/planete_php_api.yml
app/config/services.yml
db/seeds/FeedArticle.php
sources/AppBundle/Controller/Planete/ArticlesController.php
sources/AppBundle/Controller/Planete/FeedsController.php
tests/behat/bootstrap/FeatureContext.php
tests/behat/features/Api/PlanetePHPApi.feature

Cette API va servir à sortir PlanetePHP comme voulu dans #1422 
Il y a deux routes exposées :
- `/planete-php-api/articles` : la liste des articles
- `/planete-php-api/feeds` : la liste des source actives

création d'une API pour les flux de PlanetePHP

---

sources/Afup/Utils/Configuration.php

Le temps de réponse a fortement augmenté depuis début février en PROD. Cela semble lié au chargement de la configuration (parsing yaml de fichiers) et l'accès au disque particulièrement lent en PROD.
En utilisant un tableau static, celui-ci n'est chargé qu'une fois. Cela fait une sorte de cache et économiser des parsing yaml multiple.

afup#1442 optimisation du chargement de la configuration

---

htdocs/js/inscription.js

Suite à une remonté sur le Slack : 
> Je viens de voir que sur mobile, en tout cas avec firefox, la page pour prendre sa place pour l'afup day affiche les blocs pour les 10 personnes malgré le fait que la liste déroulante est sur 1. J'ai eu beau changé la valeur dans la liste déroulante mais ça ne fait rien.
> Voilà bisous :envoie_un_bisou:
Voici la correction à la surcharge d'un `!important` dans le CSS ici : 
https://github.com/afup/web/blob/855a76d9b9276f9f445fab6201008c041f86b818/htdocs/templates/site/scss/base/responsive-mobile.scss#L7

Corrige la prise de ticket en mobile

---

sources/Afup/fonctions.php

Les formulaires sont toujours instanciés via `instancierFormulaire` qui retourne une classe qui hérite de `\HTML_QuickForm`.

[PHPStan] Correction d'une fonction globale

---

sources/AppBundle/Github/GithubClient.php

L'interface n'a qu'une seule implémentation et les méthodes `get` et autre n'y sont pas. À savoir que dans la v7 de Guzzle ces méthodes sont présentes de façon concrète dans la classe `Client`.
@see https://github.com/guzzle/guzzle/blob/7.8/src/ClientTrait.php#L42

[PHPStan] Dépendance sur la classe au lieu de l'interface

---

sources/AppBundle/Indexation/Meetups/MeetupScraper.php

La méthode `query` retourne une liste de `\DOMNode`, classe qui ne possède pas de méthode `getAttribute` comme la classe `\DOMElement`.

[PHPStan] Ajout d'une vérification de type d'un node

---

htdocs/pages/administration/compta_conf_regle.php

Correction d'un léger bug lors de la création/modification d'une règle de trésorerie.
Le N.C. correspondait a un taux de TVA de 0% (oops, pas bien).
J'ai donc ajouté un choix 0% dans la liste et mis celui du N.C. à `null`.

Configuration autorisation d'un taux à 0%

---

sources/Afup/Bootstrap/Http.php

On avait les notices d'affichées sur le site, par exemple sur la liste des admins :
```
Notice: Uninitialized string offset: 4 in /home/sources/web/releases/20240323070111/sources/AppBundle/Association/Model/User.php on line 849
```
on corrige cela en changeant la façon de récupérer l'env symfony

correction affichage des notices

---

htdocs/pages/administration/compta_conf_regle.php

On aavit un souci sur l'application des règles de mode de règlement : on avait les commissions de carte bancaires configuréees en virement mais, c'était le mode de paiement "Espèce" qui était sélectionné.
Le souci venait d'un array_merge pour la gestion du NC à null, où le tableau de liste des mode de règlement avec pour clef des int, il voyais deux tableaux non associatifs et recalculait les clefs.
cf https://www.php.net/array_merge
>  Values in the input arrays with numeric keys will be renumbered with incrementing keys starting from zero in the result array.
Voilà ce qui se passait où on peux voir les clefs recalculées :
```
php -r "var_dump(array_merge([null => 'N.C.'], [
2 => 'Carte bancaire',
3 => 'Virement',
4 => 'Chèque',
5 => 'Prélèvement',
]));"
array(5) {
[""]=>
string(4) …
```

correction application mode de règlement sur les règles automatiques de compta

---

Makefile

Petite proposition sur le Makefile avec :
- un target `help` qui affiche des sections et des descriptions pour les targets intéressants
- du rangement avec les targets "invisibles" en bas du fichier
- une rapide description pour chaque target
- le `help` devient le target par défaut au lieu de `install`
Pour qu'un target soit visible dans le `help` il faut deux choses :
- qu'il soit dans une section (une ligne dans ce format : `##@ Titre de la section`)
- qu'il y ait un commentaire au dessus du target (exemple : `### Super target`)
N'hésitez pas si certains points ne vous conviennent pas.
Voilà un rendu de ce que ça donne :

Ajout d'un target `help` au Makefile

---

sources/Afup/Corporate/_Site_Base_De_Donnees.php
sources/Afup/Utils/Base_De_Donnees.php
sources/Afup/Utils/Configuration.php

on est sur une connexion à la base sur le port par défaut actuellement et sur clever cloud on sera sur un port différent de 3306, il faut donc bien le préciser sur la classe historique de connexion à la base.

on fait en sorte de bien prendre en compte le port sur la connexion à la base de données

---

db/migrations/20240401121249_compta_zone_tva.php
htdocs/pages/administration/compta_journal.php
sources/Afup/Comptabilite/Comptabilite.php

fixes #1469 
on permet de typer avec une "zone de tva" les lignes de compta, cela pour pouvoir indiquer au comptable quand la ligne correspond à un sponsor hors union européenne;

Compta : mise en place des zones de TVA

---

sources/AppBundle/Command/IndexMeetupsCommand.php
sources/AppBundle/Indexation/Meetups/Runner.php

Le scraping des meetups se lançait avec une erreur silencieuse.
Si on modifiait le code pour faire un mustRun on voyait bien le souci :
```
[Symfony\Component\Process\Exception\ProcessFailedException]
The command "'./bin/console' 'scrapping-meetup-event'" failed.
Exit Code: 127(Command not found)
Working directory: /var/www
Output:
================
Error Output:
================
sh: 1: exec: ./bin/console: not found
```
La cron est lancée comme cela :
```
0 0 * * * www-data /usr/bin/php7.0 /home/sources/web/current/bin/console  --env=prod indexing:meetups
```
Cette façon de lancer la commande de meetups ne fonctionnait pas vu qu'on était pas dans le dossier /home/sources/web/current/
On change donc la façon de lancer le scraping pour le faire en dehors du runner et éviter d'avoir des …

correction du lancement du scraping des meetups

---

sources/AppBundle/Controller/LeadController.php

On avait cette erreur sur la demande de dossier de sponsoring :
```
May 23 19:22:37 afupsvr01 [3278]: request.CRITICAL: Uncaught PHP Exception Trello\Exception\RuntimeException: "Unauthorized for read-only workspace" at /home/sources/web/releases/20240523084005/vendor/cdaguerre/php-trello-api/lib/Trello/HttpClient/HttpClient.php line 152 {"exception":"[object] (Trello\\Exception\\RuntimeException(code: 401): Unauthorized for read-only workspace at /home/sources/web/releases/20240523084005/vendor/cdaguerre/php-trello-api/lib/Trello/HttpClient/HttpClient.php:152, Trello\\Exception\\PermissionDeniedException(code: 401): Unauthorized for read-only workspace at /home/sources/web/releases/20240523084005/vendor/cdaguerre/php-trello-api/lib/Trello/HttpClient/Listener/ErrorListener.php:30)"} [] …
```

correction 500 sur demande de sponsoring

---

sources/AppBundle/Event/Model/Repository/InvoiceRepository.php

nous avons dans la tarification quelques tarifs qui ne sont pas des entiers comme 272.73 €, qui doit donner 300€ en TTC.
Il était demandé de payer 299,2€ et pas 300€.
Cela car le ttc était calculé sur 272€ et non 272,73 car l'orm passait en int. On corrige cela en prenant bien en compte les 0,73 manquant.
avant:
après:

correction calcul ttc quand le prix ht n'est pas un entier

---

sources/AppBundle/Event/Form/SpeakerType.php

dans la PR https://github.com/afup/web/pull/1152
on mettait en place un préremplissage du formulaire de création de speaker d'après les informations saisies sur les anciens CFP, mais il y avait un souci, cela ne fonctionnait pas, le test sur le type du user était problématique.
fixes #1504

correction du réremplissage des informations des informations speakers

---

app/Resources/views/event/sponsor/scan.html.twig
app/config/routing/event.yml
sources/AppBundle/Controller/Exception/InvalidSponsorTokenException.php
sources/AppBundle/Controller/SponsorScanController.php

Partie 4 : export CSV des personnes dont le badge a été scanné.

QR Code Sponsor : export csv

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/sponsor/scan.html.twig
app/config/routing/event.yml
sources/AppBundle/Controller/SponsorScanController.php

Partie 5 : pouvoir supprimer un qr code si une personne demande finalement à ne plus être dans le fichier du sponsor.

QR Code Sponsor : supprimer le scan d'un visiteur

---

sources/AppBundle/Controller/Planete/ArticlesController.php
sources/PlanetePHP/FeedArticleRepository.php
tests/behat/features/Api/PlanetePHPApi.feature

Il ne faut compter que les articles ayant le status `RELEVANT` car ce sont les seuls affichés.
Ce header permet de conditioner la présence d'un bouton pour voir la page suivante des articles.
see #1422

[Planete PHP] Correction d'un header et ajout d'un autre

---

db/seeds/FeedArticle.php
sources/AppBundle/Controller/Planete/ArticlesController.php
tests/behat/features/Api/PlanetePHPApi.feature

Certains flux ont des articles pour lesquels l'url ne contient pas le host (`/foo` au lieu de `https://a.com/foo`).
Ce changement permet de s'assurer de toujours avoir une url contenant le host, en utilisant l'url du feed.
C'est le cas par exemple pour eleven-labs.com

Correction des urls sans host des articles

---

.github/workflows/ci.yml

L'action `satackey/action-docker-layer-caching` n'est plus maintenue depuis 3 ans.
Et elle ne fonctionne plus :
La nouvelle action met en cache les images directement.
Avec ce cache on gagne entre 5 et 7 minutes de build.

Utilisation d'une autre action pour le cache Docker

---

sources/AppBundle/Indexation/Meetups/MeetupScraper.php

Corrige le problème du scrapper Meetup qui fait planter les tests.
Meetup a ajouté un queryParam (`?eventOrigin=`) dans l'URL des events ce qui pose problème dans notre scrapper au niveau de l'expression régulière.
URL avant : 
```
https://meetup.com/bordeaux-php-meetup/events/300806782/
```
URL après : 
```
https://meetup.com/bordeaux-php-meetup/events/300806782/?eventOrigin=group_past_events
```
J'ai donc corrigé l'expression régulière.

Fix Meetup scrapper Event URL

---

sources/Afup/Comptabilite/Facture.php

Quand on avait saisi un numéro de TVA intercommunautaire sur un devis celui-ci n'était pas affiché, c'est maintenant le cas.

on affiche le numéro de TVA intercommunautaire sur les devis

---

htdocs/.htaccess
htdocs/pages/.htaccess

celle-ci sera gérée par clever cloud en forçant la redirection dans la config, et pose actuellement problème où on a une redirection
en boucle.
sur le site actuel, la configuration a été modifiée pour qu'elle soit gérée dans le vhost.

on enlève la condition de redirection en https 

---

app/config/services.yml
sources/AppBundle/Controller/HtmlSitemapController.php
sources/AppBundle/Site/Model/Repository/ArticleRepository.php
sources/AppBundle/Subscriber/TalksAndNewsSitemapSubscriber.php

J'ai réduit le nombre de requêtes SQL dans le plan du site version HTML en ajoutant une fonction qui permet de lister tous les articles en 1 fois.
J'ai également ajouté la liste des articles dans les sitemap.xml via le subscriber.

afupf#1180 allègement des requêtes SQL et ajout sitemap.xml

---

db/migrations/20240918112441_cotisation_type.php

Si on a des personnes morales avec 18 membres on a une cotisation en de 1080€ TTC.
Or le stockage est en float(5,2), c'est donc 999,99 qui était stocké en base.
Le paiement était fait avec la bonne somme, mais l'édition de la facture était à 1000€ TTC et non 1080€.
On augmente la taille du champ pour pouvoir gérer ce cas.

correction stockage montant cotisation

---

app/Resources/views/blog/planning.html.twig
sources/AppBundle/Controller/BlogController.php

Solves #1536 
Je n'ai pour le moment pas réussi à trouver ce rendu sur la version de dev pour tester si complètement ok
Cependant sur `/blog/forum/planning` (lié à `planningAction` du `BlogController`) voici les évolutions : 
Avant 1 seul évènement s'affichait quand il y en avait plusieurs sur la même salle à la même heure
Désormais plusieurs évents sont supportés
Je n'ai pas trouvé de tests et le code côté front et back et assez complexe. Si vous voulez je peux à l'occasion faire une refonte en TDD avec tests atoum + Behat. Côté front j'en ai profité pour ré-indenter et refaire 2/3 petits éléments en lien avec les index sur les slots.

Feat planning allow multiple talks in the same slot

---

app/Resources/views/blog/planning.html.twig

avec https://github.com/afup/web/pull/1537/files?diff=split&w=1
on perdait la hauteur des sessions,
on retourne donc sur le calcul de la hauteur de la session.
sans cela le rendu était comme cela:

correction affichage du planning

---

sources/AppBundle/Command/QrCodesGeneratorCommand.php

On a un cas très la la marge de chevauchement de qr_code (un seul).
En attendant un meilleur correctif et vu le délai on ajoute des options pour éviter de générer ce qr code problématique en doublon.

ajout d'options pour ne pas générer tous les qr_codes

---

app/Resources/views/site/base.html.twig
htdocs/templates/site/css/styles-without-compass.css
htdocs/templates/site/scss/base/layout.scss

En prévision de la migration sur Clever Cloud on l'ajoute dans le footer. Une fois la migration faite on pourra merger cette PR.
Voici le rendu :

Ajout de l'hébergement sur Clever Cloud dans le footer

---

clevercloud/scripts/cc_pre_build_hook.sh

Lors de l'upload du fichier de banque sur le journal on avait cette erreur :
```
Uncaught PHP Exception RuntimeException: "SplFileObject::__construct(/home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/htdocs/pages/administration/../../../tmp/banque.csv): failed to open stream: No such file or directory
```
Cela car le dossier tmp n'existait pas.
Dans la variable d'environnement `CC_PRE_BUILD_HOOK` on avait pour valeur  `yarn install --ignore-engines`, on crée un script pour avoir l'installation des dépendances node et pour créer le dossier tmp.
Il faudra remplacer la valeur de la variable `CC_PRE_BUILD_HOOK` par  `./clevercloud/scripts/cc_pre_build_hook.sh`.

on crée le dossier tmp à la racine du dossier APP_HOME

---

db/migrations/20241201133731_compta_id_clef.php

suite au https://github.com/afup/web/pull/1560
le fichier peux bien être uploadé, mais on a cette erreur :
```
Field 'idclef' doesn't have a default value" string(43) "Field 'idclef' doesn't have a default value" string(43) "Field 'idclef' doesn't have a default value"
```
Cela car on a pas de valeur par défaut sur le champ.
Ce champ est tout le temps vide :
```
MariaDB [afup]> select distinct idclef from compta;
+--------+
| idclef |
+--------+
|        |
+--------+
1 row in set (0.05 sec)
```
dans l'idée on pourrait potentiellement le supprimer, mais le plus simple dans l'immédiat vu qu'on doit importer le journal est de reproduire le comportement que l'on avait avant en ajoutant une valeur par défaut sur le champ.

on corrige le schéma de compte pour pouvoir importer le journal

---

sources/AppBundle/Event/Model/Repository/TicketRepository.php

Suite à la migration et au changement de version SBGD on avait cette erreur :
```
2024-12-03T18:56:37.367Z request.CRITICAL: Uncaught PHP Exception CCMBenchmark\Ting\Driver\QueryException: "Incorrect integer value: '' for column 'citer_societe' at row 1" at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/vendor/ccmbenchmark/ting/src/Ting/Driver/Mysqli/Statement.php line 118 {"exception":"[object] (CCMBenchmark\\Ting\\Driver\\QueryException(code: 1366): Incorrect integer value: '' for column 'citer_societe' at row 1 at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/vendor/ccmbenchmark/ting/src/Ting/Driver/Mysqli/Statement.php:118)"} []
```
si on ne cochait pas la case "J'accepte que ma société soit citée comme participant à la conférence".
Ce changement devrait corriger le souci en …

Correction 500 sur inscription si on ne cocher pas la case "citer société"

---

htdocs/pages/administration/site_articles.php
sources/Afup/Corporate/Article.php
tests/behat/features/Admin/Site/AdminSiteArticles.feature

Corrige l'enregistrement d'un article suite au changement de la base de données.
+ ajout d'un test fonctionnel.
> Uncaught PHP Exception RuntimeException: "Incorrect integer value: '' for column 'theme' at row 1" at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Utils/Base_De_Donnees.php line 238

Issue 1564 mariadb to mysql

---

sources/Afup/Forum/Inscriptions.php

Nous avions une erreur 500 lors de la modification d'une inscription.
Cela car il manquait un espace avant le where.
En effet, nous nous retrouvions avec une requête comme celui-ci :
```
facturation='0', transport_mode=10, transport_distance=0WHERE id=16411
```
On corrige cela en ajoutant un espace.

correction de la modification d'inscription

---

sources/Afup/Forum/AppelConferencier.php

Depuis le passage de mariadb `10.0.28-MariaDB-1~jessie` à MySQL 5.7, la modification de session ne fonctionne plus, il y a une erreur 500.
Voici le message d'erreur :
```
Uncaught PHP Exception RuntimeException: "Incorrect integer value: '' for column 'joindin' at row 1" at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Utils/Base_De_Donnees.php line 238
```
On corrige la requête de modification afin de ne pas mettre une chaine dans un champ en INT NULLABLE et ainsi éviter une erreur 500.

correction modification de session suite au changement de bdd

---

app/Resources/views/site/base.html.twig
app/Resources/views/site/offices.html.twig
sources/AppBundle/Offices/OfficesCollection.php

- (feat) Ajout de la possibilité d'avoir un linkedin et un bluesky pour les antennes 
- (feat) Vérification des liens des antennes et mise à jour des antennes concernées
- #1555 
On est sur une vieille version de fontawesome qui ne propose pas de lien bluesky. Je l'ai mis en SVG. 
Est-ce que ça vous choque ? 
Closes #1555

Réseaux Sociaux

---

sources/AppBundle/Event/Speaker/SpeakerPage.php
tests/behat/features/EventPages/SpeakerInfos.feature

Un speaker à remonter un problème lié à l'enregistrement de ses préférences pour sa venus :
> quand on renseigne sa venue au restaurant et qu’on clique sur “enregistrer”, on a bien le message “Informations sur votre venue au restaurant des speakers enregistrées” mais dans le BO, on n’a aucune info qui apparait en page “venue speakers” et le questionnaire est également vide quand on retourne sur le profil du speaker.
Le problème est lié au typehint des champs `Speaker->willAttendSpeakersDiner` et `Speaker->hasSpecialDiet`.
J'ai aussi amélioré le test behat.

corrige l'enregistrement des venues speakers

---

phpstan.neon
sources/Afup/Association/Cotisations.php
sources/Afup/Forum/Forum.php
sources/AppBundle/Association/Form/UserEditFormData.php
sources/AppBundle/Association/Model/GeneralMeetingQuestion.php
sources/AppBundle/Association/Model/Repository/GeneralMeetingQuestionRepository.php
sources/AppBundle/Association/Model/Repository/GeneralMeetingVoteRepository.php
sources/AppBundle/Command/QrCodesGeneratorCommand.php
sources/AppBundle/Controller/Admin/Event/ListAction.php
sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ReportsAction.php
sources/AppBundle/Controller/MemberShipController.php
sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
sources/AppBundle/Event/Model/Speaker.php
sources/AppBundle/Security/LegacyAuthenticator.php
sources/AppBundle/Security/LegacyHashAuthenticator.php
sources/AppBundle/Security/TalkVoter.php
sources/AppBundle/TechLetter/HtmlParser.php
tests/stubs/Ting/Repository/Repository.php.stub
tests/stubs/Ting/Repository/RepositoryFactory.php.stub

Grâce à la migration sur Clever Cloud et au passage à PHP 7.4 il y a des erreurs PHPStan qui sont devenu possibles à corriger.
Et donc on peut passer au niveau 2 minimum.
À savoir que j'ai dû ajouter des stubs pour surcharger des annotation de Ting qui sont incomplètes.
J'ai fait [une PR](https://github.com/ccmbenchmark/ting/pull/102) sur Ting qui a été merge mais la dernière version a besoin de PHP 8 au minimum donc en attendant on a besoin des stubs.

Passage au niveau 2 de PHPStan

---

htdocs/pages/administration/personnes_morales.php

On corrige l'affichage de l'état de la personne morale non finalisée.
Traite l'issue #597.

afup#597 corrige l'état de la personne morale

---

app/Resources/views/base.html.twig

Depuis la dernière MEP, nous avons des erreurs en PROD : 
> Exception thrown when handling an exception (Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "" as such route does not exist."). at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/app/Resources/views/base.html.twig line 11)
Cette MR corrige le problème.

Corrige amélioration indexation Google

---

htdocs/robots.txt

Ce fichier demande aux IA génératives de ne pas utiliser le site de l'AFUP pour leur entrainement. Les IA listées sont celles qui semblent respecter ces directives.
J'ai eu l'idée en découvrant ce genre d'horreur : https://techcrunch.com/2025/01/10/how-openais-bot-crushed-this-seven-person-companys-web-site-like-a-ddos-attack/
Ça peut potentiellement diminuer la charge sur le site aussi vu que certains de ces crawlers d'IA n'ont pas de limite de trafic.

Ajout d'un `robots.txt` pour les IA génératives

---

sources/AppBundle/Association/UserMembership/UserService.php
tests/behat/bootstrap/FeatureContext.php
tests/behat/features/Admin/PasswordReset.feature

fix: correction de URL dans le email de réinitialisation de mot de passe

---

db/seeds/Event.php

Corrige cette issue : https://github.com/afup/web/issues/1602
On impose l'heure du début de l’évènement à 00:00:00 ce qui permet de ne plus être impacté par l'heure d’exécution des tests pour le calcul du nombre de jours restant.

afup#1602 corrige le test flaky

---

sources/AppBundle/Controller/Website/MemberController.php

On a ce timestamp en base pour l'AG 1738969200
Il est récupéré coté PHP de cette façon : https://github.com/afup/web/blob/a5346935d2322fb0c2a366f1db7e663163d6eb2b/sources/AppBundle/GeneralMeeting/GeneralMeetingRepository.php#L44
Il a donc cette valeur :
```
var_dump(DateTimeImmutable::createFromFormat('U', '1738969200'));
object(DateTimeImmutable)#1 (3) {
["date"]=>
string(26) "2025-02-07 23:00:00.000000"
["timezone_type"]=>
int(1)
["timezone"]=>
string(6) "+00:00"
}
```
Le comparatif à la date courante ne fonctionne pas (l'AG est le 8).
On a une PR pour un début de fix plus global : https://github.com/afup/web/pull/1612/files
Mais ici pour faire fonctionner sur le facile d'accès au vu du temps imparti sans trop cassé on doit faire un fix un peu moche.
Cela permet de faire fonctionne ce …

quick fix affichage lien rapide de vote dans l'espace membres

---

.github/workflows/ci.yml
Makefile
app/config/config_test.yml

Cela permet de voir le type de dépréciation qui sont levées lors des tests fonctionnels afin de pouvoir les corriger avant de passer des mises à jour.
Cela rajouter des artefacts sur les tests fonctionnels : 
Dont un qui liste les dépréciations les plus fréquentes :

on loggue les dépréciations lors des tests fonctionnels

---

sources/Afup/Corporate/Rubrique.php
sources/AppBundle/Event/Model/Talk.php

On corrige des erreurs de PROD : 
```
2025-02-09T17:43:59.823Z request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: date() expects parameter 2 to be int, string given" at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Corporate/Rubrique.php line 187 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: date() expects parameter 2 to be int, string given at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Corporate/Rubrique.php:187)"} []
2025-02-09T17:58:05.715Z request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: date() expects parameter 2 to be int, string given" at …
```

Correction suite à #1609

---

sources/Afup/Association/Cotisations.php
sources/Afup/Corporate/Article.php
sources/PlanetePHP/FeedCrawler.php

Corrige des erreurs suite à la PR #1609.
Ça corrige aussi l'erreur de paiement survenu ce matin à 11h45.
```
2025-02-09T21:00:02.715Z (bas) CMDOUT (PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: array_reverse() expects parameter 1 to be array, null given in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/PlanetePHP/FeedCrawler.php:35)
2025-02-09T22:00:01.044Z request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Afup\Site\Corporate\Article::remplir() must be of the type array, bool given, called in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Corporate/Article.php on line 193" at …
```

Corrections suite à la PR #1609

---

sources/Afup/Corporate/Branche.php

Certaines pages du BO (notamment la tréso) ne fonctionnent plus à cause de ça.

Gestion de l'absence de racine

---

rector.php
sources/Afup/Utils/Mail.php
sources/AppBundle/Controller/Event/CFP/EditAction.php
sources/AppBundle/Controller/Event/CFP/IndexAction.php
sources/AppBundle/Controller/Event/CFP/ProposeAction.php
sources/AppBundle/Controller/Event/CFP/SidebarRenderer.php
sources/AppBundle/Controller/Event/CFP/SpeakerAction.php
sources/AppBundle/Controller/Website/MemberController.php
sources/AppBundle/Email/Mailer/Mailer.php
sources/AppBundle/Offices/OfficeFinder.php
sources/AppBundle/Twig/AssetsExtension.php
sources/AppBundle/Twig/OfficesExtension.php

On utilise le bon namespace pour Twig.
Utilisation de rector : `TwigSetList::TWIG_UNDERSCORE_TO_NAMESPACE`.

Change le namespace de Twig

---

sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ReportsAction.php
sources/AppBundle/Controller/Admin/Planete/FeedEditAction.php
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/Controller/Event/SpeakerSuggestionController.php
sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php
sources/AppBundle/Event/Speaker/SpeakerPage.php

On avance sur #1616.
Suite à la remonté des logs deprecated : 
> User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. {"exception":"[object
On vérifie que `isSubmitted()` soit bien appelé avant un `isValid()`.
Avant cette PR il y avait 64 logs maintenant il y en a 28. Cela semble provenir des vendors.

Deprecated isSubmitted() before isValid()

---

htdocs/pages/administration/compta_journal.php
sources/Afup/Comptabilite/Comptabilite.php

L'erreur survient quand on tente de ventiler une ligne.

Correction du type pour les IDs

---

.github/workflows/ci.yml

Ce cache semble persisté d'un run à l'autre (dans le cache Docker j'imagine) ce qui pose problème pour les tests fonctionnels.

Suppression du cache des tests

---

app/config/services.yml
sources/AppBundle/Command/CfpNotificationCommand.php
sources/AppBundle/Command/CleanThrottlingCommand.php
sources/AppBundle/Command/DevCallBackPayboxCotisationCommand.php
sources/AppBundle/Command/GeneralMeetupNotificationCommand.php
sources/AppBundle/Command/IndexMeetupsCommand.php
sources/AppBundle/Command/IndexTalksCommand.php
sources/AppBundle/Command/QrCodesGeneratorCommand.php
sources/AppBundle/Command/RegistrationsExporterCommand.php
sources/AppBundle/Command/ScrappingMeetupEventsCommand.php
sources/AppBundle/Command/SlackMemberNotificationCommand.php
sources/AppBundle/Command/SubscriptionReminderCommand.php
sources/AppBundle/Command/SynchMembersCommand.php
sources/AppBundle/Command/SynchTechLetterCommand.php
sources/AppBundle/Command/TicketStatsNotificationCommand.php
sources/AppBundle/Command/TwitterBotCommand.php
sources/AppBundle/Command/UpdateCompanyMemberStateCommand.php
sources/AppBundle/Command/UpdateMailchimpMembersCommand.php
sources/AppBundle/Command/UpdateUserStateCommand.php
sources/AppBundle/Command/VideosDataCommand.php
sources/AppBundle/Slack/Field.php

On supprime les dépréciations lié aux `Command`: 
1. Dans service.yml on active l'autowire et l'autoconfigure.
2. On remplace `ContainerAwareCommand` par `Command` donc on injecte les services qui vont bien.
Toujours en préparation de la migration vers Symfony 4.4 : https://github.com/afup/web/issues/1616
(ça manque de tests pour être plus tranquille)

Suppression des dépréciations pour les Command

---

htdocs/pages/administration/forum_planning.php

>  2025-02-19T20:44:44.733Z request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: mktime() expects parameter 1 to be int, string given" at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/htdocs/pages/administration/forum_planning.php line 105 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: mktime() expects parameter 1 to be int, string given at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/htdocs/pages/administration/forum_planning.php:105)"} []
Suite à cette erreur, on corrige le typage pour `mktime()`

Correction du typage pour mktime

---

composer.json
composer.lock
tests/behat/bootstrap/FeatureContext.php

On optimise le reset de la base de données pour les tests fonctionnels.
Sur une idée originale d'Adrien, au premier reset un fait un dump pour s'économiser l'éxécution de toutes les migrations + l'insertion des fixtures.
Ce dump contient une clé md5 basé sur l'ensemble des migrations + fixtures.
On est passé de  6m 28s à 5m 2s  sur le temps du job de test dans la CI.

Optimisation du temps des tests fonctionnels

---

db/migrations/20250218154548_update_tables_engine_to_inno_db.php
db/migrations/20250218154608_update_tables_encoding.php
docker/dockerfiles/mysql/my.cnf
docker/dockerfiles/mysqltest/my.cnf
sources/Afup/Bootstrap/Http.php
sources/Afup/Forum/Inscriptions.php
sources/Afup/Utils/Logs.php

On a souvent des erreurs dans les logs à cause de tables qui n'acceptent pas les emojis.
Au lieu de faire la chasse aux tables à chaque fois, ce commit met toute la base de données à jour en une seule fois.
On change aussi la valeur par défaut pour les futures colonnes et tables

Mise à jour de l'encoding des tables

---

app/Resources/views/event/calendar.html.twig
app/Resources/views/site/become_member.html.twig
app/Resources/views/site/home.html.twig
app/Resources/views/site/talks/show.html.twig
db/seeds/Session.php

1. On remonte la vidéo dans le code HTML pour indiquer que c'est une page de lecture de la vidéo et non une vidéo qui illustre un article.
On utilise aussi l'embed pour faciliter le crawl Google.
2. On désindexe les page de gestion de calendrier `{event}/calendar` qui n'ont aucun intérêt pour le référencement.

Optimisations pour la google search console video

---

Makefile
compose.yml
docker/bin/bash

Suppression du container `cliphp` qui ne sert à rien.
On utilise maintenant le container `apachephp` pour la console.

Simplification du docker compose

---

app/config/config_prod.yml

Ces erreurs peuvent être exclues depuis Symfony 4.1 et rendent la lecture des logs compliquée à cause des bots qui testent plein d'urls.
Blog : https://symfony.com/blog/new-in-symfony-4-1-ignore-specific-http-codes-from-logs
Doc : https://symfony.com/doc/current/logging/monolog_exclude_http_codes.html

Désactivation des logs des erreurs 404

---

app/config/services.yml

Les logos des entreprises, le listing des CR d'AG et certains badges (ceux uploadés dans l'admin) n'était plus affichés.
Logo des entreprises sur https://afup.org/profile/company
CR AG : https://afup.org/member/general-meeting
badges manquants sur https://afup.org/member/
Cela le kernel.project_dir renvoie vers le dossier app :
La valeur du paramètre en prod :
```
bas@b248cc15-f7fa-4b2c-ad51-9de51c661ae3 ~/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da $ php bin/console debug:container  --parameters | grep general_meetings_dir
app.general_meetings_dir                                  /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/app/htdocs/uploads/general_meetings_reports
```
Le dossier du paramètre n'existe pas :
```
bas@b248cc15-f7fa-4b2c-ad51-9de51c661ae3 …
```

correction chemins badges/logos entreprises/general meetings

---

Makefile
clevercloud/scripts/change_composer_version.sh
docker/dockerfiles/apachephp/Dockerfile

Maintenant que le projet est en PHP 7.4, il n'y a plus besoin d'installer une ancienne version de composer explicitement.
Et cela permet aussi de simplifier le dev, on peut directement utiliser la commande `composer` sans avoir à faire `php composer.phar`.

Installation de composer via Docker

---

sources/AppBundle/Association/Model/CompanyMember.php
sources/AppBundle/Controller/Website/StaticController.php
tests/behat/files/super_apero.csv

Correction pour prendre en compte les antennes avec une majuscule :
> Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Antenne introuvable via le code Montpellier")." at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/templates/site/superapero.html.twig line 53 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Antenne introuvable via le code Montpellier\"). at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/templates/site/superapero.html.twig:53, InvalidArgumentException(code: 0): Antenne introuvable via le code Montpellier at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/AppBundle/Antennes/AntennesCollection.php:62)"} [] …

Correction de quelques erreurs

---

app/config/routing/admin_event.yml
app/config/routing/admin_site.yml
htdocs/pages/administration/forum_sessions.php
htdocs/templates/administration/compta_devis.html
htdocs/templates/administration/compta_facture.html
htdocs/templates/administration/forum_facturation.html
htdocs/templates/administration/forum_inscriptions.html
htdocs/templates/administration/forum_sessions.html
htdocs/templates/administration/personnes_morales.html
htdocs/templates/administration/site_articles.html
htdocs/templates/administration/site_feuilles.html
sources/Afup/Bootstrap/_Common.php
sources/Afup/Utils/SymfonyKernel.php
sources/AppBundle/Controller/Admin/VoteController.php
sources/AppBundle/Controller/Event/TicketController.php
sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php
sources/AppBundle/Controller/Website/MemberShipController.php
sources/AppBundle/Event/JsonLd.php

Dernière MR avant la migration vers Symfony 5.4 :
- Correction plus propre de la récupération des `$_GET['sens']` Smarty
- Correction de la validation du CSRF token qui pose problème en 5.4
- Correction de la notice de PROD :
> 2025-03-04T10:00:32.278Z [Tue Mar 04 10:00:32.278279 2025] [proxy_fcgi:error] [pid 2443:tid 140045705004736] [client 91.208.207.215:50776] [185.31.151.110] AH01071: Got error 'PHP message: PHP Notice:  Constant AFUP_CHEMIN_RACINE already defined in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Bootstrap/_Common.php on line 31PHP message: PHP Notice:  Constant AFUP_PERSONNES_PHYSIQUES already defined in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Bootstrap/_Common.php on line 34PHP message: PHP Notice:  Constant …

Préparation pour mise à jour Symfony 5.4

---

htdocs/calendrier/js/controllers/PlanningCtrl.js

en allant sur https://afup.org/event/afupday2025lille/calendar
Le planning ne s'affiche pas et on a cette erreur : `TypeError: $http.get(...).success is not a function`.
On est en angular 1.8.3 :
```
cat node_modules/angular/package.json
{
"name": "angular",
"version": "1.8.3",
```
Et en fait même à priori dans le lock on était en 1.8.3 : https://github.com/afup/web/blob/f5c4ebf4d3e9a8b4aa7107be974c88d9f56d09f2/yarn.lock#L82
si on regarde dans un ancien dossier on était en 1.2.16.
On le confirme en local :
```
cat node_modules_old/angular/package.json
{
"name": "angular",
"version": "1.2.16",
```
Et sur l'ancienne prod :
```
afupsvr01:/home/sources/web/current$ cat node_modules/angular/package.json
{
"name": "angular",
"version": "1.2.16",
```
On adapte donc l'appel à la nouvelle version …

correction de l'affichage du planning personnalisé

---

sources/AppBundle/Offices/OfficeFinder.php

Nous avons actuellement une 500 lors de l'export du CSV des inscriptions.
Il y a cette erreur :
```
Uncaught PHP Exception TypeError: "Argument 3 passed to AppBundle\Offices\OfficeFinder::haversineGreatCircleDistance() must be of the type float, null given, called in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/AppBundle/Offices/OfficeFinder.php on line 128" at /home/bas/app_ee619ef6-05d2-4b4c...
```
Certaines antennes n'ont pas de ville, à juste titre : https://github.com/afup/web/blob/adc7b0935c4d27fd4d5d255bdd09dbc8576d030e/sources/AppBundle/Antennes/AntennesCollection.php#L453
Il faut donc prévoir le cas pour ne pas passer un null
Cela se voit maintenant qu'on a un plus fort typage (cf https://github.com/afup/web/commit/242883255f1ec651741fd0b25c4f1cfd9dcb0a6f#diff-3b3bea …

correction de l'export de l'inscription

---

composer.json
composer.lock

Suite à la mise à jour de Symfony 5.4 avec la MR https://github.com/afup/web/pull/1668, le déploiement a échoué.
Il manque la dépendance à `symfony/http-client`en PROD.

Ajout de la dépendance symfony/http-client

---

composer.json
composer.lock

Cette dépendance est utilisée notamment pour le téléchargement des pdf des AG et a été retirée suite à la mise à jour de Symfony en 5.4
ℹ️ Le package était déjà présent dans les dépendance de dev, mais on en a besoin dans les dépendances de base.

Ajout de la dépendance `symfony/mime`

---

app/config/config.yml

Dans les logs on avait ce genre d'erreur :
```
2025-03-23T22:28:19.003Z request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://preprod.afup.org/article15.php3"" at /home/bas/app_d6e663fe-4730-44e4-a2f4-b0b9e0e13060/vendor/symfony/http-kernel/EventListener/RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://preprod.afup.org/article15.php3\" at /home/bas/app_d6e663fe-4730-44e4-a2f4-b0b9e0e13060/vendor/symfony/http-kernel/EventListener/RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/article15.php3/\". at …
```

On évite de remonter dans les logs les erreurs 404

---

clevercloud/cron.json

Le serveur est en UTC donc il faut décaler.
Un jour il faudra revoir ça avec le scheduler de Symfony qui gère les timezones mais on ne peut pas encore l'utiliser (il faut SF 6.3 minimum).

Modification de l'heure de post auto

---

sources/AppBundle/Event/Form/EventType.php

Ce champ ne doit être coché que sur des anciens événéments. Il est là pour gérer l'historique et ne doit plus être coché. Afin d'éviter qu'il soit coché dans le futur on le désactive, ainsi il reste affiché à titre informatif.

on désactive le champ "Prix définis en incluant la TVA"

---

app/config/config.yml

Depuis le https://github.com/afup/web/pull/1674/files nous sommes passés de la version 1.4 à la version 2.4 du bundle EkinoNewRelicBundle.
Entre les deux versions la fonctionnalité de log de dépréciations a été ajoutée : https://github.com/ekino/EkinoNewRelicBundle/compare/1.4.0...2.4.0
Cela dans la version v2.0.0-beta1 (dans le changelog il est indiqué :
```
- Added a new `deprecations` parameter to logs `E_USER_DEPRECATED`.
```
)
Le nombre d'erreur a très nettement augmenté sur New Relic.
Cela est devenu moins exploitable.
Dans le cadre du mise à jour dans une prochaine majeure de Symfony mieux vaudra d'abord faire une première passe de correction des dépréciations en CI, puis activer le log de déprécations en prod quelques jours avant la mise en prod.
On désactive donc pour le moment …

on désactive l'envoi des depréciations dans la liste des erreurs sur new relic

---

app/config/services.yml
sources/AppBundle/Event/Model/Repository/PlanningRepository.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/VideoNotifier/Engine.php

Cette PR corrige deux soucis :
- certains talks ont une string vide au lieu de `null` comme id youtube
- le script n'excluait pas les talks programmés dans le futur (qui sont dispos avant un event via la publication des programmes)

Gestion des ID YouTube vides

---

app/AppKernel.php
app/config/services.yml
sources/AppBundle/DependencyInjection/TingRepositoryPass.php

Encore une grosse passe sur la config des services.
On ne peut pas encore modifier la visibilité par défaut, c'est plus simple d'attendre les prochaines versions de Symfony et PHP.
Il reste des choses à revoir mais ça fait déjà assez dans une seule PR !

Nettoyage de la config des services

---

sources/AppBundle/Event/Form/EventCompareSelectType.php
sources/AppBundle/Event/Form/EventSelectType.php
sources/AppBundle/Event/Form/Support/EventHelper.php
tests/unit/AppBundle/Event/Form/Support/EventHelperTest.php

J'ai repris l'idée du comparateur d'events mais pour tous les endroits où la liste est affichée.

Groupement des évènements par années

---

app/config/routing/admin_event.yml
db/migrations/20250412223717_add_archived_at_to_events.php
htdocs/pages/administration/forum_inscriptions.php
sources/Afup/Forum/Forum.php
sources/AppBundle/Controller/Admin/Event/ArchiveAction.php
sources/AppBundle/Controller/Admin/Event/RestoreAction.php
sources/AppBundle/Event/Form/EventSelectType.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
templates/admin/event/edit.html.twig
templates/admin/event/list.html.twig

Avec les années il commence à y avoir pas mal d'évènements dans la base de données.
Cela rend parfois la navigation compliquée dans les différents sous-menus de la section `Évènements` avec le sélecteur très long.
L'idée de ce commit est d'ajouter une notion d'archivage des évènements. C'est une simple colonne nullable en base avec la date d'archivage.
Quand cette date est présente, l'évènement n'est affiché que sur la page `Gestion évènements`.
Le bouton pour archiver :
L'affichage une fois archivé :
Dans la liste ça colore la ligne en jaune :
Et au survol on voit la date :

Archivage des évènements

---

sources/AppBundle/Controller/Admin/Event/RemoveEventAction.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
templates/admin/event/list.html.twig

La requête actuelle prend trop de temps à cause des jointures (environ 4 à 5 secondes).
En comptant les relations de façon séparée, le temps de chargement de la page passe de plusieurs secondes à environ 200ms.

Amélioration de la performance de la liste des events

---

sources/AppBundle/Event/Form/EventCFPTextType.php
templates/admin/event/form.html.twig

> Cette PR vient d'une demande d'Amélie, à l'édition d'un évènement certains textearea utilisent encore l'ancien wysiwyg (tinymce) qui est je cite "tout pourri" 😄
> 
> Avec ce patch on permet l'utilisation de l'éditeur plus récent (simplemde) sur tous les textearea de l'édition/création d'évènement.
> 
> C'est fait de façon à ne pas toucher aux évènements actuels, qui restent sur tinymce qui génère un mix de html et de markdown. On pourra bien sûr migrer les anciens évènement après ce patch si on veut un jour se débarrasser totalement de tinymce.
> 
> Et les nouveaux évènements sont configurés de façon à utiliser le nouvel éditeur à la création.
En fait c'est pas ça le soucis ni la solution, voir ce commentaire : https://github.com/afup/web/pull/1732#issuecomment-2810836854

Utilisation de l'éditeur plus récent sur les events

---

templates/admin/base_with_header.html.twig

Demande d'Amélie qui galère sur la page des "venue speakers".
Quand la fenêtre est trop petite, la table a trop d'éléments et ne peut plus se compresser, ce qui masque les colonnes de droite, et la page n'est pas scrollable.
Le scroll ne s'active que si la fenêtre est petite, sinon ça reste l'ancien comportement.

Activation du scroll horizontal quand la fenêtre est trop petite

---

sources/AppBundle/Mailchimp/Mailchimp.php

En tendant de planifier la veille il y a eut une erreur 500.
En regardant les logs il y a eut cette erreur :
```
Exception 'TypeError' with message 'Argument 1 passed to AppBundle\Mailchimp\Mailchimp::scheduleCampaign() must be of the type int, string given, called in /home/bas/app_<GUID>/sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php on line 192' in /home/bas/app_<GUID>/sources/AppBundle/Mailchimp/Mailchimp.php:133
```
L'id est une chaine et non un int, on modifie la signature de la méthode pour que cela fonctionne la fois suivante.

correction de la planification de campagne pour les veille

---

sources/AppBundle/Event/Form/EventType.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
templates/admin/event/form.html.twig

Depuis la migration sous symfony de cette page la date de fin de saisie des tokens sponsors n'était plus présente sur la création/modification d'un événement. On l'affiche/permet de la modifier à nouveau.

retour de la date de fin de saisie des tokens sponsor

---

htdocs/pages/administration/forum_inscriptions.php
htdocs/pages/administration/forum_planning.php
htdocs/pages/administration/forum_sessions.php

Sur certaines pages de la partie "evenements" de l'admin (inscriptions, planning, conférences), si on ajoutait/modifiait une valeur depuis un événement qui n'était pas l'événement par défaut on retournait tout de même à l'événement par défaut. On corrige cela en retournant sur la liste d'origine après ajout/modification.

on revient sur la page du bon évenement

---

sources/AppBundle/Association/Model/CompanyMember.php
sources/AppBundle/Association/Model/Repository/CompanyMemberRepository.php
sources/AppBundle/Controller/Website/MemberShipController.php
tests/behat/bootstrap/FeatureContext.php
tests/unit/AppBundle/Association/Model/CompanyMemberTest.php

Quelques corrections pour préparer le passage à PHP 8.2 :
- le montant de la cotisation pour une personne morale
- correction du contexte behat lié aux emails.

Quelques corrections

---

sources/AppBundle/Event/Model/GithubUser.php

Il y a une erreur quand on veut éditer un speaker dans le BO :
```
Argument 1 passed to AppBundle\Event\Model\GithubUser::setName() must be of the type string, null given
```

Le `$name` d'un utilisateur GitHub est nullable en base

---

sources/Afup/Association/Cotisations.php
sources/AppBundle/Controller/Website/MemberShipController.php

Suite à cette erreur en PROD :
> in Assert\Assertion::createException called at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/vendor/beberlei/assert/lib/Assert/Assertion.php (680)
> in Assert\Assertion::notNull called at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/Afup/Association/Cotisations.php (207)
> in Afup\Site\Association\Cotisations::notifierRegelementEnLigneAuTresorier called at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/AppBundle/Controller/Website/MemberShipController.php (407)
> in AppBundle\Controller\Website\MemberShipController::payboxCallback called at /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/vendor/symfony/http-kernel/HttpKernel.php (163)
> in Symfony\Component\HttpKernel\HttpKernel::handleRaw called at …

Corrige la notification au trésorier

---

sources/AppBundle/Event/Model/Event.php

On est maintenant en full Hors Taxes donc plus besoin d'avoir de nouveaux évènements avec tarifs hybrides.

Création des évènements avec tarifs HT par défaut

---

templates/admin/base_with_header.html.twig

Pour améliorer l'affichage des pages sur les petits écrans.
Je n'ai réduis que de 10 pixels. Si on réduit plus ça créé des sauts de ligne sur certains menus.

Réduction de la largeur du menu de l'admin

---

composer.json
composer.lock
sources/AppBundle/SocialNetwork/Bluesky/BlueskyTransport.php
sources/AppBundle/SocialNetwork/SocialNetwork.php
sources/AppBundle/VideoNotifier/Engine.php
sources/AppBundle/VideoNotifier/StatusGenerator.php
tests/unit/AppBundle/SocialNetwork/SocialNetworkTest.php
tests/unit/AppBundle/VideoNotifier/StatusGeneratorTest.php

Cela permet aussi de retirer la dépendance à `myclabs/php-enum`.

Migration de l'enum `SocialNetwork` en natif

---

app/config/services.yml
sources/AppBundle/Twig/AssetsExtension.php
sources/AppBundle/Twig/OfficesExtension.php
sources/AppBundle/Twig/TwigExtension.php

Avec l'arrivée des attributs de PHP 8 et de Symfony qui avance on peut commencer à vider encore plus la config des services.
Les extensions Twig sont détectés automatiquement à la compilation du container donc plus besoin de les tag à la main.

Modernisation des extensions Twig

---

sources/AppBundle/Event/Model/Repository/EventRepository.php
sources/AppBundle/Ting/DateTimeWithTImeZoneSerializer.php
sources/AppBundle/Ting/DateTimeWithTimeZoneSerializer.php

Depuis qu'on est passé par les objets ting pour gérer les events dans l'admin nous avons un souci sur la gestion des heures.
Lors de la récupération de l'heure, celle-ci est décalée de 2 heures, et lors de l'enregistrement on enregistre cette version décalée, à chaque enregistre on a le décalage qui s'applique.
Cela car on stocke la date/heure en timestamp sur certains champs (c'est historique et à long terme l'idée est de changer cela mais on ne va pas changer cela à court terme), que le timestamp est converti en datetime par Ting et cela dans gérer le fuseau horaire.
Afin de corriger cela on crée un nouveau type de serialiser qu'on applique aux champs en timestamp qui va avoir une option pour setter la timezone, ainsi la date enregistrée est bien la date affichée.

correction de la gestion des dates dans l'admin des événements

---

templates/event/cfp/propose.html.twig

Correction du test d'ouverture du CFP.
On comparait :
```
"May 9, 2025 08:59"
```
à
```
DateTime @1749444842 {#752 ▼
date: 2025-06-09 04:54:02.0 +00:00
}
```
Forcément ça marchait beaucoup moins bien ;-)
On s'appuie maintenant sur `event.isCfpOpen()` (qui est testé unitairement) pour afficher le message de non ouverture.
Dans le cas de la fin du CFP, il y a une redirection faite depuis le controller donc on n'arrivera pas ici.

Correction du blocage de l'ouverture du CFP

---

sources/AppBundle/Event/Model/Repository/EventRepository.php

On applique la correction de la timezone #1775 sur le nouveau champ de date d'ouverture du CFP.

Correction pour la date d'ouverture du CFP

---

sources/AppBundle/TechLetter/MailchimpSynchronizer.php

L'éxécution de la synchronisation avec Mailchimp plante tout les jours avec cette erreur : 
```
2025-05-09T23:00:09.202Z (bas) CMDOUT (01:00:09 INFO      [app] Unsubscribe  to techletter ["address" => null])
2025-05-09T23:00:09.204Z console.CRITICAL: Error thrown while running command "--env=prod sync-techletter -vv". Message: "AppBundle\Mailchimp\Mailchimp::unSubscribeAddress(): Argument #2 ($email) must be of type string, null given, called in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/AppBundle/TechLetter/MailchimpSynchronizer.php on line 45" {"exception":"[object] (TypeError(code: 0): AppBundle\\Mailchimp\\Mailchimp::unSubscribeAddress(): Argument #2 ($email) must be of type string, null given, called in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/AppBund …
```

Correction d'une erreur de type du synchronizer mailchimp

---

composer.json
composer.lock
rector.php
tests/support/IntegrationTestCase.php
tests/unit/Afup/Association/CotisationsTest.php
tests/unit/Afup/Utils/UtilsTest.php
tests/unit/AppBundle/Association/MembershipFeeReferenceGeneratorTest.php
tests/unit/AppBundle/Association/Model/CompanyMemberTest.php
tests/unit/AppBundle/Compta/Importer/AutoQualifierTest.php
tests/unit/AppBundle/Event/Form/Support/EventHelperTest.php
tests/unit/AppBundle/Event/Model/EventTest.php
tests/unit/AppBundle/Event/Model/SpeakerTest.php
tests/unit/AppBundle/Indexation/Meetups/MeetupClientTest.php
tests/unit/AppBundle/Payment/PayboxTest.php
tests/unit/AppBundle/SocialNetwork/SocialNetworkTest.php
tests/unit/AppBundle/Subtitles/ParserTest.php
tests/unit/AppBundle/TechLetter/Model/TechLetterFactoryTest.php
tests/unit/AppBundle/TestCase.php
tests/unit/AppBundle/VideoNotifier/StatusGeneratorTest.php

- les data providers doivent être statiques
- les clefs des tableaux doivent correspondre aux arguments des tests
- les annotations sont remplacées par des attributs
On ne peut pas encore passer à la v12 car il faut être en PHP 8.3

Mise à jour de PHPUnit en version 11

---

app/config/config.yml
app/config/routing/admin.yml
app/config/routing/admin_event.yml
app/config/security.yml
htdocs/pages/administration/forum_facturation.php
htdocs/pages/administration/forum_inscriptions.php
htdocs/pages/administration/forum_planning.php
htdocs/pages/administration/forum_sessions.php
sources/Afup/fonctions.php
sources/AppBundle/Controller/Admin/Event/AdminActionWithEventSelector.php
sources/AppBundle/Controller/Admin/Event/PendingBankwiresAction.php
sources/AppBundle/Controller/Admin/Event/PricesAddAction.php
sources/AppBundle/Controller/Admin/Event/PricesEditAction.php
sources/AppBundle/Controller/Admin/Event/RedirectEventFromSessionListener.php
sources/AppBundle/Controller/Admin/Event/RoomAction.php
sources/AppBundle/Controller/Admin/Event/SpeakersExpensesAction.php
sources/AppBundle/Controller/Admin/Event/SpeakersManagementAction.php
sources/AppBundle/Controller/Admin/Event/SpecialPriceAction.php
sources/AppBundle/Controller/Admin/Event/SponsorTicketAction.php
sources/AppBundle/Controller/Admin/Event/VotesListeAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerListAction.php
sources/AppBundle/Controller/Admin/VoteController.php
sources/AppBundle/Event/Form/Support/EventSelectFactory.php
templates/admin/speaker/list.html.twig
tests/behat/features/Admin/Events/VoteVisiteur.feature

Stockage de la sélection d'un évènement en session, avec redirection si l'id est présent en session mais manquant dans l'url.
Le système est à moitié géré dans les anciennes pages : le sélecteur n'écrit pas dans la session mais va juste y lire un éventuel id.
Clôture de #1782 et #1716

Stockage de l'évènement sélectionné en session

---

sources/AppBundle/Mailchimp/Mailchimp.php
sources/AppBundle/TechLetter/MailchimpSynchronizer.php

Suite aux erreurs en prod lié à la tâche de synchronisation des emails avec Mailchimp : 
>  2025-05-11T23:00:06.236Z (bas) CMDOUT (PHP Warning:  Attempt to read property "email_address" on array in /home/bas/app_ee619ef6-05d2-4b4c-978f-d8f85e5a49da/sources/AppBundle/Mailchimp/Mailchimp.php on line 78)
On corrige le synchronizer Mailchimp + ajout de typehint.

Fix synchonizer Mailchimp

---

sources/AppBundle/Event/Form/TalkType.php

Actuellement la page du CFP indique le label concernant les ateliers comme texte d'aide pour le forward du profil vers les antennes, cette pr corrige ce point.
Version [en prod actuellement](https://afup.org/event/forumphp2025/cfp/propose):

Correction du message utilisé comme sous-texte pour le forward vers les antennes

---

.git-blame-ignore-revs

Suite au merge de la PR #1796 le hash du commit a changé malgré le fait d'avoir rebase la branche sur master au moment du merge 🤷

Mise à jour du hash du commit à ignorer suite au merge

---

app/config/config.yml
templates/admin/base_with_header.html.twig
templates/admin/menu.html.twig
tests/behat/features/Admin/Events/GestionEvenements.feature
tests/behat/features/Admin/Events/Inscriptions.feature
tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeeting.feature
tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingQuestions.feature
tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingReports.feature
tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingVotes.feature

Petite réorg du menu pour en réduire encore la largeur (ça aide sur le laptop d'Amélie).
- Les menus AG ne sont utilisés qu'une fois par an
- La partie "Antennes AFUP" pointe sur d'anciennes pages inexistantes
- Aucune page n'utilise l'option `nouvelle_fenetre`
- Le menu "Gestion évènements" peut également être renommé en "Liste" grâce à l'ajout d'un id sur chaque menu (qui peut être ciblé en Behat).
| Avant                                                                                     | Après                                                                                     | 
| ---                                                                                       | ---                                                                                       | 
| …

Réorg du menu

---

app/config/routing/event.yml
sources/AppBundle/Controller/Event/VoteController.php

Il avait été déplacé par erreur dans le namespace de l'admin.
Les votes sur le CFP en cours sont bloqués à cause de ça.

Correction de l'emplacement du controller des votes

---

.env.dist
app/config/config.php
app/config/config.yml
templates/base.html.twig

Cela permet d'éviter de hardcoder cette valeur et utiliser la valeur déjà présente dans l'addon de config sur clever cloud et de centraliser la configuration.

utilisation de la variable d'environnement AFUP_GLOBAL_MENU_EVENT_LABEL

---

sources/AppBundle/Association/Model/Repository/CompanyMemberInvitationRepository.php
sources/AppBundle/Association/Model/Repository/GeneralMeetingQuestionRepository.php
sources/AppBundle/Association/Model/Repository/GeneralMeetingResponseRepository.php
sources/AppBundle/Association/Model/Repository/GeneralMeetingVoteRepository.php
sources/AppBundle/Association/Model/Repository/SubscriptionReminderLogRepository.php
sources/AppBundle/Association/Model/Repository/SubscriptionRepository.php
sources/AppBundle/Association/Model/Repository/TechletterSubscriptionsRepository.php
sources/AppBundle/Association/Model/Repository/TechletterUnsubscriptionsRepository.php
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/Event/Model/Repository/BadgeRepository.php
sources/AppBundle/Event/Model/Repository/EventCouponRepository.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
sources/AppBundle/Event/Model/Repository/GithubUserRepository.php
sources/AppBundle/Event/Model/Repository/InvoiceRepository.php
sources/AppBundle/Event/Model/Repository/RoomRepository.php
sources/AppBundle/Event/Model/Repository/SpeakerSuggestionRepository.php
sources/AppBundle/Event/Model/Repository/SponsorScanRepository.php
sources/AppBundle/Event/Model/Repository/SponsorTicketRepository.php
sources/AppBundle/Event/Model/Repository/TalkInvitationRepository.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Repository/TalkToSpeakersRepository.php
sources/AppBundle/Event/Model/Repository/TicketEventTypeRepository.php
sources/AppBundle/Event/Model/Repository/TicketSpecialPriceRepository.php
sources/AppBundle/Event/Model/Repository/TicketTypeRepository.php
sources/AppBundle/Event/Model/Repository/UserBadgeRepository.php
sources/AppBundle/Event/Model/Repository/VoteRepository.php
sources/AppBundle/Security/ActionThrottling/LogRepository.php
sources/AppBundle/Site/Model/Repository/ArticleRepository.php
sources/AppBundle/Site/Model/Repository/RubriqueRepository.php
sources/AppBundle/TechLetter/Model/Repository/SendingRepository.php

La classe `Repository` est generic et le type concret n'est pas spécifié dans la majorité des repositories.
L'ajouter va permettre de simplifier et de mieux typer pas mal de code les utilisant.

Ajout du model du template generic des repositories

---

rector.php

L'outil se base maintenant sur les versions composer de certaines dépendances pour appliquer les bonnes règles de migration.

Nettoyage de la config Rector

---

.github/workflows/ci.yml
Makefile
composer.json
composer.lock
phpstan.neon

Maintenant qu'on est dans une version récente de PHP, plus besoin d'utiliser l'image Docker de PHPStan on peut l'avoir directement dans le projet.
Cela permet plusieurs choses :
- installer facilement des extensions
- mieux maitriser la version de l'outil
- avoir l'output en couleur

Installation de PHPStan en dépendance de dev

---

composer.json
composer.lock

On met à jour `presta/sitemap-bundle` en version 4 pour la préparation de la montée de version en Symfony 7.3

Mise à jour de presta/sitemap-bundle

---

htdocs/css/tickets-2025.css
templates/event/ticket/ticket.html.twig

Hello,
2 petits bugs repérés lors de la mise en prod:
- La gestion de la mise en avant des tickets ne tenait pas compte des tickets non commandable (i.e: plus de stock en late bird ou réservé aux membres pour un user non connecté)
- L'affichage de cette mise en avant était incorrect
**Rendu actuel**
**Après PR:**

Correction gestion de la mise en avant tickets soutien

---

phpstan.neon
sources/AppBundle/StaticAnalysis/Rule/NoDebugFunctionsRule.php
tests/stubs/phpstan/debug-functions.php
tests/unit/AppBundle/StaticAnalysis/Rule/NoDebugFunctionsRuleTest.php

Cela permet de détecter les oublis dans les PRs.

Ajout d'une règle PHPStan pour les fonctions de debug

---

Makefile

Quand on lance le projet, on "perd" sa console, on est obligé d'ajouter un var d'env pour être en detach.
J'ai passé de base en detach, ça me parait plus dans l'air du temps :)
Pour pouvoir voir les logs docker compose, j'ai ajouté un  `make logs`.

DX - Launch docker compose with --detach

---

sources/AppBundle/Controller/Event/Event/IndexAction.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

sur https://cfp.afup.org on redirige vers https://afup.org/event/ cette page liste tous les événements à venir, sans prendre en compte la date d'ouverture du CFP. on peux donc avant la keynote de cloture afficher les AFUP Days retenus. Pour éviter ça on ajoute un filtre sur la liste des événements sur la date d'ouverture du CFP (le changement a été appliqué en prod pour éviter de faire fuiter l'info (certaines personnes sont déjà tombées sur cette page et l'on remonté), mais sera perdu lors du prochain déploiement)

correction page liste events
