htdocs/templates/phptourluxembourg2015/entete.html

juste une modifs dans les headers
les pages sont actuellement visibles en prod mais sans liens

ouverture des liens conferenciers et sessions

---

sources/Afup/AFUP_Site.php

Devrait fixer #82 
Je suis en train de rajouter les ALTs dans la BDD 
http://afup.org/pages/administration/index.php?page=site_feuilles&action=lister
Champs à modifier : description

Alt sur images plutôt que sur les liens

---

htdocs/pages/phptourluxembourg2015/inscription-en.php
htdocs/pages/phptourluxembourg2015/inscription.php
htdocs/templates/phptourluxembourg2015/inscription-en.html
htdocs/templates/phptourluxembourg2015/inscription.html

Ajoute la page d'inscription en anglais. 
@mteneur , @jacquesbh : Je n'ai pas eu la possibilité de tester (pas moyen de faire fonctionner correctement la vagrant hier soir).

Ajoute la page d'inscription en anglais. 

---

htdocs/templates/administration/connexion.html
htdocs/templates/administration/mot_de_passe_perdu.html
htdocs/templates/administration/style.css

Fix login admin page (with mobile)

---

htdocs/pages/administration/forum_sessions.php
htdocs/pages/forumphp2015/appel-a-conferenciers-en.php
htdocs/pages/forumphp2015/appel-a-conferenciers.php
provisionning/chef/cookbooks/afup/recipes/default.rb

Choix de conférence de 20 min dans formulaire d'ajout de session

---

htdocs/pages/forumphp2015/inscription.php
htdocs/templates/forumphp2015/inscription.html

* Le paramètre ?nolayout permet de générer une page sans en-tête ni pied de page
* On définie l'action par un paramètre GET

Forum : intégration du formulaire pourle blog

---

htdocs/pages/forumphp2015/appel-a-conferenciers.php

Suppression echo lors de la soumission d'une conf au CFP du forumPHP 2015

Suppression echo lors de la soumission d'une conf au CFP du forumPHP 2015

---

htdocs/pages/forumphp2015/paybox_effectue.php

ping @mikaelkael @mikaelrandy 
Is that ok for you? It's a copy/paste (not dummy one) of the PHP Tour 2015 :heart_eyes:

Send invoice and registration confirmation emails on Forum 2015

---

htdocs/pages/forumphp2015/index.php
htdocs/pages/forumphp2015/inscription.php
htdocs/pages/forumphp2015/sessions.php
htdocs/templates/forumphp2015/sessions.html
translations/inscription.en.xlf

* Corrections de traductions
* Corrections de redirections
* Correction page sessions

Corrections intégration blog // event.afup.org

---

dependencies/paybox/payboxv2.inc
htdocs/pages/forumphp2015/inscription.php
htdocs/pages/forumphp2015/paybox_retour.php

"Paybox : retour serveur à serveur""

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.html
sources/Afup/AFUP_Compta.php

Hi guys @mikaelkael @paxal @mikaelrandy 
I need a very quick review please. It works perfectly fine on my machine.
If nobody reviews it before 18:30, I'll merge :+1: 
Thanks!

[+FEATURE] Show selects in table in order to improve utilization

---

configs/application/pages.php
htdocs/pages/administration/compta_recherche.php
htdocs/templates/administration/compta_recherche.html
sources/Afup/AFUP_Compta.php
sources/Afup/fonctions.php

For accounting purpose only.
Result preview:
It searchs in:
* Devis / Factures
* Cotisations (personnes physiques & morales)
* Inscriptions Forum
* Factures Forum
ping @paxal @mikaelkael 
I'll merge this PR if it's not reviewed before 10:15 pm. I really need it :) Thanks.

Global search

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.html

I used a popup… :sweat_smile:
It's a simple "tool" which allows me to just click on link and get transactions of the day. Really really helpful.
ping @mikaelkael @paxal Need review on this :) (quick)
Thanks!

Add direct link to paybox transactions

---

provisionning/chef/cookbooks/afup/recipes/default.rb

see https://github.com/afup/web/search?utf8=%E2%9C%93&q=mcrypt

Add missing php5-mcrypt dependency in provisioning

---

htdocs/templates/administration/compta_journal.html
htdocs/templates/administration/style.css

Some improvements on accounting logs
ping @paxal @xavierleune

Improve accounting logs

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.html
sources/Afup/AFUP_Compta.php
sql/20160105_alter_compta.sql

The best example is a GIF, isn't it?
Next PR will be to export this data. But for now, it works like I want it.
ping @paxal @xavierleune

Add comment in journal

---

htdocs/templates/administration/compta_recherche.html
sources/Afup/AFUP_Compta.php

Add total, refs & details in invoice line in search results

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.html

The file is formatted like this: (using `fr_FR.utf8` locale)
```csv
Date;Compte;Evénement;Catégorie;Description;Débit;Crédit;Règlement;Commentaire
2015-01-01;Caisse;Gestion;Administratif;;;13,37;"Solde banque";"test commentaire"
2015-01-01;Paypal;Gestion;Administratif;;;13,37;"Solde banque";
2015-01-01;"Compte courant";Gestion;Administratif;;;42,00;"Solde banque";"yeah"
2015-01-01;"Livret A";Gestion;Administratif;;;"1 337,42";"Solde banque";
```

Export "journal" as CSV

---

htdocs/pages/administration/compta_banque.php
sources/Afup/AFUP_Compta.php

ping @afup/outils 
It adds the column `Commentaire` in the .xlsx exported using "Banque" page.

Add comment in XLSX export

---

Vagrantfile
provisionning/chef/cookbooks/afup/files/default/dotdeb.list
provisionning/chef/cookbooks/afup/files/default/mariadb.list
provisionning/chef/cookbooks/afup/recipes/default.rb
provisionning/chef/cookbooks/afup/templates/default/virtualhost.erb

ping @afup/outils 
(of course the provisioning works perfectly ;))

Update box to debian 8.2 "jessie" & remove mailcatcher

---

htdocs/pages/administration/compta_banque.php
htdocs/templates/administration/compta_banque.html

A "simple" link to download a zipball with all the attachments of the `compta` sorted by month.
This PR is based on #154. So please review and merge it before this one.

Download all attachments

---

doc/import-scans.md
htdocs/pages/administration/forum_inscriptions.php
htdocs/templates/administration/forum_inscriptions.html
sql/20160114_precense-flag-event.sql

Event presence flag

---

htdocs/templates/administration/compta_recherche.html

Add payment information in search results on invoices

---

htdocs/pages/administration/compta_banque.php
sources/Afup/AFUP_Compta.php

Update columns in excel to get information about attachment

---

htdocs/pages/administration/compta_journal.php
sources/Afup/AFUP_Compta.php

Add comment field in compta edition form

---

configs/application/pages.php
htdocs/pages/administration/membre_personne_morale.php
htdocs/templates/administration/membre_personne_morale.html

Amélioration de l'expérience membre.

Les membres d'une personne morale peuvent éditer sa fiche

---

htdocs/pages/administration/forum_conferenciers.php

FIX #174 ne pas ajouter les projets aux conférenciers

---

Vagrantfile

Deploy: correction for Ubuntu 16.04(see #189)

---

provisionning/chef/cookbooks/afup/recipes/default.rb

Perhaps, can be improved. At least, it runs

Deploy: composer is missing using vagrant

---

htdocs/templates/forumphp2016/inscription.html

Ces fichiers ne sont plus utiles & de toute manière n'ont pas été repris lors de la création du répertoire forumphp2016

Correction inclusion fichiers absents

---

htdocs/templates/forumphp2016/js/inscription.js

Related to : https://twitter.com/talus_/status/785514705527926784

Fix: calcul js de l'inscription

---

Vagrantfile
provisionning/chef/cookbooks/afup/recipes/default.rb

En attendant une refonte + globale du provisionning, ça fait l'affaire :)

Correction provisionning

---

htdocs/pages/forumphp2016/inscription.php

On ne propose à la vente que des pass jour 2

---

Vagrantfile
htdocs/tmp/twig/3c/3caa323df5d20ec1c99b74c07965f9f5a722db6572a2d445df1368e6069e82c6.php

As boxcutter/debian85 box seems to be unavailable, use existing boxcutter/debian8 instead

Update vagrant base box to existing one

---

sources/AppBundle/Model/Repository/EventRepository.php

En local j'étais en datetime mais la prod semble être en timestamp.

Les dates sont en int en prod

---

.gitignore
htdocs/pages/administration/connexion.php
htdocs/pages/administration/forum_badge.php
htdocs/pages/administration/forum_badge_programme.php
htdocs/pages/administration/index.php
htdocs/templates/administration/connexion.html
sources/Afup/Droits.php

close #206
Affiche un message d'erreur adapté en fonction de l'erreur de login
Contient un refacto de la classe de gestion des droits

Gestion des différents cas d'erreur de login

---

app/Resources/views/event/home.html.twig
app/config/services.yml
composer.json
composer.lock
htdocs/css/vote.css

Affichage date de fin du CFP sur la home

---

htdocs/templates/administration/forum_sessions.html
sources/Afup/Forum/AppelConferencier.php

Meilleur affichage des votes dans le BO

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/home.html.twig
htdocs/css/vote.css
sources/AppBundle/Controller/EventController.php
sources/AppBundle/Model/Repository/TalkRepository.php
sources/AppBundle/Model/Repository/VoteRepository.php

Sur la capture il n'y a que peu de votes & soumissions, mais en réalité on affiche pas une stat si celle-ci est inférieure à 30

Home du cfp: affichage de stats sur votes & soumissions

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/cfp/edit.html.twig
app/Resources/views/event/star.html.twig
app/Resources/views/event/vote/liste.html.twig
app/Resources/views/event/vote/talk.html.twig
htdocs/css/vote.css
sources/AppBundle/Controller/CFPController.php

Affichage des votes & commentaires sur le formulaire d'édition d'un sujet

---

htdocs/pages/administration/membre_assemblee_generale.php
sources/Afup/Association/Assemblee_Generale.php

niveau injection/préparation de la requête, ce n'est pas la folie, mais ça s’inscrit dans la lignée de l'existant.

on évite qu'un membre puisses donner son pouvoir à lui-même

---

htdocs/pages/administration/assemblee_generale.php
sources/Afup/Association/Assemblee_Generale.php

Convocation AG: Mailchimp & Wysiwyg

---

htdocs/pages/administration/forum_sessions.php
sources/AppBundle/Event/Form/TalkType.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php
sql/2016-12-07-needsMentoring.sql

ajout checkbox accompagnement des jeunes speakers

---

app/AppKernel.php
app/config/services.yml
composer.json
composer.lock
sources/AppBundle/Controller/CFPController.php
sources/AppBundle/Controller/VoteController.php
sources/AppBundle/Notifier/SlackNotifier.php
sources/AppBundle/Slack/Attachment.php
sources/AppBundle/Slack/Field.php
sources/AppBundle/Slack/Message.php
sources/AppBundle/Slack/MessageFactory.php

Envoi de notifications slack lors de l'ajout de talk ou de vote

---

htdocs/robots/planete/explorateur.php

Correction exploration planete

---

htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php
sql/2016-12-17-sessionInfos.sql

On permet de stocker :
- l'id de la vidéo youtube
- l'url vers les slides
- l'url vers une version écrite de la conf
Une prochaine PR viendra avec l'affichage de ces infos.

ajout d'infos sur les talks

---

.atoum.php
.gitignore
app/Resources/views/base.html.twig
app/Resources/views/site/talks/list.html.twig
app/config/parameters.yml.dist
app/config/routing.yml
app/config/routing/talks.yml
app/config/services.yml
composer.json
composer.lock
htdocs/.htaccess
htdocs/css/talk/list.css
htdocs/js/talk/list.js
sources/AppBundle/Command/IndexTalksCommand.php
sources/AppBundle/Controller/TalksController.php
sources/AppBundle/Event/Model/Planning.php
sources/AppBundle/Event/Model/Repository/PlanningRepository.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Speaker.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Indexation/Talks/Runner.php
sources/AppBundle/Indexation/Talks/Transformer.php
tests/units/AppBundle/Event/Model/Talk/Talk.php
tests/units/AppBundle/Indexation/Talks/Transformer.php

branche partant de la PR #271
Ajout d'une page permettant de chercher dans les conférences.
Il est possible de rechercher via libellé/nom des speakers, et de filtrer sur les confs ayant des vidéos/slides associés.
Pour chaque conférence, on affiche, si ils sont présents, les liens vers : la vidéo sur youtube, les slides, la page sur joind.in ou un article de blog du speaker.

Ajout d'une page listant les conférences

---

htdocs/css/talk/list.css
htdocs/js/talk/list.js

amélioration de l'affichage de la pagination

---

app/Resources/views/site/talks/show.html.twig
sources/AppBundle/Event/Model/Talk.php

* intégration cartes twitter
* ajout du nom de la conf/event sur le titre

ajout de balises meta sur la page talks

---

htdocs/css/talk/list.css
htdocs/js/talk/list.js

ajout d'un lien permettant de voir l'ensemble des confs dans la liste des facettes

---

app/Resources/views/site/talks/list.html.twig
htdocs/js/talk/list.js
htdocs/pages/administration/forum_sessions.php
sources/AppBundle/Controller/TalksController.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Indexation/Talks/Runner.php
sources/AppBundle/Indexation/Talks/Transformer.php
tests/units/AppBundle/Indexation/Talks/Transformer.php

Ajout du format sur la page historique des confs

---

app/Resources/views/event/base.html.twig
app/Resources/views/event/vote/talk.html.twig
htdocs/css/vote.css

Je me suis basé sur typebase.css pour améliorer un peu la lisibilité des propositions sur la page Vote. Il y a encore quelques modifs a faire je pense, mais c'est un bon début, qu'est-ce que vous en pensez ?
Avant/Apres :

Lisibilité du CFP

---

sources/Afup/Association/Cotisations.php

Add `COTIS-` as prefix for subscription invoices

---

app/Resources/views/site/talks/show.html.twig
htdocs/css/grid.css

on donne plus de place à la vidéo sur le détail d'un talk

---

app/Resources/views/site/talks/list.html.twig
htdocs/js/talk/list.js

Le lien n'est affiché que si il y a au moins un filtre.

ajout d'un lien pour supprimer les filtres

---

htdocs/templates/administration/forum_sessions.html
htdocs/templates/administration/style.css

on ajoute des icones pour indiquer :
* si le speaker a demandé de l'accompagnement
* si je joindin est renseigné
* si une vidéo est indiquée
* si il a des slides
* si il a un lien vers un transcript

ajout d'indicateurs sur la liste des sessions

---

htdocs/pages/administration/assemblee_generale.php
htdocs/templates/administration/assemblee_generale.html
sources/Afup/Association/Assemblee_Generale.php

Précédemment on affichait juste le nombre de présences et pouvoirs.
Maintenant on affiche aussi juste le nombre de présences.

affichage du nombre de présences sur le BO

---

app/Resources/views/site/superapero.html.twig

ajout de poitiers sur la carte des super apéros

---

app/Resources/views/site/superapero.html.twig

ajout reims dans la liste des villes particpantes au superapero

---

htdocs/pages/administration/forum_sessions.php
htdocs/templates/administration/forum_sessions.html
sources/Afup/Forum/AppelConferencier.php

ajout d'un filtre pour ne lister que les sessions dont le speaker a demandé un accompagnement

---

app/Resources/views/site/superapero_live.html.twig
app/config/routing/site.yml
sources/AppBundle/Controller/StaticController.php

ajout d'une page pour suivre les live des SuperAperoPHP

---

htdocs/templates/administration/accueil.html

Fix a typo

---

app/Resources/views/blog/program.html.twig
app/config/routing.yml
app/config/routing/blog.yml
app/config/security.yml
composer.lock
htdocs/.htaccess
sources/AppBundle/Controller/BlogController.php
sources/AppBundle/Event/Model/JoinHydrator.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

Le JoinHydrator est un premier jet, je l'améliorerai et proposerai de le merger dans Ting directement, il facilite la manipulation des données issues de Left Join en tirant parti des générateurs.
Certaines urls sont en dur ==> il s'agit d'url qu'on retrouve sur le blog et non pas côté applicatif web. On ne peut pas les construire avec le routeur.

Le programme est desormais dispo pour le blog via sf

---

app/Resources/views/blog/speakers.html.twig
app/config/routing/blog.yml
sources/AppBundle/Controller/BlogController.php
sources/AppBundle/Event/Model/Repository/SpeakerRepository.php

@agallou j'ai besoin de la passer maintenant mais je veux bien que tu jette un oeil après coup quand même :)

Page speakers pour le blog

---

app/Resources/views/blog/program.html.twig

Je la met également sur le titre car je fais mes tests sur le forum 2016 et on avait des caractères genre :taco: dans les titres :)

Mise en forme HTML depuis le BO sur les talks

---

app/Resources/views/blog/speakers.html.twig

utilisation des widgets twitter pour les boutons de suivi des speakers

---

app/Resources/views/blog/program.html.twig
sources/AppBundle/Event/Model/Planning.php
sources/AppBundle/Event/Model/Repository/PlanningRepository.php
sources/AppBundle/Event/Model/Repository/RoomRepository.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Room.php

J'ai besoin de le passer rapidement car actuellement le programme n'apparait pas :'(

Ajout de la date plannifiée sur le programme

---

htdocs/pages/administration/forum_planning.php

On augmente la précision du planning

---

htdocs/templates/phptournantes2017/js/inscription.js

Cette PR tire parti du localStorage lorsque disponible afin d'y stocker au fur et à mesure les données du formulaire d'inscription et le pré-remplir automatiquement lors d'une revisite sur le formulaire en cas d'inscription non finalisée.

FIX #222 on reremplit automatiquement l'inscription

---

htdocs/pages/administration/forum_conferenciers.php

J'ai pas pu m'empêcher de remettre le fichier au propre pour qu'il soit lisible, mais au moins le bug est corrigé, il s'agissait de paramètres incorrects lors de l'appel de la méthode

FIX #186 les badges conférenciers sont créés avec le statut invité

---

sources/Afup/Oeuvres.php

FIX #357 (je suppose en tous cas)

Correction erreur 500 sur calcul oeuvres

---

app/config/routing/admin.yml
sources/AppBundle/Controller/AdminMemberShipController.php

Allow super admin to update company

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/cfp/edit.html.twig
app/Resources/views/event/cfp/propose.html.twig
sources/AppBundle/Event/Form/TalkType.php

On accepte le COC & d'être filmé / photographié quand on soumet une conf

FIX #347 COC

---

sources/AppBundle/Slack/MessageFactory.php

We avoid to be redirected to the login page.

Change the URL to avoid redirect

---

app/Resources/views/site/offices.html.twig

modification de l'affichage de la page antenne

---

app/Resources/views/admin/base_with_header.html.twig
app/Resources/views/admin/menu.html.twig
htdocs/templates/administration/style.css

J'en avais tellement marre de ce menu pourri à gauche…

Move menu in top of the page

---

htdocs/pages/administration/forum_inscriptions.php

Champs obligatoires préremplis

---

htdocs/pages/administration/forum_sessions.php
htdocs/templates/administration/forum_sessions.html
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Indexation/Talks/Transformer.php

Cela va permettra de trouver facilement l'adresse de la fiche.

sessions : ajout d'un lien vers la fiche publique depuis l'admin

---

htdocs/pages/administration/forum_sessions.php
htdocs/templates/administration/forum_sessions.html
sources/Afup/Forum/AppelConferencier.php

 ajout d'un filtre permettant de filtrer sur les sessions planifiées 

---

app/Resources/views/event/cfp/edit.html.twig

I have added the number of vote inside the cfp edit view (https://afup.org/event/forumphp2017/cfp/{id}).
I would also like to add the average of vote, but I prefer to have a feedback on it before.

Displaying the number of vote inside the cfp edit view

---

htdocs/pages/administration/forum_inscriptions.php
htdocs/templates/administration/forum_inscriptions.html
sources/AppBundle/Event/Model/Repository/TicketEventTypeRepository.php
sql/2017-06-15-afup_forum_tarif_old_event.sql

Affichage billets depuis la BDD dans le BO

---

app/Resources/translations/messages.en.yml
app/Resources/translations/messages.fr.yml
app/Resources/views/event/sponsorship_file/base.html.twig
app/Resources/views/event/sponsorship_file/form.html.twig
app/Resources/views/event/sponsorship_file/thanks.html.twig
app/config/parameters.yml.dist
app/config/routing/event.yml
app/config/services.yml
composer.json
composer.lock
htdocs/css/tickets.css
htdocs/pages/administration/forum_gestion.php
sources/Afup/Forum/Forum.php
sources/Afup/Utils/Mail.php
sources/AppBundle/Association/CompanyMembership/InvitationMail.php
sources/AppBundle/Association/UserMembership/AbstractUserReminder.php
sources/AppBundle/Controller/LeadController.php
sources/AppBundle/Event/Form/LeadType.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Lead.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
sources/AppBundle/Event/Model/Repository/LeadRepository.php
sources/AppBundle/Event/Sponsorship/SponsorshipLeadMail.php
sources/AppBundle/Event/Ticket/SponsorTokenMail.php
sql/2017-06-15-trello-list-id.sql

Ajout d'une page de collecte de lead, qui crée une carte dans le trello sponsor

FIX #390 Collecte de Lead Trello pour le dossier de sponsoring

---

app/Resources/views/event/ticket/ticket.html.twig
sources/AppBundle/Event/Form/TicketType.php

ajout d'un message pour promouvoir les billets normaux et late avant leur date de début

---

sources/Afup/Forum/Inscriptions.php
sources/AppBundle/Command/TicketStatsNotificationCommand.php
sources/AppBundle/Notifier/SlackNotifier.php
sources/AppBundle/Slack/MessageFactory.php

cf #407 (par contre c'est un peu différent, au lieu d'une notif à chaque inscription, on a une notif par jour)

ajout d'une commande pour afficher régulièrement l'état des inscriptions

---

app/Resources/views/blog/planning.html.twig

correction affichage du planning

---

sources/Afup/Comptabilite/Facture.php

FIX #376 Facture payable à réception

---

sources/Afup/Forum/Facturation.php

Au passage on ajoute le nom de l'événement en lieu et place du nom générique "forum"

FIX #433 Cellule trop petite pour le champ "technical_name"

---

app/Resources/views/blog/talk.html.twig
app/config/routing/blog.yml
sources/AppBundle/Controller/BlogController.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

Cela permettra d'afficher des informations sur la/les confs du/des speaker(s)
qui sont interviewés.

ajout d'une action pour afficher des infos sur les talks sur event.afup.org

---

event/resources/themes/basis_child/style.css

ajout d'une marge sur les bouttons twitter

---

app/Resources/views/event/ticket/ticket.html.twig

attention, elle est hardcodée, il faudra penser à la modifier/rendre ça dynamique pour le prochain event.

ajout d'une twitter card sur la billeterie

---

app/Resources/views/admin/event/export_anonymous.html.twig
app/config/config.yml
app/config/routing/admin_event.yml
app/config/services.yml
sources/AppBundle/Controller/AdminEventController.php
sources/AppBundle/Event/AnonymousExport.php
sources/AppBundle/Event/Model/Repository/TicketRepository.php

Cet export anonymisé des inscrits (et harmonisé pour éviter les différences de casse ou d'accents) de l'ensemble des inscrits à tous les forums permet de construire des analyses autour des revisites

Export anonymisé des inscrits

---

app/config/parameters.yml.dist
sources/Afup/Utils/Base_De_Donnees.php

Faut vraiment lui demander gentiment pour qu'elle vienne

Connexion paresseuse à la base de données

---

event/composer.json
event/composer.lock

Revert "mise à jour de wordpress en version 4.7.6"

---

htdocs/templates/planete/index.html

version responsive planete

---

app/Resources/views/blog/planning.html.twig

on laisse de l'espace entre le titre de la conf et le speaker

---

sources/AppBundle/Event/Form/TalkType.php

on enlève les ateliers pour le prochain CFP

---

app/Resources/views/event/ticket/ticket.html.twig
htdocs/css/tickets.css

FIX #496 Mise en avant différentes inscriptions
FIX #504 Inscriptions: préciser workflow

Formulaire d'inscription

---

app/Resources/views/site/meetups/list.html.twig
app/config/parameters.yml.dist
app/config/routing.yml
app/config/routing/meetups.yml
composer.json
composer.lock
htdocs/.htaccess
htdocs/css/grid.css
htdocs/css/meetups/list.css
htdocs/js/meetups/list.js
sources/AppBundle/Command/IndexMeetupsCommand.php
sources/AppBundle/Controller/MeetupsController.php
sources/AppBundle/Indexation/Meetups/Runner.php
sources/AppBundle/Indexation/Meetups/Transformer.php
sources/AppBundle/Offices/OfficesCollection.php
tests/units/AppBundle/Indexation/Meetups/Transformer.php

Ajout d'une page affichant les meetups dans les antennes

---

app/Resources/views/event/base.html.twig
app/Resources/views/site/meetups/list.html.twig
htdocs/css/buttons.css
htdocs/css/vote.css
htdocs/js/meetups/list.js

ajout d'un bouton d'inscription pour distinguer les meetups à venir

---

docker/dockerfiles/apachephp/Dockerfile

Certaines pages, comme le CFP ou la billeterie en avaient besoin.

ajout de intl, qui était manquant dans l'env de dev

---

app/Resources/views/site/meetups/list.html.twig
app/Resources/views/site/talks/list.html.twig
htdocs/css/grid.css
htdocs/css/meetups/list.css
htdocs/css/talk/list.css
htdocs/js/meetups/list.js

Version mobile meetups

---

htdocs/pages/administration/membre_assemblee_generale.php

$_SESSION['afup_login'] est obsolète avec la gestion des sessions par sf

Correction prise en compte présence AG

---

app/Resources/views/site/offices.html.twig
sources/AppBundle/Controller/StaticController.php
sources/AppBundle/Offices/OfficesCollection.php

La liste des antennes était à la fois dans le template des antennes
et dans la classe OfficesCollection, on utilise maintenant OfficesCollection
dans le template.

factorisation de la liste des antennes

---

htdocs/pages/administration/membre_assemblee_generale.php

merci à @ratibus pour la remontée de bug.

correction typo sur la page participation à l'AG

---

app/Resources/views/site/base.html.twig
htdocs/css/grid.css
htdocs/templates/site/css/styles.css

ajout d'une ligne au dessus du footer pour les réseaux sociaux et la newsletter

---

app/Resources/views/base.html.twig
app/Resources/views/event/base.html.twig
app/Resources/views/event/menu.html.twig
app/Resources/views/site/base.html.twig
docker-compose.override.yml-dist
event/resources/themes/basis_child/header.php
htdocs/css/vote.css
htdocs/pages/planete/styles.css
htdocs/templates/planete/index.html
htdocs/templates/site/css/styles.css

ajout d'un menu global pour présenter tous les sites de l'AFUP

---

app/Resources/views/site/base.html.twig
htdocs/templates/site/css/styles.css

suppression de la tagline sur la home

---

app/Resources/views/base.html.twig
app/Resources/views/site/base.html.twig
htdocs/templates/site/css/styles-without-compass.css
htdocs/templates/site/css/styles.css
sources/Afup/Corporate/Branche.php
sources/Afup/Corporate/Page.php

on passe le footer sur 3 colonnes

---

app/Resources/views/site/meetups/list.html.twig
app/Resources/views/site/offices.html.twig
app/Resources/views/site/secondary_menu.html.twig
htdocs/templates/site/css/styles.css
sources/Afup/Corporate/Feuille.php
sources/AppBundle/Controller/SecondaryMenuController.php

ajout d'un sous menu sur les pages liées aux antennes

---

app/Resources/views/site/cms_page/display.html.twig
app/config/routing.yml
app/config/routing/cms_page.yml
htdocs/.htaccess
htdocs/pages/.htaccess
htdocs/pages/administration/site_rubriques.php
sources/Afup/Corporate/Article.php
sources/Afup/Corporate/Rubrique.php
sources/AppBundle/Controller/CmsPageController.php
sql/2018-02-03-rubrique-feuille.sql

ajout d'un sous menu sur la page association

---

app/Resources/views/site/home.html.twig
app/config/routing.yml
app/config/routing/global.yml
htdocs/.htaccess
htdocs/index.php
htdocs/pages/.htaccess
htdocs/templates/site/css/styles.css
sources/Afup/Corporate/Feuille.php
sources/AppBundle/Controller/HomeController.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

desktop avant:
desktop après:
mobile avant:
mobile après:

modification de la façon dont est agencée la home

---

app/Resources/views/site/base.html.twig
htdocs/templates/site/css/styles.css
sources/Afup/Corporate/Page.php

On met en avant le bouton d'adhésion, et rends les boutons plus
en accord avec les dernières adaptations sur le site.
avant:
après:

modification de l'affichage des boutons de connexion et d'adhésion

---

app/Resources/views/site/news/display.html.twig
app/Resources/views/site/news/list.html.twig
app/Resources/views/site/pager.html.twig
app/config/config.yml
app/config/routing.yml
app/config/routing/news.yml
app/config/services.yml
htdocs/.htaccess
htdocs/pages/.htaccess
htdocs/templates/site/css/styles.css
sources/Afup/Corporate/Rubrique.php
sources/AppBundle/Controller/NewsController.php
sources/AppBundle/Controller/PagerController.php
sources/AppBundle/Site/Form/NewsFiltersType.php
sources/AppBundle/Site/Model/Article.php
sources/AppBundle/Site/Model/Repository/ArticleRepository.php

liste avant:
liste après:
actualité avant:
actualité après:
Modifications:
* les urls sont maintenant plus propres, elles passent de : `https://afup.org/pages/site/?route=actualites/982/decouvrez-le-programme-du-php-tour-montpellier` à : `https://afup.org/news/982-decouvrez-le-programme-du-php-tour-montpellier`
* la colonne de droite à été supprimée sur la liste et l'actualité (cela permet de mieux se concentrer sur le contenu de la page)
* au vu de la suppression de la colonne de droite sur la page actualité, on centre le contenu
* sur le vue liste, il est maintenant possible de filtrer les actualités par année
* avant la date était mise en avant et rendait peu lisible les listes et page actualité : ce n'était pas l'information principale 
* les boutons voir plus ont été modifiés pour …

Refonte page actualités

---

htdocs/pages/administration/site_feuilles.php
htdocs/templates/site/css/styles.css
sources/Afup/Corporate/Feuille.php
sources/Afup/Corporate/Page.php
sources/AppBundle/Listener/LegacySiteListener.php
sql/2018-02-09-feuille-patterns.sql

en-tête : on met en évidence l'item de menu courant
avant:
après:

menu d'en-tête : on met en évidence l'item de menu courant

---

app/Resources/views/site/news/list.html.twig
htdocs/pages/administration/site_articles.php
htdocs/templates/administration/site_articles.html
sources/Afup/Corporate/Article.php
sources/AppBundle/Site/Form/NewsFiltersType.php
sources/AppBundle/Site/Model/Repository/ArticleRepository.php
sql/2018-02-10-articles-categories.sql

ajout de filtre sur les thèmes/cycle de conférences sur la page actualités

---

app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker
app/config/routing.yml
app/config/routing/techno_watch.yml
htdocs/.htaccess
sources/AppBundle/Calendar/TechnoWatchCalendarGenerator.php
sources/AppBundle/Controller/TechnoWatchController.php

Permet d'ajouter ces événements dans nos agendas en filtrant éventuellement
par personne.

ajout d'un calendrier pour savoir qui s'occupe de la veille

---

htdocs/pages/administration/cotisations.php
htdocs/pages/administration/membre_cotisation.php
sources/Afup/Association/Cotisations.php

Utilisation du service de Mail pour envoyer les factures de cotisations

FIX #533 Envoi de la facture de cotisation par mail

---

app/config/services.yml
sources/AppBundle/Command/RegistrationsByOfficeExporterCommand.php
sources/AppBundle/Command/RegistrationsExporterCommand.php
sources/AppBundle/Event/Ticket/RegistrationsExportGenerator.php
sources/AppBundle/Offices/OfficeFinder.php

On avait deux fichiers pour générer les badges : le détail des inscriptions et la les antennes correspondantes, maintenant tout est dans un seul fichier.
(la commande à été modifiée pour pouvoir la passer facilement dans un controlleur dans un second temps)

Génration d'un seul fichier pour générer les badges

---

app/Resources/views/event/vote/sidebar.html.twig

refs #397 ajout texte d'explications sur influence des votes

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/speaker-suggestion/index.html.twig

ajout de la traduction sur les libellés/boutons de la page suggestion de speaker

---

htdocs/pages/administration/membre_coordonnees.php

Suppression de la limite de 30 caractères pour les mots de passes
(pour l'histoire, j'ai galéré parce que mon auto-fill des champs modifiait l'email ... sans que je le vois D:)
- Fixes #624

removing maxlength on user password field

---

README.md

Corrections & ajouts d'informations dans le README
Il faudrait voir pour l'image `afup-web_event_1`, je n'arrive pas y accéder ?
(cf. https://i.imgur.com/sa59V36.png)

Improving readme for contributors

---

app/Resources/views/event/home.html.twig

Corrige le countdown pour afficher les minutes & secondes.
- Fixes #421

CFP: bug sur dernières minutes

---

app/Resources/views/blog/planning.html.twig
app/Resources/views/blog/program.html.twig
db/migrations/20180718212829_planning_announcement.php
htdocs/pages/administration/forum_gestion.php
sources/Afup/Forum/Forum.php
sources/AppBundle/Event/JsonLd.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

On permet de définir une date à partir de laquelle on affiche le planning et les infos liées (cela permet de préparer le planning dans le BO et ne pas avoir les infos affichées directement en front).

Programmation de l'affichage du planning

---

event/resources/themes/basis_child/style.css

Amélioration affichage abstracts sur les articles des interviews

---

htdocs/pages/administration/membre_cotisation.php
sources/Afup/Association/Cotisations.php
sources/Afup/Droits.php

Vérifie que l'utilisateur a le droit d'accéder à une facture avant de l'envoyer par mail ou de la télécharger.

fix droits sur l'accès des factures

---

app/Resources/views/admin/techletter/generate.html.twig
app/config/parameters.yml.dist
app/config/parameters.yml.dist-docker
app/config/routing/techletter_admin.yml
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php

cela simplifiera les suppressions / modifications en les faisant dans le BO au lieu de sur Mailchimp

on permet d'envoyer facilement des mail de test de la techletter

---

db/seeds/Techletter.php
db/seeds/Users.php

* on ajoute deux exemples sur la techletter (un envoyé, l'autre non)
* on fait en sorte que l'admin soit réelement admin

ajout seed techletter et amélioration seed users

---

app/Resources/translations/messages.en.yml
app/Resources/views/admin/event/speakers_management.html.twig
app/Resources/views/event/speaker/page.html.twig
app/config/security.yml
db/migrations/20190103181152_activation_hotel_et_resto.php
htdocs/pages/administration/forum_gestion.php
sources/Afup/Forum/Forum.php
sources/AppBundle/Controller/EventController.php
sources/AppBundle/Controller/SpeakerController.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

Pour les AFUP Day on a plusieurs événements en même temps, et on a pas de nuits d'hôtel à récolter, on ajoute donc des options pour activer ou non ces fonctionnalités.

Gestion des événements multiples sur la page des speakers

---

app/Resources/views/site/offices.html.twig

Modification de la page des antennes.

---

db/seeds/ComptaCategorie.php
db/seeds/ComptaCompte.php
db/seeds/ComptaEvenement.php
db/seeds/ComptaOperation.php
db/seeds/ComptaPeriode.php
db/seeds/ComptaReglement.php

Ajout des données dans les tables compta_* pour que le site BO fonctionne lors des tests de la partie comptabilité.

ajout des seed pour l'init de la partie compta dans la base de données

---

composer.json
docker/dockerfiles/apachephp/Dockerfile

Correction du problème des dates dans les formulaires lors de la modification.

mise à jour de la dépendance quickform

---

htdocs/templates/administration/forum_inscriptions.html

il ne fonctionnait que sur le dernier event

correction du lien d'exportation des inscriptions pour les pages

---

app/Resources/views/site/talks/list.html.twig
htdocs/css/grid.css
sources/AppBundle/Controller/TalksController.php

Modifications pour traitement de l'issue #779.

Ajout des liens Youtube des antennes dans la page des talks.

---

app/Resources/views/site/talks/show.html.twig

gestion des événements d'un jour sur la page de détail d'un talk

---

app/Resources/views/admin/event/speakers_management.html.twig

correction type sur la page d'admin de gestion documentaire des speakers

---

app/Resources/views/site/become_member.html.twig
htdocs/css/argument-list.css
htdocs/templates/site/scss/generic/table.scss

Et pour éviter qu'elle ne prenne trop de place on la passe sur deux
colonnes.
refs #800

On passe la liste des avantages membres en haut de la page

---

db/migrations/20190721161626_techletter_url.php
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/TechLetter/Model/Repository/SendingRepository.php
sources/AppBundle/TechLetter/Model/Sending.php

cela permettra dans le nouvel espace membre de consulter l'historique.

Mémorisation en base de l'url pour consulter la techletter lors de sa création

---

sources/AppBundle/Event/Model/Speaker.php
sources/AppBundle/VideoNotifier/TweetGenerator.php
tests/units/AppBundle/Indexation/Talks/Transformer.php

on passe les noms des speakers en majuscule

---

app/Resources/views/admin/association/membership/_member_menu.html.twig

Correction d'une faute dans le menu des membres

---

app/Resources/views/site/talks/show.html.twig
db/migrations/20190827181213_lien_interview.php
htdocs/pages/administration/forum_sessions.php
htdocs/templates/administration/forum_sessions.html
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php

ajout des interviews sur les pages des talks

---

htdocs/pages/administration/compta_devis.php
htdocs/pages/administration/compta_facture.php
htdocs/templates/administration/compta_devis.html
htdocs/templates/administration/compta_facture.html

fixes #815
Avec un lien depuis la page de modifcation de devis on arrive
sur la page de création de devis préremplie avec les champs du
devis d'origine.

on permet de dupliquer un devis

---

app/Resources/views/admin/association/membership/_company_menu.html.twig
app/Resources/views/form_theme_help.html.twig
app/Resources/views/site/member/company_public_profile.html.twig
app/Resources/views/site/member/index.html.twig
app/config/config.yml
app/config/routing/member.yml
app/config/services.yml
db/migrations/20190831190911_page_publiques_personnes_morales.php
htdocs/css/forms_company.css
sources/AppBundle/Association/Form/CompanyPublicProfile.php
sources/AppBundle/Association/Form/HelpMessageExtension.php
sources/AppBundle/Association/Model/CompanyMember.php
sources/AppBundle/Association/Model/Repository/CompanyMemberRepository.php
sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php

Ajout dune page dans l'espace membre pour saisir les infos de page publique

---

db/migrations/20191005151243_emojis_comments.php
htdocs/pages/administration/forum_inscriptions.php

on permet de les saisir dans le BO en passant par ting et corrige le charset du champ

correction saisie emojis dans les tags

---

htdocs/pages/administration/paybox_effectue.php

on renvoie vers la nouvelle page membre au lieu de l'admin après paiement de la cotisation

---

app/Resources/views/event/home.html.twig
htdocs/pages/administration/forum_gestion.php
htdocs/templates/administration/forum_gestion.html

Cela évitera d'utiliser tinymce qui n'est pas des plus pratiques
à utiliser.

on permet de saisir le texte des CFP en markdown

---

sources/AppBundle/Association/CompanyMembership/Reminder15DaysAfterEnd.php
sources/AppBundle/Association/CompanyMembership/Reminder15DaysBeforeEnd.php
sources/AppBundle/Association/CompanyMembership/Reminder7DaysBeforeEnd.php
sources/AppBundle/Association/UserMembership/Reminder15DaysAfterEnd.php
sources/AppBundle/Association/UserMembership/Reminder15DaysBeforeEnd.php
sources/AppBundle/Association/UserMembership/Reminder7DaysBeforeEnd.php
sources/AppBundle/Association/UserMembership/ReminderDDay.php

Mise à jour du contenu des mails de relance de cotisation

---

sources/AppBundle/Association/Model/Repository/UserRepository.php
sources/AppBundle/Command/UpdateUserStateCommand.php

Cela va permettre de calculer correctement le nombre de membres à
jour de cotisation sur les différentes pages de statistiques.

ajout d'une commande pour mettre à jour le statut des membres

---

sources/AppBundle/Event/Model/Repository/TicketRepository.php
sources/AppBundle/Event/Ticket/TicketTypeAvailability.php

Si on avait une limite sur le type de place on comptait toutes les places
peu importe le type.
Il faut bien compter le nombre de places peu importe le type (dans la limite
du nombre de places disponible au total).
fixes #888

correction calcul du stock restant quand on a une limite sur le type

---

db/migrations/20191209155002_needs_up_to_date_membership.php
htdocs/pages/administration/personnes_physiques.php
htdocs/templates/administration/personnes_physiques.html
sources/Afup/Association/Personnes_Physiques.php

Certains membres comme ceux du bureau ou des orgas d'antennes doivent être à jour de cotisation.
On simplifie cette vérification via un flag / filtre.

simplification vérification cotisation de certains membres

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.html

* on permet de ventiler sur plusieurs lignes d'un coup
* on ne renvoie plus vers la page de modification de la dernière ligne crée, mais sur le journal, au niveau de la ligne dernièrement crée

améliorations ux journal compta

---

htdocs/templates/administration/compta_facture.html

ajout référence client sur liste des factures

---

app/Resources/views/event/sponsorship_file/form.html.twig
sources/AppBundle/Event/Form/LeadType.php
sources/AppBundle/Event/Model/Lead.php
sources/AppBundle/Event/Model/Repository/LeadRepository.php

L'information n'est pas utilisée donc autant ne pas la demander.

suppression du poste sur le formulaire pour devenir sponsor

---

app/config/config.yml

on donne le droit à certaines pages aux personnes ayant le droit de
gestion du Forum.

correction des droits d'accès aux pages du forum

---

htdocs/pages/administration/site_articles.php
sources/Afup/Corporate/Articles.php

La recherche sur les articles ne fonctionnait pas, c'est maintenant corrigé.

admin : correction de la recherche sur les articles

---

htdocs/pages/administration/site_rubriques.php
sources/Afup/Corporate/Rubriques.php

La recherche sur les rubriques ne fonctionnait pas, c'est maintenant corrigé.

admin : correction de la recherche sur les rubriques

---

htdocs/pages/administration/assemblee_generale.php
htdocs/templates/administration/assemblee_generale.html
sources/Afup/Utils/PDF_AG.php

Cela permet d'avoir plus de controle sur la sortie et ne plus dépendre
de la CSS.

on passe le l'émargement de l'AG en pdf

---

app/Resources/views/event/cfp/home.html.twig
app/config/routing/event.yml
app/config/services.yml
sources/AppBundle/CFP/ViewModel/EventTalkList.php
sources/AppBundle/Controller/CFPController.php
sources/AppBundle/Controller/Event/AbstractEventAction.php
sources/AppBundle/Controller/Event/CFP/IndexAction.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Listener/LegacySiteListener.php

Ajout de l'historique des propositions dans l'espace speaker des CFP

---

app/Resources/views/admin/speaker/edit.html.twig
sources/AppBundle/CFP/PhotoStorage.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerAddAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerDeleteAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerEditAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerLinkGravatarAction.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerRegisterAction.php
sources/AppBundle/Event/Form/SpeakerFormData.php

+ fix enregistrement photo quand champ vide + amélioration redirection vers liste des speakers

fix lien disparu vers la photo originale du speaker

---

README.md
app/Resources/views/site/company_membership/paybox_redirect.html.twig
app/config/routing/site.yml
sources/Afup/Utils/Configuration.php
sources/AppBundle/Command/DevCallBackPayboxCotisationCommand.php
sources/AppBundle/Controller/MemberShipController.php
sources/AppBundle/Controller/PayboxRedirectAction.php
sources/AppBundle/Payment/PayboxFactory.php

modification pour utiliser Symfony pour le retour après le paiement de la cotisation
ref #942
Résultat:

modification pour utiliser Symfony pour le retour après le paiement

---

app/Resources/views/admin/event/list.html.twig
app/config/config.yml
app/config/routing/admin_event.yml
htdocs/pages/administration/forum_gestion.php
htdocs/templates/administration/forum_gestion.html
sources/AppBundle/Controller/Admin/Event/ListAction.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

migration liste des événements vers symfony
nettoyage du code legacy

migration liste des événements

---

app/Resources/translations/messages.en.yml
app/Resources/views/event/cfp/vote_only.html.twig

fix phrase ref #701

---

app/Resources/views/admin/event/list.html.twig
app/config/routing/admin_event.yml
htdocs/pages/administration/forum_gestion.php
sources/AppBundle/Controller/Admin/Event/RemoveEventAction.php
sources/AppBundle/Event/Model/Repository/EventRepository.php

migration de l'action de suppression d'un evenement + securite augmentée

migration de l'action de suppression d'un evenement

---

sources/Afup/Comptabilite/Facture.php

devis not transform to facture have not a facture date

Filtrer devis by devis date

---

sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Talk/ExportGenerator.php

En ajoutant cet id cela permettra de simplifier le travail
préparatoire à au sous-titrage.

ajout de l'id youtube sur l'export des conférences

---

htdocs/pages/administration/compta_journal.php

suite au refacto de la description des écritures du journal

Corrige une regression sur la détection des lien paybox 

---

db/migrations/20210208174605_afup_cotisation_create_reference_client.php
htdocs/pages/administration/cotisations.php
sources/Afup/Association/Cotisations.php

Besoin de ce nouveau champ pour pouvoir afficher des références nécessaires au client sur les factures de cotis (ici un bon de commande)

Add reference client facture cotisations

---

app/Resources/views/admin/members/general_meeting_vote/list.html.twig
app/Resources/views/site/member/index.html.twig
sources/AppBundle/Controller/Admin/Members/GeneralMeetingVote/ListAction.php
sources/AppBundle/Controller/MemberController.php
sources/AppBundle/Controller/MemberShipController.php

* on empêche de voter pour un vote non ouvert
* ajout d'un gros bouton sur l'accueil de l'espace membre le jour du vote pour accéder à la partie AG
* on affiche les résultats pendant le vote dans l'admin

améliorations / corrections sur le système de vote AG

---

app/Resources/translations/messages.en.yml
app/Resources/translations/messages.fr.yml
sources/AppBundle/Event/Talk/InvitationFormHandler.php

Try user's name , fallback on login.
Closes #710

feat(invitation-email): prefer name to login on email

---

app/Resources/views/site/offices.html.twig
sources/AppBundle/Offices/OfficesCollection.php

ajout des liens workadventure sur la page des antennes

---

app/Resources/views/blog/planning.html.twig
sources/AppBundle/Controller/BlogController.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php

Sur le wordpress, on va pouvoir avoir des urls comme celle-ci actuellement :
https://172.17.0.1:9206/blog/forumphp2018/planning
Mais aussi des urls comme celle-ci :
https://172.17.0.1:9206/blog/forumphp2018,forumphp2019/planning

on permet d'avoir sur une même page de planning plusieurs events

---

app/Resources/translations/messages.en.yml
db/migrations/20210820214305_mme_mle.php
htdocs/pages/administration/forum_inscriptions.php
htdocs/pages/administration/personnes_morales.php
sources/AppBundle/Association/Form/UserEditFormData.php
sources/AppBundle/Association/Form/UserEditType.php
sources/AppBundle/Controller/LegacyController.php
sources/AppBundle/Event/Form/SpeakerType.php
sources/AppBundle/Event/Form/SponsorTicketType.php
sources/AppBundle/Event/Form/TicketType.php
sources/AppBundle/Security/TestGithubAuthenticator.php
tests/behat/features/Admin/AdminEvenements.feature
tests/behat/features/Admin/AdminPersonnesMorales.feature
tests/behat/features/Admin/AdminPersonnesPhysiques.feature
tests/behat/features/EventPages/Cfp.feature
tests/behat/features/EventPages/CfpEn.feature
tests/behat/features/EventPages/Ticketing.feature
tests/behat/features/EventPages/TicketingEn.feature
tests/behat/features/PublicSite/Register.feature
translations/inscription.en.xlf

Reprise de la PR #1026 en mettant le bon patch SQL (et en utilisant phinx). en adaptant les tests et créant des nouveaux cas, ainsi qu'en ne traitant pas les pages comme "membre_personne_morale.php" qui ne semblent plus utilisées
fixes issue #890

Suppression de Mlle dans nos différents formulaires

---

app/Resources/views/site/talks/show.html.twig
composer.json
composer.lock
db/migrations/20210920111110_talk_transcript.php
htdocs/js/talk/list.js
htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/Afup/Utils/Base_De_Donnees.php
sources/AppBundle/Controller/TalksController.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php
sources/AppBundle/Subtitles/Parser.php
tests/units/AppBundle/Subtitles/Parser.php

sous la page du talk on affiche les sous titres qu'on a tenté de grouper en paragraphes. Au clic sur celui-ci on accède au moment correspondant dans la vidéo.

on affiche les sous titres en dessous de la page talk

---

htdocs/css/grid.css

Corrige la largeur de la colonne en CSS quand il y a une vidéo Youtude liée au Talk d'après l'issue #892.

Issue 892 CSS Youtube embed

---

app/AppKernel.php
app/config/config.yml
composer.json
composer.lock

On a certaines erreurs qui ne sont pas remontées sur new relic.
Avec l'intégration du bundle ekino, celles-ci devraient être remontées.

Meilleure intégration de new relic

---

app/Resources/views/admin/association/membership/membershipfee.html.twig
sources/AppBundle/Controller/MemberShipController.php
tests/behat/features/MembersArea/Index.feature

On autorise la seule personne physique à accéder à la facturation.

Issue #1058 access invoices is_granted

---

app/Resources/views/site/meetups/list.html.twig

Add typo correction.  #1144 resolved ✔️

Typo Correction

---

htdocs/pages/administration/site_articles.php
htdocs/templates/administration/site_articles.html

Cela permet de retrouve facilement l'url sans publier/dépublier ou le reconstituer
depuis l'id / slug.
fixes #1155

sur la page de modification d'un article on ajoute un lien vers l'article

---

README.md

Proposition d'ajout d'une partie décrivant comment lancer les tests à la main dans le README.

feat(doc) : Ajout d'une partie test dans le readme

---

app/Resources/views/site/become_member.html.twig

feat(#799) - Page devenir membre : ajouter un lien vers la FAQ

---

app/Resources/views/site/base.html.twig
app/Resources/views/site/become_member.html.twig
app/Resources/views/site/cms_page/display.html.twig
app/Resources/views/site/company_public_profile.html.twig
app/Resources/views/site/company_public_profile_list.html.twig
app/Resources/views/site/home.html.twig
app/Resources/views/site/meetups/list.html.twig
app/Resources/views/site/member/company_public_profile.html.twig
app/Resources/views/site/news/display.html.twig
app/Resources/views/site/news/list.html.twig
app/Resources/views/site/offices.html.twig
app/Resources/views/site/superapero.html.twig
app/Resources/views/site/talks/list.html.twig
app/Resources/views/site/talks/show.html.twig
app/Resources/views/site/techletter/index.html.twig
sources/AppBundle/Controller/NewsController.php

Amélioration des titres des pages et des attritbuts alt des images.
Issue : #1182

feat (#1182): amélioration des titres et de l'accéssibilité des images

---

app/Resources/views/admin/techletter/generate.html.twig
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/Mailchimp/Mailchimp.php

Voici un aperçu des modifications sur l'édition d'une veille : 
.

feat (1175, 1174): Veille: envoyer, verrouiller et planifier Mailchimp

---

htdocs/templates/administration/forum_inscriptions.html

Fix #1147 - remove BO export registrations action

---

sources/AppBundle/Association/Model/Repository/TechletterSubscriptionsRepository.php
tests/behat/features/Admin/Techletter/AdminVeilleAbonnés.feature

Fix #1136 - [Admin] correct the number of subscribers to the tech watch

---

app/Resources/views/site/talks/show.html.twig
db/migrations/20221106125854_talk_verbatim.php
htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php

On permet de saisir les verbatims du messageur et les affiche sur les pages talk

---

app/Resources/views/site/talks/show.html.twig
db/migrations/20221106180301_talk_openfeedback.php
htdocs/pages/administration/forum_sessions.php
sources/Afup/Forum/AppelConferencier.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/Talk.php

fixes #1211 
Exemple de rendu dans la partie "informations complémentaires"

on permet d'afficher un lien vers la page openfeedback depus la tage du talk

---

htdocs/templates/administration/forum_inscriptions.html

Solves #1158 
En effet @agallou  c'était bien ca, j'ai pu le tester en ajoutant un évènement et on pointe bien sur le current désormais

Fix afup/web #1158: replace with the correct forum ID

---

app/Resources/views/blog/talk.html.twig
sources/AppBundle/Event/Model/Repository/TalkRepository.php

Fix: take into account the publication date of the program

---

app/config/routing/event.yml
db/seeds/Conferenciers.php
db/seeds/GithubUsers.php
db/seeds/Session.php
htdocs/templates/administration/forum_gestion.html
sources/AppBundle/Controller/EventController.php
sources/AppBundle/Openfeedback/OpenfeedbackJsonGenerator.php
tests/behat/features/Admin/AdminGithubUsers.feature
tests/behat/features/Admin/AdminSpeakers.feature
tests/behat/features/Api/Talks/OpenfeedbackExport.feature

Solves #1214 
Fonctionnel et testé avec plusieurs scénarios.
**NB:**
Ngrok ne fonctionne pas à cause d'une page intermédiaire de sécurité. 
Utiliser un gist qui contient le json content à la place. Exemple [ici ](https://gist.githubusercontent.com/vinceAmstoutz/585d41446054ea53ca739355618b43ec/raw/11f83b53bffe0bb7d4513852061292f8bfa26792/afup_test_openfeedback.json).
TODO :

Simplify the import of talks on openfeedback

---

app/Resources/views/admin/event/mail_inscription.html.twig

feat (#1213): email d'inscription correction logo

---

Makefile
app/Resources/views/admin/login.html.twig
app/Resources/views/event/sponsorship_file/form.html.twig
app/Resources/views/event/ticket/paybox_redirect.html.twig
app/Resources/views/event/ticket/payment.html.twig
app/Resources/views/event/ticket/payment_already_done.html.twig
app/Resources/views/event/ticket/sold_out.html.twig
app/Resources/views/event/ticket/sponsor.html.twig
app/Resources/views/event/ticket/sponsor_home.html.twig
app/Resources/views/event/ticket/ticket.html.twig
app/Resources/views/site/home.html.twig
app/Resources/views/site/techletter/index.html.twig
htdocs/css/techletter.css
sources/AppBundle/Compta/BankAccount/BankAccountFactory.php
sources/AppBundle/Email/Emails.php
tests/behat/features/PublicSite/Sponsor.feature

feat(1235) Ajout h1 manquants sur certaines pages

---

app/config/services.yml
sources/AppBundle/Controller/LeadController.php

Le rendu mailcatcher du texte brut de l'email:

feat(#1241) Envoit d'un mail au pôle lors des demandes sur le site

---

app/Resources/views/site/member/index.html.twig

On précise à quoi correspond chaque partie de l'espace membre (sauf sur une partie qui sera supprimée), et en profite pour indiquer comment suivre l'AFUP.

espace membres : on ajout plus d'explications sur les différentes sections

---

app/Resources/views/site/superapero.html.twig

on modifie le texte d'intro pour la page du super apéro en 2023

modification texte pour super apéro 2023

---

app/Resources/views/event/ticket/sponsor_home.html.twig

[Issue 1244](https://github.com/afup/web/issues/1244)

#1244 add meta robot noindex on event sponsor page

---

htdocs/templates/administration/compta_devis.html
htdocs/templates/administration/compta_facture.html
tests/behat/features/Admin/Tresorerie/DevisFactures.feature
tests/behat/features/Admin/Tresorerie/Journal.feature

Traite les tests fonctionnels pour :
- Trésorerie
- Devis
- Factures
- Journal

Feat 1110 functional test

---

app/Resources/views/site/news/display.html.twig
sources/AppBundle/Controller/NewsController.php
sources/AppBundle/Site/Model/Article.php
sources/AppBundle/Site/Model/Repository/ArticleRepository.php

Traite l'issue : #1303 
L'idée est de se baser sur la permission `'ROLE_ADMIN'` pour pouvoir consulter un article même s'il n'est pas publié.

feat (#1303): Article preview

---

db/migrations/20231120220609_tva_journal.php
htdocs/pages/administration/compta_journal.php
sources/Afup/Comptabilite/Comptabilite.php

fixes #1338
* Ajout de nouveaux champs dans la table du journal
* dans l'admin on permet de les ajouter/modifier

fiscalisation : ajouter la TVA dans les entrées du journal

---

db/migrations/20231121201113_tva_devis_facture.php
htdocs/pages/administration/compta_devis.php
htdocs/pages/administration/compta_facture.php
sources/Afup/Comptabilite/Facture.php

* on ajoute le champ en base
* sur l'admin des devis/factures, on ajoute un champ TVA sur chaque ligne de contenu
* 
fixes #1343

ajout de la tva sur les lignes dans l'admin des devis/facture

---

htdocs/pages/administration/compta_journal.php
sources/Afup/Comptabilite/Comptabilite.php

Voici le genre d'export que cela donne : 
fixes #1352

ajout des infos de montants HT/de TVA dans le journal

---

sources/AppBundle/Event/Validator/Constraints/AvailableTicketValidator.php
sources/AppBundle/Event/Validator/Constraints/CorporateMemberValidator.php
sources/AppBundle/Event/Validator/Constraints/LoggedInMemberValidator.php
sources/AppBundle/Event/Validator/Constraints/PublicTicketValidator.php

La doc : https://symfony.com/doc/current/validation/custom_constraint.html
Fonctionnellement ça ne change rien, c'est juste mieux typé.

Correction de validators pour suivre la doc officielle

---

sources/Afup/Association/Cotisations.php
sources/Afup/Corporate/_Site_Base_De_Donnees.php
sources/Afup/Utils/Base_De_Donnees.php
sources/Afup/Utils/PDF_AG.php
sources/Afup/Utils/Pays.php
sources/Afup/Utils/Utils.php
sources/Afup/fonctions.php
sources/AppBundle/Association/CompanyMembership/SubscriptionManagement.php
sources/AppBundle/Association/Model/GeneralMeetingQuestion.php
sources/AppBundle/Association/Model/GeneralMeetingResponse.php
sources/AppBundle/Association/Model/Repository/CompanyMemberInvitationRepository.php
sources/AppBundle/Association/Model/Repository/CompanyMemberRepository.php
sources/AppBundle/Association/Model/Repository/GeneralMeetingQuestionRepository.php
sources/AppBundle/Association/Model/Repository/UserRepository.php
sources/AppBundle/Association/UserMembership/StatisticsComputer.php
sources/AppBundle/Calendar/IcsPLanningGenerator.php
sources/AppBundle/Calendar/JsonPlanningGenerator.php
sources/AppBundle/Command/SubscriptionReminderCommand.php
sources/AppBundle/Command/UpdateMailchimpMembersCommand.php
sources/AppBundle/Command/VideosDataCommand.php
sources/AppBundle/Controller/Admin/Event/PendingBankwiresAction.php
sources/AppBundle/Controller/Admin/Event/SendLastCallSponsorTokenAction.php
sources/AppBundle/Joindin/JoindinTalk.php
sources/PlanetePHP/PlaneteIndexAction.php

C'est du même genre que la #1368

Correction de docblocks

---

db/migrations/20231204211600_tva_intra_facture.php
htdocs/pages/administration/compta_devis.php
htdocs/pages/administration/compta_facture.php
sources/Afup/Comptabilite/Facture.php
tests/behat/features/Admin/Tresorerie/DevisFactures.feature

Ajout du numéro de TVA intra #1348.

Ajout TVA intracommunautaire

---

app/Resources/views/admin/association/membership/membershipfee.html.twig
db/seeds/Users.php
tests/behat/features/Admin/AdminPersonnesPhysiques.feature
tests/behat/features/MembersArea/Index.feature

Afin de préparer le dev #1350 on ajoute des tests sur les factures de cotisation.

Ajout de tests sur les factures de cotisation

---

sources/AppBundle/Compta/BankAccount/BankAccountFactory.php

le test https://github.com/afup/web/blob/e872ed563a2f3c5c805d0dfdd2dc7d2503e4f5e5/tests/behat/features/MembersArea/Index.feature#L70 ne passait pas parfois ou non selon l'heure à laquelle il était lancé (par exemple avant 15h il passait mais plus tard il était en erreur).
Cela car on avait un fichier généré qui était différent, on avait les infos de RIB qui changeait. Cela car la création de la date de cutoff entre les deux ribs se faisait en fonction de la date courante. On corrige donc cela en fixant l'heure de changement de RIB (dans les tests on avait une date de début de cotisation au premier janvier 2023)
Pour debugger, la libfaketime a été utilisée comme cela :
```diff
diff --git a/Makefile b/Makefile
index eddc535e..a9d97375 100644
--- a/Makefile
+++ b/Makefile
@@ -78,6 +78,10 @@ …
```

on corrige le lancement des tests selon l'heure à laquelle ils sont lancés

---

htdocs/pages/administration/compta_facture.php
sources/Afup/Utils/PDF_Facture.php
tests/behat/features/Admin/Events/FacturesEvennement.feature
tests/behat/features/MembersArea/Index.feature

on corrige des libellé intercommunautaire en intracommunautaire

---

app/Resources/views/admin/event/special_price.html.twig
sources/AppBundle/Event/Form/TicketSpecialPriceType.php

on indique que les tokens visiteur saisir le sont TTC

---

app/Resources/views/admin/event/prices.html.twig
sources/AppBundle/Association/Form/TicketEventType.php

on indique dans l'admin des tarifs qu'ils sont en ttc

---

htdocs/pages/paiement/index.php

on effectue le même calcul sur le PDF de facture
fixes #1353

on prends en compte la TVA dans les liens de paiement des factures

---

db/seeds/Users.php
sources/Afup/Association/Cotisations.php

Fiscalisation : on rends plus cohérent la cotisation personne morale fixe de 2024

---

db/seeds/Compta.php
features/bootstrap/FeatureContext.php
htdocs/templates/administration/compta_devis.html
tests/behat/features/Admin/Tresorerie/BalanceComptable.feature
tests/behat/features/Admin/Tresorerie/Bilan.feature
tests/behat/features/Admin/Tresorerie/CompteBanques.feature
tests/behat/features/Admin/Tresorerie/DevisFactures.feature
tests/behat/features/MembersArea/Index.feature

On corrige les tests qui sont cassé à cause du changement d'année.

Corrige les tests à cause du changement d'année

---

sources/AppBundle/Event/Form/SpeakerType.php
sources/AppBundle/Event/Validator/Constraints/CorporateMemberValidator.php
sources/AppBundle/Event/Validator/Constraints/LoggedInMemberValidator.php
sources/AppBundle/Security/LegacyAuthenticator.php
sources/AppBundle/Security/LegacyHashAuthenticator.php

Symfony retourne son interface qui ne contient pas toutes les méthodes nécessaires.

Vérification des instances de `User`

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.js.html

dans le journal on simplifie la saisie des montants HT en ajoutant des liens pour calculer automatiquement d'après le montant TTC.
voici ce que cela donne:
https://github.com/afup/web/assets/320372/ae8974aa-64cd-47b5-ae86-c518713320f5

Fiscalisation : on simplifie la saisie des montants HT dans le journal

---

htdocs/pages/administration/compta_journal.php
sources/AppBundle/Compta/Importer/CreditMutuelLivret.php
sources/AppBundle/Compta/Importer/Factory.php
sources/AppBundle/Model/ComptaCompte.php

Cela permet d'avoir des exports pour le comptable plus justes et de calculer les soldes des comptes.

on permet d'importer les fichiers CSV du livret dans le BO

---

app/Resources/views/admin/association/membership/membershipfee.html.twig

Un article de blog sera publié demain à propos des changements liés à la TVA et aux cotisations, on ajoute un bandeau à son propos sur la page des cotisations afin de pouvoir répondre à d'éventuelles questions.

Sur la page des cotisations on affiche un message pointant vers l'article de blog

---

sources/AppBundle/Event/Model/Repository/TicketSpecialPriceRepository.php

si on a une inscription annulée, on permet d'utiliser à nouveau le token.

gestion token visiteur et inscription annulée

---

app/config/config.yml
app/config/services.yml
db/migrations/20240106213200_sessions.php
htdocs/app.php
htdocs/include/prepend.inc.php
htdocs/pages/planete/app.php

Réouverture de la PR : https://github.com/afup/web/pull/1417 car cela n'a pas fonctionnait lors du déploiement en PROD.
Traite l'issue : [1415](https://github.com/afup/web/issues/1415)

afup#1415 Session in DB

---

sources/Afup/Bootstrap/Http.php
sources/Afup/Utils/Configuration.php

On sécurise le fichier de configuration dans le cas il y manque des paramètres.
On ajuste les erreurs en production.

afup#1416 fix missing parameters + error level

---

compose.yml
docker/dockerfiles/statictestresources/feed.xml
tests/behat/features/Admin/PlanetePHP/Flux.feature

On utilisait un vrai flux de prod, qui parfois avait des erreurs. Pour éviter cela on passe par un container où on met des ressources statiques pour les tests.
Cela sera aussi potentiellement utilisable pour les tests sur meetup qui par moments ont eut des soucis du même acabit.

on passe par un mock du flux pour s'éviter des erreurs

---

sources/Afup/Utils/Configuration.php

Optimisation du chargement de la configuration acte 2 scène 2.
J'ai passé les valeurs en static et on se base sur les variables d'environnements pour ne pas parser le yaml.
Il n'y a que le cas d'une surcharge via un fichier `parameter_ENV.yaml` qui va déclencher un parse de fichier.

afup#1442 optimisation du chargement de la configuration

---

sources/Afup/Utils/Configuration.php

Revert "afup#1442 optimisation du chargement de la configuration"

---

sources/Afup/Droits.php
sources/Afup/Utils/Utils.php
sources/AppBundle/Controller/LegacyController.php
sources/AppBundle/Controller/MemberShipController.php

Cette classe semble contenir pas mal de code qui ne sert plus :
- d'anciennes constantes
- des propriétés et méthodes inutilisées

[PHPStan] Nettoyage de la classe `Droits`

---

sources/AppBundle/Controller/Planete/ArticlesController.php
sources/PlanetePHP/FeedArticleRepository.php
tests/behat/features/Api/PlanetePHPApi.feature

Sans ces headers on ne peut pas savoir en avance s'il reste des pages.

Ajout de headers pour la pagination des articles

---

app/Resources/views/admin/members/general_meeting/list.html.twig
app/Resources/views/admin/members/general_meeting/reports.html.twig
app/config/config.yml
app/config/routing/admin.yml
db/seeds/GeneralMeetings.php
sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ReportsAction.php
tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingReports.feature

Traite l'issue : https://github.com/afup/web/issues/1461

afup#1461 General Meeting reports

---

app/Resources/views/admin/event/prices.html.twig
app/Resources/views/event/ticket/payment.html.twig
app/Resources/views/event/ticket/ticket.html.twig
db/migrations/20240510105738_prices_with_vat.php
db/seeds/Event.php
htdocs/js/inscription.js
htdocs/pages/administration/forum_gestion.php
sources/Afup/Forum/Facturation.php
sources/Afup/Forum/Forum.php
sources/Afup/Utils/Vat.php
sources/AppBundle/Association/Form/TicketEventType.php
sources/AppBundle/Controller/Admin/Event/PricesAction.php
sources/AppBundle/Controller/Admin/Event/PricesAddAction.php
sources/AppBundle/Controller/Admin/Event/PricesEditAction.php
sources/AppBundle/Controller/TicketController.php
sources/AppBundle/Event/Model/Event.php
sources/AppBundle/Event/Model/Repository/EventRepository.php
sources/AppBundle/Payment/PayboxFactory.php

Pour l'AFUP day on avait gardé des prix publics identiques et a calculé le HT d'après le TTC saisir dans les tarifs.
Pour le Forum au final on part différemment et part du HT saisi pour calculer le TTC.
Du coup il fallait faire des adaptations sur le tunnel, la saisie des tarifs et les factures, tout en faisant en sorte que les anciennes factures ne bougent pas.
Voici des captures d'écran de ce que donnent ces changements.
Dans l'admin d'un event on a une case à cocher décochée défaut, où ça sera cochée sur l'AFUP Day
Sur les tarifs en fonction de cette case à cocher on affiche HT ou TTC.
Voici ce que donne le tunnel, où toujours selon cette case à cocher, on afficher les prix en HT lors du choix du type de billet et calcule bien le TTC dans le résumé en bas.
Sur l'étape suivante on …

On permet de définir les prix en HT dans la tarification

---

sources/AppBundle/Controller/Admin/Membership/MembersAction.php

fix mini typo

---

htdocs/pages/administration/compta_journal.php
htdocs/templates/administration/compta_journal.html

Suppresion du code générant le lien de télécollecte et son utilisation

feat/1478 : Supprime le lien de télécollecte

---

app/Resources/views/site/become_member.html.twig

update(become_member): Supprimer certain avantage et ajout de précision concernant l'accès slack

---

sources/AppBundle/Controller/TicketController.php

Corrige l'issue #1512.
On corrige les conditions de blocage pour le soldout des tickets sponsors.

Corrige le BUG de modification d'un ticket sponsor issue#1512

---

app/config/config.php

Lire la configuration depuis les variables d'env en premier lieu sinon lire le fichier .env

Configuration depuis les variables d'env en premier

---

app/Resources/views/site/base.html.twig
app/Resources/views/site/newsletter/postsubscribe.html.twig
sources/AppBundle/Controller/NewsletterController.php
tests/behat/bootstrap/FeatureContext.php

feat(home): #1252 Changer la fréquence des emails + Changer le message lorsque le formulaire a fonctionné

---

sources/Afup/Forum/Forum.php

Pour la modification c'est déjà corrigé https://github.com/afup/web/blob/18b0cdad6a584717b26c69d55cc780bf06433780/sources/Afup/Forum/Forum.php#L685 Sans cela un une fois sur clever cloud on ne pourra plus inserer de forum.

corrige sur la date de fin de vote sur l'ajout d'un nouveau forum

---

app/Resources/views/admin/event/bankwires.html.twig

Feat back office add an information message to the upcoming transfers page

---

app/Resources/views/site/sitemap.html.twig

Corrige l'erreur 500 sur cette page : https://afup.org/plan-du-site

corrige la route member_membership dans le plan du site

---

db/seeds/Event.php
htdocs/js/vote.js
sources/AppBundle/Controller/Event/CFP/ProposeAction.php
sources/AppBundle/Event/Form/TalkType.php
tests/behat/features/EventPages/Cfp.feature

On n'affiche pas la proposition d'atelier pour les AFUP day.
Traite l'issue #1548

afup#1548 remove workshop afup day

---

sources/AppBundle/TechLetter/MailchimpSynchronizer.php

Amélioration des erreurs renvoyées par Mailchimp, traite l'issue #1553 .
Avant, quand une erreur d'API intervennait cela bloqué toute le synchronisation des abonnées.
Maintenant, on catch les erreurs et on les logs pour ne plus bloquer la synchronisation.
P.S. : J'ai fais un peu de ménage dans le fichier aussi.

afup#1553 fix mailchimp sync

---

app/Resources/views/blog/speakers.html.twig
sources/AppBundle/Event/Model/Speaker.php
sources/AppBundle/VideoNotifier/TweetGenerator.php
tests/units/AppBundle/Event/Model/Speaker.php

On améliore les URLs et username des réseaux sociaux pour les speakers.

afup#1285 speaker display mastodon link better username match

---

app/config/services.yml
db/seeds/Feuilles.php
sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
tests/behat/features/Admin/Site/AdminSiteFeuilles.feature

On termine cette issue : https://github.com/afup/web/issues/386 en ajoutant les membres au sitemaps.xml pour Google.
J'ai également ajouté le lien dans le footer vers le sitemap HTML dans le fixtures.

afup#386 sitemap add members

---

app/Resources/views/site/offices.html.twig

Issue 1556 - suppression colonne twitter et map responsive

---

app/Resources/views/site/offices.html.twig
sources/AppBundle/Offices/OfficesCollection.php

Elles ne servent plus et pourront être remises à la prochaine pandémie :trollface:

Suppression des URLs Work Adventure

---

sources/AppBundle/Subscriber/SitemapXmlSubscriber.php

On complète le sitemap pour Google en ajoutant les pages gérées par les Feuilles.
Cela permettra de clôturer l'issue #386

issue#386 sitemap google

---

app/Resources/views/admin/association/membership/generalmeeting.html.twig
htdocs/css/forms_company.css
sources/AppBundle/Controller/MemberShipController.php

Suite à des réponses étrange à la participation de l'Assemblée Générale, nous avons revu l'UX pour indiquer son choix :
https://github.com/user-attachments/assets/9dc9094b-aa76-4790-9f83-185a45b02578

Amélioration présence assemblée générale

---

sources/AppBundle/Offices/OfficesCollection.php

Bluesky - Ajout des nantais

---

app/config/config.yml

On passe le temps de session à 24 heures.

Temps de session de 24 heures

---

sources/Afup/Forum/AppelConferencier.php
tests/behat/features/Admin/Events/Planning.feature

Lors de la modification de la programmation d'une session dans le planning d'un évènement il y avait une erreur 500.
> Doctrine\DBAL\Exception\DriverException
Problème avec la valeur par défaut dans MySQL.
Ajout de tests fonctionnels pour valider la correction.

Corrige la modification de la programmation d'un session

---

htdocs/pages/administration/compta_facture.php
htdocs/templates/administration/compta_facture.html
sources/Afup/Comptabilite/Facture.php
sources/Afup/Forum/AppelConferencier.php
tests/behat/features/Admin/Tresorerie/DevisFactures.feature

On ajoute la pagination sur la liste des factures.

Pagination factures

---

db/migrations/20250210180403_planete_billet_encoding.php

J'ai remarqué dans les logs en prod qu'on avait des erreurs dans le cron de fetching des articles à cause de ça.

Mise à jour de l'encoding de la table `afup_planete_billet`

---

app/config/services.yml
composer.json
composer.lock
sources/AppBundle/Command/IndexMeetupsCommand.php
sources/AppBundle/Controller/Website/HomeController.php
sources/AppBundle/Indexation/Meetups/Runner.php
sources/AppBundle/Indexation/Talks/Runner.php

Toujours dans le cadre la préparation pour le mise à jour vers Symfony 4.4. (https://github.com/afup/web/issues/1616)
On met à jours la lib `AlgoliaSearch`.

Upgrade AlgoliaSearch

---

app/Resources/views/event/ticket/ticket.html.twig
app/Resources/views/site/secondary_menu.html.twig
composer.json
composer.lock
sources/AppBundle/Association/Form/CompanyPublicProfile.php
sources/AppBundle/Event/Speaker/SpeakerPage.php
sources/AppBundle/Planete/FeedFormData.php
sources/AppBundle/Security/TestGithubAuthenticator.php
sources/AppBundle/SpeakerInfos/Form/HotelReservationType.php

On supprime les dépréciations pour préparer la mise à jour vers Symfony 4.4. (https://github.com/afup/web/issues/1616)

Suppression des dépréciations

---

composer.json
composer.lock
htdocs/templates/administration/compta_balance.html
htdocs/templates/administration/compta_banque.html
htdocs/templates/administration/compta_bilan.html
htdocs/templates/administration/compta_journal.html
htdocs/templates/administration/forum_facturation.html
htdocs/templates/administration/forum_inscriptions.html
htdocs/templates/administration/forum_sessions.html
htdocs/templates/administration/personnes_morales.html
htdocs/templates/administration/site_articles.html
sources/Afup/Bootstrap/Http.php
sources/AppBundle/Controller/LegacyController.php
tests/behat/features/Admin/Events/Inscriptions.feature

Mise à jour de Smarty en version 5.4 lié a #1616

Upgrade Smarty 5.4

---

.github/workflows/ci.yml

On prend en compte les différents Dockerfiles dans la clé.

Amélioration de la clé de cache Docker

---

app/config/routing.yml
composer.json
composer.lock
sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
tests/behat/features/PublicSite/Sitemaps.feature

Mise à jour du bundle  `presta/sitemap-bundle`
+ ajout de test fonctionnel sur les sitemaps

Mise à jour de presta/sitemap-bundle

---

app/config/routing_dev.yml
sources/AppBundle/Association/CompanyMembership/InvitationMail.php
sources/AppBundle/Controller/Event/CFP/EditAction.php
sources/AppBundle/Controller/Event/CFP/InviteAction.php
sources/AppBundle/Controller/Event/CFP/ProposeAction.php
sources/AppBundle/Controller/Event/CFP/SpeakerAction.php
sources/AppBundle/Controller/Legacy/Forum2016SessionsAction.php
sources/AppBundle/Event/Sponsorship/SponsorshipLeadMail.php
sources/AppBundle/Event/Talk/InvitationFormHandler.php
sources/AppBundle/Event/Ticket/SponsorTokenMail.php
sources/AppBundle/Listener/LocaleEventSubscriber.php
sources/AppBundle/Slack/MessageFactory.php
sources/AppBundle/SpeakerInfos/Form/HotelReservationType.php
tests/units/AppBundle/Notifier/SlackNotifier.php

On correction encore de dépréciations.

Correction de dépréciations

---

sources/Afup/Bootstrap/Http.php
sources/AppBundle/Association/Model/CompanyMember.php
sources/AppBundle/Association/Model/GeneralMeetingQuestion.php
sources/AppBundle/Association/Model/User.php
sources/AppBundle/Controller/Admin/Event/RoomAction.php
sources/AppBundle/Event/Model/Planning.php
sources/AppBundle/Event/Model/Repository/SponsorScanRepository.php
sources/AppBundle/Event/Model/Speaker.php
sources/AppBundle/Event/Model/SponsorScan.php

Encore d'autres corrections liées au niveau 3 de PHPStan.
Il n'en reste plus qu'une vingtaine après ça, mais elles sont plus compliquées donc ce sera dans d'autres PRs.

Corrections PHPStan niveau 3

---

sources/AppBundle/Association/Model/Repository/UserRepository.php
sources/AppBundle/Command/ScrappingMeetupEventsCommand.php
sources/AppBundle/Event/Model/Repository/MeetupRepository.php

Cela permet d'avoir les infos à jour en cas de modifications.

Mise à jour des meetup existants

---

sources/Afup/Association/Cotisations.php

C'est bloquant pour l'ajout manuel d'une cotisation (que j'ai besoin de faire).

Correction de la création de cotisation

---

app/config/services.yml
composer.json
composer.lock
db/seeds/Articles.php
phinx.php
sources/AppBundle/Controller/Website/NewsController.php
sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
templates/site/news/list.html.twig
templates/site/pager.html.twig
tests/behat/features/Admin/Site/AdminSiteArticles.feature

Traitre l'issue : https://github.com/afup/web/issues/1680

#1680 ajout des listes des actualités dans le sitemap

---

app/config/routing.yml
sources/AppBundle/Controller/Website/TalksController.php
sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
templates/site/talks/list.html.twig

Amélioration SEO en ajoutant des pages dans le sitemap.
Issue #1681

#1681 ajout de pages dans le sitemap

---

app/config/services.yml

Première PR de ménage de la config des services.
On commence avec Planete PHP.

Nettoyage de la config des services de Planete PHP

---

clevercloud/cron.json

Modification de l'heure de post auto pour passage à l'heure d'été

---

app/config/services.yml

Ici on fait `AppBundle\Antennes` et `AppBundle\Association`

Simplification de la config des services

---

app/config/services.yml
composer.json
composer.lock
htdocs/app.php
htdocs/templates/administration/compta_banque.html
htdocs/templates/administration/compta_conf_evenement.html
templates/site/base.html.twig

Toujours en préparation de la montée de version de Symfony, on supprime des dépréciations.

On supprime des dépréciations

---

.gitignore
.php-cs-fixer.php
composer.json
composer.lock
htdocs/pages/administration/compta_journal.php
sources/Afup/Forum/Forum.php

On met à jour PHP CS Fixer en version 3

Mise à jour de PHP CS Fixer

---

htdocs/pages/administration/forum_inscriptions.php
htdocs/pages/administration/site_feuilles.php
htdocs/templates/administration/cotisations.html
htdocs/templates/administration/forum_inscriptions.html
sources/Afup/Association/Cotisations.php
sources/Afup/Comptabilite/Facture.php
sources/Afup/Forum/Facturation.php
sources/Afup/Forum/Inscriptions.php
sources/AppBundle/Association/Model/CompanyMember.php
sources/AppBundle/Association/UserMembership/SeniorityComputer.php
sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ListAction.php
sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ListingAction.php
sources/AppBundle/Controller/Website/MemberController.php
sources/AppBundle/Controller/Website/MemberShipController.php
sources/AppBundle/Event/Form/Support/EventHelper.php
sources/AppBundle/Event/Model/GithubUser.php
sources/AppBundle/Event/Model/Lead.php
sources/AppBundle/GeneralMeeting/GeneralMeetingRepository.php
sources/AppBundle/TechLetter/Model/TechLetterFactory.php

Corrections de quelques type en préparation de la montée de version de PHP 8

Correction de quelques types / erreurs

---

sources/AppBundle/Controller/Admin/Speaker/SpeakerRegisterAction.php
sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
sources/AppBundle/Event/Model/Repository/TicketRepository.php
sources/AppBundle/Event/Validator/Constraints/CorporateMemberValidator.php
sources/AppBundle/SpeakerInfos/Form/HotelReservationType.php

Quelques corrections niveau 4 de PHPStan sans lien particulier.

Corrections PHPStan

---

db/seeds/Tarif.php
tests/behat/features/Admin/Events/TokensVIsiteurs.feature

On ajoute le tarif spécial dans les fixtures et un test pour valider le lien vers les tokens.

Tarif spécial forum : fixture + test

---

sources/AppBundle/Antennes/Antenne.php
sources/AppBundle/Antennes/AntennesCollection.php
sources/AppBundle/Antennes/City.php
sources/AppBundle/Antennes/LegendAttachment.php
sources/AppBundle/Antennes/Map.php
sources/AppBundle/Antennes/Meetup.php
sources/AppBundle/Antennes/Point.php
sources/AppBundle/Antennes/Position.php
sources/AppBundle/Antennes/Socials.php
templates/site/offices.html.twig

J'avais hâte de pouvoir faire ça 😄

Migration des DTOs des antennes en PHP 8

---

sources/Afup/Association/Cotisations.php
tests/behat/features/MembersArea/Index.feature

Correction de l'issue #1769 en castant le timestamp reçu de la base de données.
Ajout des tests e2e pour valider la correction.

Correction de l'envoi de la cotisation par email

---

.github/workflows/ci.yml

Cette action gére elle-même le cache composer.

Utilisation de `ramsey/composer-install` dans la CI

---

htdocs/pages/administration/forum_facturation.php
htdocs/pages/administration/forum_inscriptions.php
htdocs/pages/administration/forum_planning.php
htdocs/pages/administration/forum_sessions.php
sources/Afup/fonctions.php

Pour faire suite à ce commentaire : https://github.com/afup/web/pull/1784#issuecomment-2871247496

Redirection vers les pages avec `id_forum`

---

sources/Afup/fonctions.php
sources/AppBundle/Controller/Admin/Event/RedirectEventFromSessionListener.php
tests/support/IntegrationTestCase.php
tests/unit/AppBundle/Event/Model/EventTest.php

Toujours dans le cadre du https://github.com/afup/web/pull/1785 on corrige les cas mergés entretemps, cela permettra de faire passer la PR en vert avant de la merger.

correctif de règles rector

---

db/seeds/Session.php
sources/AppBundle/Event/Model/Repository/PlanningRepository.php
tests/behat/bootstrap/FeatureContext.php
tests/behat/features/Api/Talks/OpenfeedbackExport.feature

Fix la récupération de la data planning en rajoutant la bonne timezone

Fix timezone des plannings

---

app/config/config.yml
templates/admin/event/speakers_expenses.html.twig
templates/admin/event/speakers_management.html.twig
tests/behat/features/Admin/AdminInfosSpeakers.feature

Cela fait suite à une demande d'Amélie.

Menu `Venue speakers` renommé en `Infos speakers`

---

db/seeds/Session.php
sources/AppBundle/Controller/Event/VoteController.php
sources/AppBundle/Event/Model/Vote.php
tests/behat/bootstrap/FeatureContext.php
tests/behat/features/EventPages/Cfp.feature

On corrige les derniers bug laissé pour le vote du CFP.
Cette partie n'était pas testée alors j'ai ajouter un test fonctionnel.

Corrections pour le vote du CFP

---

sources/AppBundle/Calendar/IcsPLanningGenerator.php
sources/AppBundle/Calendar/JsonPlanningGenerator.php
sources/AppBundle/Command/VideosDataCommand.php
sources/AppBundle/Controller/Admin/Speaker/SpeakerRegisterAction.php
sources/AppBundle/Controller/Event/BlogController.php
sources/AppBundle/Event/JsonLd.php
sources/AppBundle/Event/Model/Repository/TalkRepository.php
sources/AppBundle/Event/Model/TalkAggregate.php
sources/AppBundle/Event/Speaker/SpeakerPage.php
sources/AppBundle/Openfeedback/OpenfeedbackJsonGenerator.php
templates/blog/planning.html.twig
templates/blog/program.html.twig

Le tableau pose des problèmes d'analyse statique.

Refactor d'un array en DTO

---

sources/AppBundle/Association/Model/Repository/CompanyMemberRepository.php

Recherche des personnes morales insensible à la casse

---

sources/AppBundle/Association/Model/Repository/UserRepository.php

Ref https://github.com/afup/web/issues/1828 
C'est du code GDD (Github Driven Dev)

User - search with lower case

---

app/config/bundles.php
composer.json
composer.lock
sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
sources/AppBundle/Indexation/Meetups/MeetupClient.php
sources/AppBundle/SocialNetwork/Bluesky/BlueskyTransport.php
sources/AppBundle/TechLetter/Model/TechLetterFactory.php
tests/unit/AppBundle/Indexation/Meetups/MeetupClientTest.php
tests/unit/AppBundle/TechLetter/Model/TechLetterFactoryTest.php

Cela permet principalement d'avoir le cache activé correctement par défaut pour améliorer les performances.

Utilisation du bundle Valinor

---

htdocs/pages/administration/forum_sessions.php

J'ai ajouté la case en cocher en dernier dans le formulaire, à voir s'il y a un emplacement plus adapté

CPF : afficher l'autorisation du partage aux antennes dans l'administration

---

composer.json
composer.lock
sources/AppBundle/Controller/Event/CFP/EditAction.php
sources/AppBundle/Controller/Event/EventActionHelper.php

La lib `phpstan/phpstan-beberlei-assert` permet à PHPStan de comprendre les assertions.

Modernisation du typage

---

htdocs/pages/administration/forum_sessions.php

Je n'ai pas trouvé d'option pour faire ça plus propre 😭

Utilisation de l'année en cours comme valeur par défaut

---

app/config/services.yml
sources/Afup/Droits.php
sources/AppBundle/Controller/Website/MemberShipController.php

C'est en préparation pour le découper en plusieurs classes.

Nettoyage du controller MemberShip
